### PR TITLE
Cleanup time

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/431)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 20 of 20 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 13 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/431)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Oh man, that calendar date stuff. Fun times.

**Comment by lesserwhirls** [comment]
Thanks @JohnLCaron !

**Pull request merged**
