### PR TITLE
GridNew ui: change zoom and pan to work like google maps.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/813)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
This is great! I can't wait to try it out!

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/813#-:-MiTG8rkAB69qj1mx1-y:b6wop24)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnLCaron)

___
*[toolsui/uicdm/src/main/java/ucar/nc2/ui/geoloc/Navigation.java, line 388 at r2](https://reviewable.io/reviews/unidata/netcdf-java/813#-MiTFtX3DZ5zbqs5024h:-MiTFtX3DZ5zbqs5024i:b1j2xog) ([raw file](https://github.com/unidata/netcdf-java/blob/1aa44ae2d0f6aa91a68b187790b68c0b8066e64c/toolsui/uicdm/src/main/java/ucar/nc2/ui/geoloc/Navigation.java#L388)):*
> ```Java
> 
> /*
>  * Notes for zoom calculations, because Math is Hard (TM)
> ```

Much better than the approach of  "it is trivial to see that..." and pointing to the final result

**Review by lesserwhirls — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/813)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnLCaron)

**Comment by JohnLCaron** [comment]
yeah  i really like it. check out the grid subsetting tool also :

[Screenshot from 2021-08-31 16-19-37](https://user-images.githubusercontent.com/613568/131583196-5b8dc7c8-aa8e-42a0-b991-6c50d295e0fd.png)

**Comment by JohnLCaron** [comment]
oops looks like i broke the subsetting tool. ill get that fixed.

**Comment by JohnLCaron** [comment]
nevermind, it still works. try it on the curvilinear grids, let me know what you think: eg

cdmUnitTest/conventions/cf/signell/signell_bathy_fixed.nc
cdmUnitTest/transforms/UTM/artabro_20120425.nc

grid lines work, also

**Pull request merged**
