### PR TITLE
Coord axes

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/526)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
Is the idea here to bring some of the Feature Type semantics into the dataset layer (the more generic `Coordinate*` -> `Grid*`) as well as preparing to make these immutable?

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/526#-:-MK0-MY8AMdQEWQ0LvJD:b-iy1wlx)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by JohnLCaron** [comment]
The tentative idea is to remove duplicate code from dataset coordinate classes, and place it in new "feature type" classes like grid, point, radial, etc. Not sure how successful it will be, experimenting now with new grid package. Not sure if it will really make things simpler. 

The deprecations here reference code thats not yet done, so will change as things progress.

**Comment by lesserwhirls** [comment]
Sounds good!

**Pull request merged**
