### PR TITLE
Grib iosp builder

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/164)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Just a minor question - will pick up Unidata/netcdf-java#163 with this one since it's included.

**Comment by JohnLCaron** [comment]
NcMLReader.writeNcMLToFile seems wrong (writing from a reader class). Its a static method, it could go anywhere.

Not sure who calls it (TDS?) . Im thinking maybe we should move it somewhere else (NcmlWriter?)

What do you think?

**Comment by lesserwhirls** [comment]
The TDS codebase does not call it. A google search didn't turn up anything useful. I don't really see another method for reading NcML from an input stream and writing out a netCDF file to disk, and we do use it in ToolsUI to read text from the NcML editor and write it to a netCDF file:

https://github.com/Unidata/netcdf-java/blob/270500e8f1d5d35e1b19e8890e3c1ec2662a0641/uicdm/src/main/java/ucar/nc2/ui/op/NcmlEditor.java#L298-L311

The current `NcmlFileWriter` seems to be focused on writing actual NcML, but I can't think of a better place. We could stuff the logic inside the `NcmlEditor.writeNetcdf` method since there isn't much involved (only five lines), but that does not feel 100% right either.

**Comment by JohnLCaron** [comment]
I think we should eliminate unneeded methods. We can put the code in NcmlEditor if needed.

Would be good to get this PR in, as I have another one ready to go.

**Comment by lesserwhirls** [comment]
Sounds good to me. Merging now. Thanks @JohnLCaron!

**Pull request merged**
