### PR TITLE
Ncmlwriter

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/235)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
> Reviewed 103 of 103 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/235)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnLCaron)

___
*[cdm/core/src/main/java/thredds/client/catalog/builder/package.html, line 12 at r1](https://reviewable.io/reviews/unidata/netcdf-java/235#-M36tTbqA1mPz7z359tQ:-M36tTbrEqsYXHySLP5H:bm7fnaa) ([raw file](https://github.com/unidata/netcdf-java/blob/8ffdf809536128b5141758008ade0fac9196437c/cdm/core/src/main/java/thredds/client/catalog/builder/package.html#L12)):*
> ```HTML
> <body>
> <pre>
>   NOT PUBLIC API - DO NOT USE: THREDDS Catalog builders.
> ```

Many of the public constructors for classes in `thredds.client.catalog` are marked as `/** @deprecated use builder */`. If the builders in `thredds.client.catalog.builder` are not part of the public API, will the builders live somewhere else? How should a user open a client catalog? Is the plan to expose the builders from `thredds.client.catalog.builder` through the classes in `thredds.client.catalog`?
___
*[cdm/core/src/main/java/ucar/nc2/package.html, line 8 at r1](https://reviewable.io/reviews/unidata/netcdf-java/235#-M36uk637h20v4DmvE6F:-M36uk637h20v4DmvE6G:b-n7kbr5) ([raw file](https://github.com/unidata/netcdf-java/blob/8ffdf809536128b5141758008ade0fac9196437c/cdm/core/src/main/java/ucar/nc2/package.html#L8)):*
> ```HTML
> <HTML>
> <HEAD>
>   <TITLE>package ucar.ma2</TITLE>
> ```

Shouldn't this be package ucar.nc2?
___
*[cdm/core/src/main/java/ucar/nc2/ft/point/package.html, line 7 at r1](https://reviewable.io/reviews/unidata/netcdf-java/235#-M36w0EVBHxWvfp-De5y:-M36w0EW0FR6hoA3mbTy:b748om5) ([raw file](https://github.com/unidata/netcdf-java/blob/8ffdf809536128b5141758008ade0fac9196437c/cdm/core/src/main/java/ucar/nc2/ft/point/package.html#L7)):*
> ```HTML
> </head>
> <body bgcolor="#FFFFFF">
> <h3>Implementation of Point Feature Types</h3>
> ```

Add "DEPRECATED API - WILL BE REPLACED: "? Or is the plan to keep ucar.nc2.ft.point? cdm/core/src/main/java/ucar/nc2/ft/package.html seems to indicate it is not staying.
___
*[cdm/core/src/main/java/ucar/nc2/util/log/LoggerFactory.java, line 12 at r1](https://reviewable.io/reviews/unidata/netcdf-java/235#-M3721Za0Vvpg6zzft_G:-M3721Zb5wwY86gcyptJ:bmvm3rs) ([raw file](https://github.com/unidata/netcdf-java/blob/8ffdf809536128b5141758008ade0fac9196437c/cdm/core/src/main/java/ucar/nc2/util/log/LoggerFactory.java#L12)):*
> ```Java
>  * Allows us to keep log4j dependencies out of the cdm
>  *
>  * TODO used by TDS?
> ```

Neither `ucar.nc2.util.log.LoggerFactory` nor `ucar.nc2.util.log.LoggerFactoryImpl` are used by the TDS as far as I can tell.
___
*[cdm/core/src/main/java/ucar/nc2/util/net/URLStreamHandlerFactory.java, line 19 at r1](https://reviewable.io/reviews/unidata/netcdf-java/235#-M3747ll7GKfm9a6Tj3y:-M3747ll7GKfm9a6Tj3z:b-g83vey) ([raw file](https://github.com/unidata/netcdf-java/blob/8ffdf809536128b5141758008ade0fac9196437c/cdm/core/src/main/java/ucar/nc2/util/net/URLStreamHandlerFactory.java#L19)):*
> ```Java
> public class URLStreamHandlerFactory implements java.net.URLStreamHandlerFactory {
> 
>   public static org.slf4j.Logger log = ucar.httpservices.HTTPSession.log; // WTF?
> ```

Yikes, that's no good. I bet there is more than one place where this is happening. I'll take a look.
___
*[cdm/core/src/main/java/ucar/nc2/write/package.html, line 7 at r1](https://reviewable.io/reviews/unidata/netcdf-java/235#-M375OPJ4HRSptpGJG8X:-M375OPJ4HRSptpGJG8Y:b-dccmjn) ([raw file](https://github.com/unidata/netcdf-java/blob/8ffdf809536128b5141758008ade0fac9196437c/cdm/core/src/main/java/ucar/nc2/write/package.html#L7)):*
> ```HTML
> <HTML>
> <HEAD>
> <TITLE>package ucar.nc2</TITLE>
> ```

package ucar.nc2.write ?

**Comment by JohnLCaron** [comment]
> 
> > ```
> > <body>
> > <pre>
> >   NOT PUBLIC API - DO NOT USE: THREDDS Catalog builders.
> > ```
> 
> Many of the public constructors for classes in `thredds.client.catalog` are marked as `/** @deprecated use builder */`. If the builders in `thredds.client.catalog.builder` are not part of the public API, will the builders live somewhere else? How should a user open a client catalog? Is the plan to expose the builders from `thredds.client.catalog.builder` through the classes in `thredds.client.catalog`?

My intention is to rewrite thredds.client.catalog with the builders inside, possibly using @Autovalue. Im unsure whether I can do that in ver5, or if it has to be in ver6. Also unclear whether builders have to be public at all, other than maybe for testing? I guess that the main use is to read a xml doc and get back an object tree?

So, my reasoning is to mark stuff deprecated as a warning, even if we dont yet have the replacement. Thoughts?

**Comment by JohnLCaron** [comment]
> > ```
> > </head>
> > <body bgcolor="#FFFFFF">
> > <h3>Implementation of Point Feature Types</h3>
> > ```
> 
> Add "DEPRECATED API - WILL BE REPLACED: "? Or is the plan to keep ucar.nc2.ft.point? cdm/core/src/main/java/ucar/nc2/ft/package.html seems to indicate it is not staying.

Yes, all below ucar.dt, ft, ft2 are deprecated. I was just being lazy. Added one to all subpackages

**Comment by JohnLCaron** [comment]
Oops, I just made those changes on the wrong PR. Hmmm, is there something easy to do?

**Comment by JohnLCaron** [comment]
I think if you accept this one, I can merge with other changes and submit another PR.

**Comment by lesserwhirls** [comment]
> > > ```
> > > <body>
> > > <pre>
> > >   NOT PUBLIC API - DO NOT USE: THREDDS Catalog builders.
> > > ```
> > 
> > 
> > Many of the public constructors for classes in `thredds.client.catalog` are marked as `/** @deprecated use builder */`. If the builders in `thredds.client.catalog.builder` are not part of the public API, will the builders live somewhere else? How should a user open a client catalog? Is the plan to expose the builders from `thredds.client.catalog.builder` through the classes in `thredds.client.catalog`?
> 
> My intention is to rewrite thredds.client.catalog with the builders inside, possibly using @autovalue. Im unsure whether I can do that in ver5, or if it has to be in ver6. Also unclear whether builders have to be public at all, other than maybe for testing? I guess that the main use is to read a xml doc and get back an object tree?
> 
> So, my reasoning is to mark stuff deprecated as a warning, even if we dont yet have the replacement. Thoughts?

I think the main use is to read an xml file (local file, as a string, or stream) and get back an object tree. However, based on some questions I've been getting I think there are users out there who want to build their own client catalogs using the netCDF-Java API, perhaps as a way of translating between THREDDS Client Catalogs and other catalog-like specs.

**Comment by lesserwhirls** [comment]
> I think if you accept this one, I can merge with other changes and submit another PR.

Sounds like a plan to me. Merging this one in now. Thanks @JohnLCaron!

**Comment by ethanrd** [comment]
> there are users out there who want to build their own client catalogs using the netCDF-Java API

+1

**Comment by JohnLCaron** [comment]
ok, good to know. Ill make sure the builders stay public in ver6.

**Pull request merged**
