### PR TITLE
Deprecate CFGridCoverageWriter2, replace with CFGridCoverageWriter.

### PR DESCRIPTION
**Pull request by JohnLCaron**
Add test compare.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/315)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/315)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnLCaron)

___
*[cdm/core/src/main/java/ucar/nc2/Dimensions.java, line 51 at r1](https://reviewable.io/reviews/unidata/netcdf-java/315#-M93AASl307TNyky6gf3:-M93AASl307TNyky6gf4:bl6x4ms) ([raw file](https://github.com/unidata/netcdf-java/blob/11812d83d009cc46b30bd163c408f6e1643dc244/cdm/core/src/main/java/ucar/nc2/Dimensions.java#L51)):*
> ```Java
>   }
> 
>   /** Get the toyal number of elements the dimensions represent. */
> ```

Minor typo
___
*[cdm/core/src/main/java/ucar/nc2/dt/grid/CFGridWriter2.java, line 30 at r1](https://reviewable.io/reviews/unidata/netcdf-java/315#-M93BxPD2p150wS5hBoC:-M93BxPD2p150wS5hBoD:bel0nce) ([raw file](https://github.com/unidata/netcdf-java/blob/11812d83d009cc46b30bd163c408f6e1643dc244/cdm/core/src/main/java/ucar/nc2/dt/grid/CFGridWriter2.java#L30)):*
> ```Java
>  * Write CF compliant gridded data version 2.
>  * 
>  * @deprecated use CFCoverageWriter.
> ```

Should this be `CFGridCoverageWriter` instead of `CFCoverageWriter`? Maybe

~~~java
 *
 * @deprecated Use {@link ucar.nc2.ft2.coverage.writer.CFGridCoverageWriter}
 *
~~~

**Comment by lesserwhirls** [comment]
Looks good - just a few minor things to tweak. Thanks @JohnLCaron!

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/315)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnLCaron)

**Review by lesserwhirls — APPROVED** [review]

**Comment by lesserwhirls** [comment]
Thanks @JohnLCaron!

**Pull request merged**
