### PR TITLE
Only deprecate Misc methods with clear alternatives.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/307)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 47 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/307)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Looks good to me 👍 

On a related note, since we're already pulling in Guava, do you think it would make sense to have the `nearlyEquals` methods (and related) wrap the `fuzzyEquals` methods from `com.google.common.math`?

**Comment by JohnLCaron** [comment]
Agree about using fuzzyEquals. I didnt have time to unravel the absolute vs relative difference. I think fuzzyEquals is absolute. So I thought Id submit what I had ready. But some more thought is called for.

**Comment by lesserwhirls** [comment]
I'll try to circle around to the `fuzzyEquals` stuff after I wrap up the work I'm doing over on the TDS. Thanks @JohnLCaron!

**Pull request merged**
