### PR TITLE
Update MessageScanner.java

### PR DESCRIPTION
**Pull request by zfy68**
## Description of Changes

_is that useful ? about  m.setTableLookup(embedTable.getTableLookup())  could some ncep bufr(gdas data format) decode error!_

## PR Checklist

- [x] Link to any issues that the PR addresses
- [ ] Add labels
- [x] Open as a [draft PR](https://github.com/Unidata/netcdf-java/pull/1084)
       until ready for review
- [x] Make sure GitHub tests pass
- [ ] Mark PR as "Ready for Review"

### CODE REVIEW

**Comment by zfy68** [comment]
> [CLA assistant check](https://cla-assistant.io/Unidata/netcdf-java?pullRequest=1084) All committers have signed the CLA.

ok

**Comment by haileyajohnson** [comment]
What issue(s) is this intended to fix?

**Comment by zfy68** [comment]
> What issue(s) is this intended to fix?

Hello, I am personally researching GDAS(Prepbufr) data.
I obtained the GDAS - Daily BUFR Files product data for 2022 from the [official website](https://www.ncei.noaa.gov/products/weather-climate-models/global-data-assimilation).

**In the first step**, I tried to parse the data through the netcdf-java tool and source code, but I encountered a roadblock. Error codes and error files are as follows:
1) error code:

image

 2) error file see  annex :

[ gdas.t00z.1bamua.tm00.bufr_d](https://drive.google.com/file/d/1mKE_KXzpQyG0R3tUJc6ud-FwtGRQy0jA/view?usp=drive_web)

**In the second step**, I re-obtained the product data in 2020, parsed the data through netcdf-java, and found that it was normal. normal file see annex :
[ gdas.t12z.adpsfc.tm00.bufr_d.nr](https://drive.google.com/file/d/1y82ey_ZSL-gkKBYo6vDMC94_gTOgw2ao/view?usp=drive_web)


**In the end**, after many attempts, I modified the above code and it can be parsed normally. On the one hand, I would like to ask the role of the next method? Does it not pass only when the BUFR template has nested tables? Perhaps the template has changed, but the source code has not been updated.
By modifying the secondary code is my current way of solving the problem.

**Comment by JohnLCaron** [comment]
Hi @zfy68 :

I dont have access to the data files. Can you allow all access, or attach to GitHub if they are not too big?

John

**Comment by zfy68** [comment]
> Hi @zfy68 :
> 
> I dont have access to the data files. Can you allow all access, or attach to GitHub if they are not too big?
> 
> John

yes, these file too big.

**Comment by JohnLCaron** [comment]
I have requested access to those data files on google drive.

**Comment by zfy68** [comment]
Hi @JohnLCaron :
I have turned on viewing permissions.

**Comment by zfy68** [comment]
Hi, @haileyajohnson https://github.com/Unidata/netcdf-java/pull/1084#issuecomment-1254349616

**Comment by tdrwenski** [comment]
Apologies for the delay in getting to this issue. It appears that Netcdf-java fails at reading the embedded table in this file. In addition, as also shown in your screenshot, the `isBitCountOk` returns false, so there could be additional issues reading this file.

Thank you for investigating this, however, I do not think commenting this out is the correct fix as this code works correctly for other bufr files with embedded tables. I have created a [new issue](https://github.com/Unidata/netcdf-java/issues/1184) to investigate other fixes for your problem and so I will close this PR.

**Comment by zfy68** [comment]
OK，I also use other bufr file，its no problem。

**Pull request closed without merging**
