### PR TITLE
Fix cdm-test failures

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/246)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
2020-04-09T00:08:51.8714691Z Err:1 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 hdf5-helpers amd64 1.10.0-patch1+docs-4
2020-04-09T00:08:51.8715172Z   Could not connect to azure.archive.ubuntu.com:80 (13.66.189.214), connection timed out
2020-04-09T00:08:51.8715722Z Err:2 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libaec0 amd64 0.3.2-2
2020-04-09T00:08:51.8716010Z   Unable to connect to azure.archive.ubuntu.com:http:

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — COMMENTED** [review]
I like that `builder()` no longer takes a parameter. I'm wondering if .build() should be parameterless as well...the calls to `build(null)` really stick out to me in this diff set.

> Reviewed 24 of 26 files at r1, 3 of 3 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/246#-:-M4Uf0CtCkiycFGJgIM9:b-jjhbhx)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by JohnLCaron** [comment]
> I like that `builder()` no longer takes a parameter. I'm wondering if .build() should be parameterless as well...the calls to `build(null)` really stick out to me in this diff set.
> 
> > Reviewed 24 of 26 files at r1, 3 of 3 files at r2, 3 of 3 files at r3.
> > _[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/246#-:-M4Uf0CtCkiycFGJgIM9:b-jjhbhx)_ status: :shipit: complete! all files reviewed, all discussions resolved

No, build() has to have the parent as parameter, as its the only way to set the parent Group. Setting the parent Group.Builder is rather a kludge, but at the moment stilll needed.

**Comment by JohnLCaron** [comment]
OTOH, could have a build() convenience routine for the common case of creating the root group.

**Comment by JohnLCaron** [comment]
Ok, I agree, Im adding Group.Builder.build()

**Comment by lesserwhirls** [comment]
A convenience method for the common case looks good to me, although I don't quite have my head wrapped all the way around the interplay between the `Group` `parentGroup` and the `Group.Builder` `parentGroup` at `build()` time. Perhaps I just need a :beer:

**Review by lesserwhirls — APPROVED** [review]

**Pull request merged**
