### PR TITLE
CmdrServer uses array.Array. Add shape to cmdr Data proto.

### PR DESCRIPTION
**Pull request by JohnLCaron**
Attribute uses array.Array.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/504)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 40 of 40 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/504)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnLCaron)

___
*[cdm/core/src/test/java/ucar/array/TestReadArrayCompare.java, line 51 at r1](https://reviewable.io/reviews/unidata/netcdf-java/504#-MIW1YqWATuU8le9dwWg:-MIW1YqWATuU8le9dwWh:b4hamrz) ([raw file](https://github.com/unidata/netcdf-java/blob/eaf6235b7ceba4b37f5d188dd4a6e889ac6cf131/cdm/core/src/test/java/ucar/array/TestReadArrayCompare.java#L51)):*
> ```Java
>       TestDir.actOnAllParameterized(TestDir.cdmUnitTestDir + "formats/hdf5/wrf/", ff, result);
>       // too slow
>       // TestDir.actOnAllParameterized(TestDir.cdmUnitTestDir + "formats/hdf5/xmdf/", ff, result);
> ```

It'd be nice to be able to use the `@Category(Slow.class)` annotation inside the method, but that's not how the junit category stuff works. However, we have to set a system property when we run gradle to allow the slow tests to run, and we *can* check for that. It would be good to stick with the category annotation where we can, but here we could do something like this:

~~~java
if (Boolean.getBoolean("runSlowTests")) {
  TestDir.actOnAllParameterized(TestDir.cdmUnitTestDir + "formats/hdf5/xmdf/", ff, result);
  TestDir.actOnAllParameterized(TestDir.cdmUnitTestDir + "formats/hdf5/", ff, result, false);
}
~~~ 

I don't like having that hardcoded, so we could probably put the property name in a class in the `cdm-test-utils` subproject, but for now, we would not be commenting out these lines. I'd be happy to add this in in another PR, or if you'd like to snag it later that works too.
___
*[cdm/core/src/test/java/ucar/nc2/TestAttribute.java, line 253 at r1](https://reviewable.io/reviews/unidata/netcdf-java/504#-MIW515k3wenpZ77aSKR:-MIW515k3wenpZ77aSKS:b-shkl3a) ([raw file](https://github.com/unidata/netcdf-java/blob/eaf6235b7ceba4b37f5d188dd4a6e889ac6cf131/cdm/core/src/test/java/ucar/nc2/TestAttribute.java#L253)):*
> ```Java
> 
>   /*
>    * LOOK are we allowing opagq atttributes?
> ```

I believe opaque typed attributes are valid.

**Comment by JohnLCaron** [comment]
ready

**Comment by JohnLCaron** [comment]
In terms of opaque attributes, do we actually have any examples, or is it just that netcdf4 allows them?

**Comment by JohnLCaron** [comment]
if (Boolean.getBoolean("runSlowTests")) {
  TestDir.actOnAllParameterized(TestDir.cdmUnitTestDir + "formats/hdf5/xmdf/", ff, result);
  TestDir.actOnAllParameterized(TestDir.cdmUnitTestDir + "formats/hdf5/", ff, result, false);
}
Dont think I knew about Boolean.getBoolean(). Ive added this.

**Comment by JohnLCaron** [comment]
Dont think I knew about Boolean.getBoolean(). Ive added this in the following PR. This one should go in as is.

**Review by lesserwhirls — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/504)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
> In terms of opaque attributes, do we actually have any examples, or is it just that netcdf4 allows them?

Let me see what I can find. I think I saw a test that creates one in the C library...

**Pull request merged**
