### PR TITLE
Add GridHorizCurvilinear for curvilinear lat/lon (2d).

### PR DESCRIPTION
**Pull request by JohnLCaron**
Add GridHorizCurvilinear extends GridHorizCoordinateSystem to deal with curvilinear lat/lon (no projection).

GridHorizCoordinateSystem now has Iterable<CoordBounds> bounds().
Add Curvilinear projection (not done).
deprecate Projection.constructCopy().
SubsetTimeHelper handles timePresent.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/764)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Comment by lesserwhirls** [comment]
Would you mind doing a rebase?

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 30 of 49 files at r1, 19 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/764)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnLCaron)

**Pull request merged**
