### PR TITLE
Cleanup ucar.ma2; Section, Range are Immutable.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/470)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
test failure seems to be:

2020-09-09T21:59:11.3589597Z ucar.nc2.util.net.TestHTTPSession > testAgent FAILED
2020-09-09T21:59:11.3591777Z     ucar.httpservices.HTTPException: org.apache.http.conn.ConnectTimeoutException: Connect to thredds-dev.unidata.ucar.edu:443 [thredds-dev.unidata.ucar.edu/128.117.149.3] failed: connect timed out
2020-09-09T21:59:11.3593443Z         at ucar.httpservices.HTTPMethod.executeRaw(HTTPMethod.java:385)
2020-09-09T21:59:11.3594088Z         at ucar.httpservices.HTTPMethod.execute(HTTPMethod.java:327)
2020-09-09T21:59:11.3594701Z         at ucar.nc2.util.net.TestHTTPSession.testAgent(TestHTTPSession.java:93)
...

Im going to mark these as flaky, unless you have a better idea?

  @Ignore("flaky")

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 49 of 49 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/470)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnLCaron)

___
*[cdm/core/src/main/java/ucar/ma/Array.java, line 117 at r2](https://reviewable.io/reviews/unidata/netcdf-java/470#-MGrp0-WCIWNs_Br00V2:-MGrp0-WCIWNs_Br00V3:b7fm4ou) ([raw file](https://github.com/unidata/netcdf-java/blob/8a88860e2e73c8d5c5df14c31e7bc37b9a6e3d8f/cdm/core/src/main/java/ucar/ma/Array.java#L117)):*
> ```Java
>   public abstract T sum();
> 
>   public abstract T get();
> ```

Maybe we could use `varargs` for `get()`?
___
*[cdm/core/src/main/java/ucar/ma/Index.java, line 53 at r2](https://reviewable.io/reviews/unidata/netcdf-java/470#-MGrs2yZ7kTxytaPcJPg:-MGrs2yZ7kTxytaPcJPh:b4ml7xr) ([raw file](https://github.com/unidata/netcdf-java/blob/8a88860e2e73c8d5c5df14c31e7bc37b9a6e3d8f/cdm/core/src/main/java/ucar/ma/Index.java#L53)):*
> ```Java
> 
>   /** set current element at dimension 0 to v */
>   public Index set0(int v) {
> ```

Thinking these setN() methods could go to clean-up the API
___
*[cdm/core/src/main/java/ucar/ma/Index.java, line 95 at r2](https://reviewable.io/reviews/unidata/netcdf-java/470#-MGrsFm7CDfz9a9yPGff:-MGrsFm7CDfz9a9yPGfg:b32x8pf) ([raw file](https://github.com/unidata/netcdf-java/blob/8a88860e2e73c8d5c5df14c31e7bc37b9a6e3d8f/cdm/core/src/main/java/ucar/ma/Index.java#L95)):*
> ```Java
> 
>   /** set current element at dimension 0 to v0 */
>   public Index set(int v0) {
> ```

`varargs` for here as well?
___
*[cdm/core/src/main/java/ucar/ma/Strides.java, line 39 at r2](https://reviewable.io/reviews/unidata/netcdf-java/470#-MGrsTwv7X2Ho8mTRS5m:-MGrsTwv7X2Ho8mTRS5n:bepvw7c) ([raw file](https://github.com/unidata/netcdf-java/blob/8a88860e2e73c8d5c5df14c31e7bc37b9a6e3d8f/cdm/core/src/main/java/ucar/ma/Strides.java#L39)):*
> ```Java
>   ////////////////////////////////////////////////////////////////////////////////////////////////////////////////
> 
>   public int get(int v0) {
> ```

`varargs`?

**Review by lesserwhirls — COMMENTED** [review]
The machine room hosting the server thredds-dev.unidata.ucar.edu was down yesterday due to multiple power issues. It should be up now though. I'd say in general any test that relies on an external resource could be marked at potentially flaky. Let me give this some though on how we could deal with cases where we expect a failure due to lack of network connection, the remote resource being unavailable, etc., and make sure that information bubbles up to the test report. For this particular test, though, we could probably rely on the server that we spin up locally as part of the testing process anyways.

The comments I've added are more in the category thinking of a new API for the array interface, and not blockers for this PR. One thing that catches my eye here, though, is that we are going from `ucar.ma2` to `ucar.ma`, which seems confusing. I believe back in the day, it started life as `ucar.multiarray`, so I'm guessing we never had a `ucar.ma` in the past? Have we ever had a `ucar.array` package?

> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/470#-:-MGrtlHl1Dy5ENvzvi84:buk6v4y)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnLCaron)

**Comment by JohnLCaron** [comment]
agree ucar.array is better package name. will look at your other api suggestions. thanks for your careful reviews.

It doesnt look like we need to use thredds-dev here (?) should use a local server as you say. Also hoping to ditch httpservices altogether, maybe in version 7.

i will remove the flaky annotation for now. im cleaning up error messages with the word "failed" in it, so its easier to look at failures during review. there really ought to be a better UI than grepping for "failed", but whatever...

**Comment by JohnLCaron** [comment]
varargs for Strides, Array and Index is brilliant.

Index.set() is really for easing the transition from old. In fact, thats all Index is. Will wait to when we are transitioning to make final API cut.

**Pull request merged**
