### PR TITLE
deprecate lots of stuff (2)

### PR DESCRIPTION
**Pull request by JohnLCaron**
ucar.nc2.wmo, ucar.unidata.geoloc, ucar.unidata.io

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/232)

### CODE REVIEW

**Review by lesserwhirls — COMMENTED** [review]
> Reviewed 5 of 31 files at r1, 8 of 68 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/232)* status: 13 of 90 files reviewed, all discussions resolved (waiting on @lesserwhirls)

**Comment by lesserwhirls** [comment]
I just noticed you hadn't marked this one ready for review, but so far looks good to me. I had seen `@AutoValue` floating around before, but never really took at look to see what it did. Super cool that it's able to handle all of that boilerplate at compile time.

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
Awesome, thanks John!

> Reviewed 26 of 31 files at r1, 60 of 68 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/232#-:-M2seLUv5A1OFxvFHaLg:b-n4soxb)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
