### PR TITLE
Remove old NcML classes

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/377)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
If you approve previous PR, I can rebase and I think the conflicts will go away.

**Comment by JohnLCaron** [comment]
How come rebasing doesnt resolve the conflict?

**Comment by lesserwhirls** [comment]
The PR looks clear on my end now

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 81 of 81 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/377)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Looks good - ready to roll?

**Comment by JohnLCaron** [comment]
Roll it

**Pull request merged**
