### PR TITLE
Comparision cleanups

### PR DESCRIPTION
**Pull request by JohnLCaron**
Various fixes in new builder code, uncovered by comparing all the .nc files in unitTest.
more work is needed handling groups.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/205)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Looks like this and Unidata/netcdf-java#204 cover the same ground, plus commit 083a5ab? I'll go ahead and review this one.

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/205)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnLCaron)

___
*[cdm/core/src/main/java/ucar/nc2/dataset/NetcdfDataset.java, line 1588 at r1](https://reviewable.io/reviews/unidata/netcdf-java/205#-M-XkSNh7V0SFqn2HIHE:-M-XkSNh7V0SFqn2HIHF:b-lnboa) ([raw file](https://github.com/unidata/netcdf-java/blob/083a5ab31cde5729c8a165eb110cfc2ab4e080bd/cdm/core/src/main/java/ucar/nc2/dataset/NetcdfDataset.java#L1588)):*
> ```Java
>     // CoordinatesHelper has to wire the coordinate systems together
>     for (Variable v : this.variables) {
>       // LOOK StructureDS ??
> ```

Should we log a warning here?
___
*[cdm/core/src/main/java/ucar/nc2/internal/dataset/CoordSystemFactory.java, line 141 at r1](https://reviewable.io/reviews/unidata/netcdf-java/205#-M-Xkwyz5l-XpXh8LYzT:-M-Xkwz--yoLFr9TtBp2:bt40d0m) ([raw file](https://github.com/unidata/netcdf-java/blob/083a5ab31cde5729c8a165eb110cfc2ab4e080bd/cdm/core/src/main/java/ucar/nc2/internal/dataset/CoordSystemFactory.java#L141)):*
> ```Java
>         names.add(name.trim());
>       }
>       return names;
> ```

Out of curiosity, why return mid method instead of at the end as was done previously? 
___
*[cdm/core/src/main/java/ucar/nc2/internal/dataset/conv/M3IOConvention.java, line 53 at r1](https://reviewable.io/reviews/unidata/netcdf-java/205#-M-Xn9mHDwdZsg-dYJn8:-M-Xn9mHDwdZsg-dYJn9:b-uv4p61) ([raw file](https://github.com/unidata/netcdf-java/blob/083a5ab31cde5729c8a165eb110cfc2ab4e080bd/cdm/core/src/main/java/ucar/nc2/internal/dataset/conv/M3IOConvention.java#L53)):*
> ```Java
>  * @author plessel.todd@epa.gov
>  * @author caron
>  * @see <a href=
> ```

Minor: Can we update the URL to https://www.cmascenter.org/ioapi/? The one here is dead.
___
*[cdm/core/src/main/java/ucar/nc2/internal/dataset/conv/Nimbus.java, line 24 at r1](https://reviewable.io/reviews/unidata/netcdf-java/205#-M-XniR7E5ATJEp_IDEl:-M-XniR7E5ATJEp_IDEm:b2vvl8i) ([raw file](https://github.com/unidata/netcdf-java/blob/083a5ab31cde5729c8a165eb110cfc2ab4e080bd/cdm/core/src/main/java/ucar/nc2/internal/dataset/conv/Nimbus.java#L24)):*
> ```Java
>  * NCAR RAF / NIMBUS
>  * 
>  * @see "http://www.eol.ucar.edu/raf/Software/netCDF.html"
> ```

I wonder, for new things when adding a reference to a web doc, maybe we should use the wayback machine to capture a snapshot and reference that? For this URL, we'd have:

https://web.archive.org/web/20180621013727/https://www.eol.ucar.edu/raf/Software/netCDF.html

Since then, it's been moved. There is a redirect in place, but as long as the web archive is up, we will be good. Though, every URL has a finite life I suppose.
___
*[cdm/core/src/main/java/ucar/nc2/internal/dataset/conv/UnidataObsConvention.java, line 24 at r1](https://reviewable.io/reviews/unidata/netcdf-java/205#-M-XokPW-HERxbj_KqMi:-M-XokPW-HERxbj_KqMj:b-m57wam) ([raw file](https://github.com/unidata/netcdf-java/blob/083a5ab31cde5729c8a165eb110cfc2ab4e080bd/cdm/core/src/main/java/ucar/nc2/internal/dataset/conv/UnidataObsConvention.java#L24)):*
> ```
> http://www.unidata.ucar.edu/software/netcdf-java/formats/UnidataObsConvention.html
> ```
I can't find this in our docs (even 4.6.). I did find a copy from 2013 on the wayback machine: https://web.archive.org/web/20130713015813/www.unidata.ucar.edu/software/netcdf-java/formats/UnidataObsConvention.html

Should I rescue this, or is it obsolete at this point?

**Review by JohnLCaron — COMMENTED** [review]
Ready to go.

> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/205#-:-M-kx_g595wzjpV-Hhg1:b-s9qjvh)* status: all files reviewed, 4 unresolved discussions (waiting on @lesserwhirls)

___
*[cdm/core/src/main/java/ucar/nc2/dataset/NetcdfDataset.java, line 1588 at r1](https://reviewable.io/reviews/unidata/netcdf-java/205#-M-XkSNh7V0SFqn2HIHE:-M-kvXKjA8T_UPCHtWFu:b-clp0gu) ([raw file](https://github.com/unidata/netcdf-java/blob/083a5ab31cde5729c8a165eb110cfc2ab4e080bd/cdm/core/src/main/java/ucar/nc2/dataset/NetcdfDataset.java#L1588)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

Should we log a warning here?
</blockquote></details>

I elaborated on the TODO. Not yet sure if theres warning needed.
___
*[cdm/core/src/main/java/ucar/nc2/internal/dataset/CoordSystemFactory.java, line 141 at r1](https://reviewable.io/reviews/unidata/netcdf-java/205#-M-Xkwyz5l-XpXh8LYzT:-M-kw-1s1KBL4munHO55:b-7rl0kd) ([raw file](https://github.com/unidata/netcdf-java/blob/083a5ab31cde5729c8a165eb110cfc2ab4e080bd/cdm/core/src/main/java/ucar/nc2/internal/dataset/CoordSystemFactory.java#L141)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

Out of curiosity, why return mid method instead of at the end as was done previously? 
</blockquote></details>

done
___
*[cdm/core/src/main/java/ucar/nc2/internal/dataset/conv/Nimbus.java, line 24 at r1](https://reviewable.io/reviews/unidata/netcdf-java/205#-M-XniR7E5ATJEp_IDEl:-M-kwusS8wUc9SWOIww5:be2i2y) ([raw file](https://github.com/unidata/netcdf-java/blob/083a5ab31cde5729c8a165eb110cfc2ab4e080bd/cdm/core/src/main/java/ucar/nc2/internal/dataset/conv/Nimbus.java#L24)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

I wonder, for new things when adding a reference to a web doc, maybe we should use the wayback machine to capture a snapshot and reference that? For this URL, we'd have:

https://web.archive.org/web/20180621013727/https://www.eol.ucar.edu/raf/Software/netCDF.html

Since then, it's been moved. There is a redirect in place, but as long as the web archive is up, we will be good. Though, every URL has a finite life I suppose.
</blockquote></details>

I dont have a preference; I changed it to wayback url.
___
*[cdm/core/src/main/java/ucar/nc2/internal/dataset/conv/UnidataObsConvention.java, line 24 at r1](https://reviewable.io/reviews/unidata/netcdf-java/205#-M-XokPW-HERxbj_KqMi:-M-kxQ-I7zqqa1mpyEuD:bicfnka) ([raw file](https://github.com/unidata/netcdf-java/blob/083a5ab31cde5729c8a165eb110cfc2ab4e080bd/cdm/core/src/main/java/ucar/nc2/internal/dataset/conv/UnidataObsConvention.java#L24)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

> ```
> http://www.unidata.ucar.edu/software/netcdf-java/formats/UnidataObsConvention.html
> ```
I can't find this in our docs (even 4.6.). I did find a copy from 2013 on the wayback machine: https://web.archive.org/web/20130713015813/www.unidata.ucar.edu/software/netcdf-java/formats/UnidataObsConvention.html

Should I rescue this, or is it obsolete at this point?
</blockquote></details>

Definitely obsolete, I changed to wayback url.

**Comment by lesserwhirls** [comment]
Thanks @JohnLCaron!

**Pull request merged**
