### PR TITLE
GridNew: add tests, refactor CS subsetting, fix stuff.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/539)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Comment by JohnLCaron** [comment]
really ready

**Review by lesserwhirls — APPROVED** [review]
> Note kludge fix in old WRF files for LambertConformal. Should be verified / backported.

I can take a look at this. Thanks @johnlcaron!

> Reviewed 39 of 39 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/539#-:-MKepNe20hOMYtGwLvpi:b-5gownq)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnLCaron)

___
*[cdm/core/src/main/java/ucar/nc2/internal/grid/CoordinateAxis1DExtractor.java, line 249 at r2](https://reviewable.io/reviews/unidata/netcdf-java/539#-MKemrcFBm7lX8O4HfBP:-MKemrcGCoe-kx8qQBrM:bnjh5kv) ([raw file](https://github.com/unidata/netcdf-java/blob/5015cb9d60880c449aaca6ac4a987299e5fdbed8/cdm/core/src/main/java/ucar/nc2/internal/grid/CoordinateAxis1DExtractor.java#L249)):*
> ```Java
>           break;
>         }
>         // LOOK we could internally reorder.
> ```

I've been thinking about doing something like this (internally reordering) for unstructured grids

**Review by lesserwhirls — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/539)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnLCaron)

**Review by lesserwhirls — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/539)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
