### PR TITLE
protocol service provider strawman

### PR DESCRIPTION
**Pull request by JohnLCaron**
First pass "strawman" on using ServiceLoader for optional protocols, to get your input.
Do HDFS and S3 fit into this?

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Could also refactor ncml, cdmremote and thredds out of NetcdfDataset with this mechanism.

**Comment by lesserwhirls** [comment]
So HDFS and S3 work at the `RandomAccessFile` level, &agrave;l la `HTTPRandomAccessFile` and get hooked-up inside `NetcdfFile` (via `getRaf`). For those (and other extensions of `RandomAccessFile`), perhaps a similar approach could be taken (say, `RandomAccessFileProvider`)?

Then again, we can control what `RandomAccessFile` class is actually used at the `NetcdfFileProvider` level with `open`. At that point, we could pull all of the `RandomAccessFile` extensions out of NetcdfFile and refactor `NetcdfFile.getRaf()` to use the new `NetcdfFileProvider` infrastructure that you have here (would probably want to bump `netcdfFileProvider` up a level into `ucar.nc2`).

Either way, I like the way this is looking!

**Comment by JohnLCaron** [comment]
There has to be some way of telling the library to use the special RandomAccessFile, so I think that means it has to be a protocol service provider. Presumably they can use 

protected NetcdfFile(IOServiceProvider spi, ucar.unidata.io.RandomAccessFile raf, String location,
      ucar.nc2.util.CancelTask cancelTask)

So at the moment I think this is right way to handle HDFS and S3.

**Comment by JohnLCaron** [comment]
Since the goal is to allow these to be added without touching core code, I see that DatasetUrl needs to be modified to look for these providers, so that their protocol string doesnt have to be hardcoded there. So using enum ServiceType has to be generalized. So a bit more work to be done here.

**Comment by JohnLCaron** [comment]
Superceded by #128

**Pull request closed without merging**
