### PR TITLE
Deprecations for ucar.ma2.DataType.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/631)

### CODE REVIEW

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
> Reviewed 99 of 99 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/631)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnLCaron)

___
*[cdm/core/src/main/java/ucar/array/Arrays.java, line 6 at r1](https://reviewable.io/reviews/unidata/netcdf-java/631#-MW0fjjX-VG1bMMF7N-D:-MW0fjjX-VG1bMMF7N-E:b-ds6by6) ([raw file](https://github.com/unidata/netcdf-java/blob/631def2d4c719a11b8e1a1354702dba45aeab6b3/cdm/core/src/main/java/ucar/array/Arrays.java#L6)):*
> ```Java
>  */
> package ucar.array;
> ```

Are these new imports used?

**Comment by JohnLCaron** [comment]
Can you approve, @lesserwhirls?  I need to remove from latest PR in order to track down bug. Thanks.

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/631)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnLCaron)

**Comment by lesserwhirls** [comment]
Sorry for the delay - thanks @JohnLCaron!

**Pull request merged**
