### PR TITLE
Group searching2

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/267)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Remove keeping Dimension names (instead of Dimensions) in Variable.Builder, now that we have its parent Group.Builder. Clean up some of the workarounds from that.
Handle nested Structures correctly, esp in CoordSystemBuilder.
Some other cleanup and method renaming for clarity.

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 8 of 32 files at r1, 20 of 23 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/267)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Thanks @johnlcaron! This reminds me, I need hop down in the CF convention code and see how well we handle looking for things in group hierarchies given there are now some guidelines about in [CF](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#groups) about how to go about doing that.

**Pull request merged**
