### PR TITLE
fix typo in iosp docs

### PR DESCRIPTION
**Pull request by haileyajohnson**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/641)

### CODE REVIEW

**Comment by haileyajohnson** [comment]
This is the failing test: TestControllerS3. testGetInventoryTopBucketDelimiterAws
So I feel like that's not related...

**Comment by lesserwhirls** [comment]
Totally unrelated...bad assumptions on my part for a test. We temporarily disabled this test for PRs on the develop branch [by making this change](https://github.com/Unidata/netcdf-java/commit/47dfaae143357bd44570080d4e50309e457ed071). It still fails on Jenkins runs, so it won't get lost. Would you mind backporting that to this PR so we get it on 5?

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/641)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haileyajohnson)

**Review by lesserwhirls — APPROVED** [review]
Thanks @haileyajohnson!

> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/641#-:-MWkJibN5PomQJNlpsQZ:blbe0m5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haileyajohnson)

**Pull request merged**
