### PR TITLE
new DatasetUrl -> DatasetUrl.create()

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/311)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 14 of 14 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/311)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Looks good to me! Thanks @JohnLCaron!

**Comment by lesserwhirls** [comment]
I just noticed this was PR 311...how can I not:

[](http://www.youtube.com/watch?v=JjTjtJDZomw "311")

**Pull request merged**
