### PR TITLE
Disable fmrc, netcdf4 modules.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/393)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/393)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Does this need to go in before Unidata/netcdf-java#392?

**Comment by JohnLCaron** [comment]
Doesnt matter which order.

**Comment by JohnLCaron** [comment]
You could kick off a jenkins run after this is in.

**Comment by lesserwhirls** [comment]
Running at https://jenkins-aws.unidata.ucar.edu/view/John/job/john-caron-netcdf-java/15/

**Pull request merged**
