### PR TITLE
Hdf conventions

### PR DESCRIPTION
**Pull request by JohnLCaron**
Fix problems with nested Groups (part 1).
See list in TestCoordSysCompareMore for problems not yet fixed.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/253)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Would you mind rebasing this one? Thank you @JohnLCaron!

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 53 of 53 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/253)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Looks good on my end. Happy to merge this in now if it's ready.

**Comment by JohnLCaron** [comment]
ready

**Comment by lesserwhirls** [comment]
Thank you @JohnLCaron!

**Pull request merged**
