### PR TITLE
Update documentation gradle build

### LINKED ISSUE #663: make topnav shareable between subprojects
TopNav content should be shared by the netcdf docs subprojects (user guide, developer guide, ncml, and cdm).
For now, topnav content is not nested, but ideally all projects should be under one dropdown with subprojects nested.

### PR DESCRIPTION
**Pull request by lesserwhirls**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/668)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Would like to incorporate the results from this [discussion](https://github.com/Unidata/unidata-jekyll-theme/issues/15) before marking this ready for review.

**Comment by lesserwhirls** [comment]
Ok, I think this is finally ready. Here is a preview:

https://docs.unidata.ucar.edu/netcdf-java/index.html

(see the dev docs)

and

https://docs.unidata.ucar.edu/thredds/ncml/index.html

(note: the version selector is broken, but that will get fixed at the theme level)

**Comment by lesserwhirls** [comment]
This PR addresses Unidata/netcdf-java#663 ("make topnav shareable between subprojects") - see https://github.com/Unidata/netcdf-java/pull/668/files#diff-3229bec93ac4f99de171fae5417c08f146b264578397cdb9ab99dc648a5b2a31 for details on how it works.

**Review by haileyajohnson — CHANGES_REQUESTED** [review]
Looks great (except the one "BURF" typo)! Thanks for doing all this!

> Reviewed 23 of 43 files at r1, 29 of 29 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/668#-:-MZxCAEP9VQhKdkUSaZi:b-6i0n8q)* status: all files reviewed, 1 unresolved discussion (waiting on @lesserwhirls)

___
*[docs/developer/src/site/_data/sidebars/developer_sidebar.yml, line 52 at r2](https://reviewable.io/reviews/unidata/netcdf-java/668#-MZxAmRL3zSVqcJXxCel:-MZxAmRL3zSVqcJXxCem:b-mr85aq) ([raw file](https://github.com/unidata/netcdf-java/blob/4eadf19998e4fbc2f9d173049a737eff88a33e0c/docs/developer/src/site/_data/sidebars/developer_sidebar.yml#L52)):*
> ```YAML
> 
>       subfolders:
>         - title: BURF Details
> ```

"BURF"   XD

**Review by lesserwhirls — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/668)* status: all files reviewed, 1 unresolved discussion (waiting on @haileyajohnson)

___
*[docs/developer/src/site/_data/sidebars/developer_sidebar.yml, line 52 at r2](https://reviewable.io/reviews/unidata/netcdf-java/668#-MZxAmRL3zSVqcJXxCel:-MZyVelJ5z9e9z72KWbM:b-ftj2vr) ([raw file](https://github.com/unidata/netcdf-java/blob/4eadf19998e4fbc2f9d173049a737eff88a33e0c/docs/developer/src/site/_data/sidebars/developer_sidebar.yml#L52)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

"BURF"   XD
</blockquote></details>

**Review by lesserwhirls — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/668)* status: 51 of 52 files reviewed, 1 unresolved discussion (waiting on @haileyajohnson)

___
*[docs/developer/src/site/_data/sidebars/developer_sidebar.yml, line 52 at r2](https://reviewable.io/reviews/unidata/netcdf-java/668#-MZxAmRL3zSVqcJXxCel:-MZyWpoxE7RDAu8vzA9U:b-vrn6k7) ([raw file](https://github.com/unidata/netcdf-java/blob/4eadf19998e4fbc2f9d173049a737eff88a33e0c/docs/developer/src/site/_data/sidebars/developer_sidebar.yml#L52)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>


</blockquote></details>

Ok, should be fixed now.

**Review by lesserwhirls — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/668)* status: 51 of 52 files reviewed, 1 unresolved discussion (waiting on @haileyajohnson)

___
*[docs/developer/src/site/_data/sidebars/developer_sidebar.yml, line 52 at r2](https://reviewable.io/reviews/unidata/netcdf-java/668#-MZxAmRL3zSVqcJXxCel:-MZyWuW29dB1tLYoVzzr:b-etw0r7) ([raw file](https://github.com/unidata/netcdf-java/blob/4eadf19998e4fbc2f9d173049a737eff88a33e0c/docs/developer/src/site/_data/sidebars/developer_sidebar.yml#L52)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

Ok, should be fixed now.
</blockquote></details>

Nice catch, btw!

**Review by haileyajohnson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/668)* status: 51 of 52 files reviewed, 1 unresolved discussion (waiting on @haileyajohnson and @lesserwhirls)

___
*[docs/developer/src/site/_data/sidebars/developer_sidebar.yml, line 52 at r2](https://reviewable.io/reviews/unidata/netcdf-java/668#-MZxAmRL3zSVqcJXxCel:-MZyhQtIDPfhmjavKr0J:bb7hf0f) ([raw file](https://github.com/unidata/netcdf-java/blob/4eadf19998e4fbc2f9d173049a737eff88a33e0c/docs/developer/src/site/_data/sidebars/developer_sidebar.yml#L52)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

Nice catch, btw!
</blockquote></details>

hehe

**Pull request merged**
