### PR TITLE
EarthLocation, Station are concrete, Immutable classes.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/362)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
travis failure - unrelated?

**Comment by lesserwhirls** [comment]
I ripped out the travis files, but there isn't a way that I've found to turn off the actual check. I don't have permissions on travis to see that part of the configs, i guess.  I need to check with @dopplershift about that.

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 45 of 45 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/362)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Thanks @JohnLCaron!

**Comment by lesserwhirls** [comment]
Would you mind doing a rebase? Once that's done, I'll merge it in.

**Comment by JohnLCaron** [comment]
ready

**Comment by dopplershift** [comment]
@lesserwhirls You still have a `.travis.yml`. Can you try putting in a PR that deletes that file and see if that stops it?

**Comment by lesserwhirls** [comment]
LoL - of course I do. I removed the travis/ directory, but I forgot the yml. Nothing like a fresh set of eyes to find what should have been step one. Thanks @dopplershift!

**Pull request merged**
