### PR TITLE
Handle case where HDF-EOS StructMetadata is stored as String

### PR DESCRIPTION
**Pull request by lesserwhirls**
Fixes Unidata/netcdf-java#455

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/457)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Not sure this is the correct way to fix things, but the end result appears to work (and no new failures on Jenkins).

**Comment by rschmunk** [comment]
Not working for me. I'm still getting an exception stack trace that passes through line 1939 of `H5headerNew`, just **before** the code that you altered.

**Comment by rschmunk** [comment]
Trying to dig into this, I find that when 1939 of `H5headerNew$Vinfo.readString` calls `IospHelper.readDataFill` for the example file of #455, it is passing in `TypeData.STRING` for the datatype, but there is no option in the if-then-else chain in `readDataFill` for that case.

Also, in looking at the commit history, it looks like this might go back to a bunch of PRs that @V-F made in January but which weren't actually committed to the repo until a month later?

**Comment by lesserwhirls** [comment]
I'll take a look again. I did the original work and testing with the sample file you provided, and only swapped that out with the smaller test file once things were working, but let me revisit it and see if I can trigger the stacktrace.

**Comment by rschmunk** [comment]
@lesserwhirls, My apologies, it looks like when I copied your changes into my local fork of netcdf-java, I left some lines of code out. Going back and looking at your changes again, I am now able to get the file to open.

**Comment by lesserwhirls** [comment]
Does the data look ok to you? From what I was able to see through toolsUI (comparing an older netCDF-java with the current), it looked ok, but that makes me feel a bit...uneasy...if that's the best I can do. If the data look ok on your end, I'll go ahead a get this merged in. If we run into issues later, I'll try to have a quick turn around for you.

**Comment by rschmunk** [comment]
The metadata appear fine.

I'm pondering the variables in the Data_Fields group as I'm not getting meaningful plots of the variable data. I'm trying to figure out if my code had an issue with the sinusoidal grid projection or if there's something else weird going on. I've also queried the person who provided the sample file(s).

**Review by haileyajohnson — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/457)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @haileyajohnson and @lesserwhirls)

___
*[cdm/core/src/test/java/ucar/nc2/iosp/hdf5/TestEosStructMetadata.java, line 21 at r1](https://reviewable.io/reviews/unidata/netcdf-java/457#-MGyZ6UGA-q7JY5UUmFg:-MGyZ6UGA-q7JY5UUmFh:b-xmzqx9) ([raw file](https://github.com/unidata/netcdf-java/blob/a88c45ee68f8619297c7d284b34c208ebbb35871/cdm/core/src/test/java/ucar/nc2/iosp/hdf5/TestEosStructMetadata.java#L21)):*
> ```Java
> 
>   @Test
>   public void testStrucMetadataEosString() throws IOException {
> ```

missing 't' in name (Struc)
___
*[cdm/core/src/test/java/ucar/nc2/iosp/hdf5/TestEosStructMetadata.java, line 21 at r1](https://reviewable.io/reviews/unidata/netcdf-java/457#-MGyZDay9VSskM3nZ6YJ:-MGyZDay9VSskM3nZ6YK:b-da3omb) ([raw file](https://github.com/unidata/netcdf-java/blob/a88c45ee68f8619297c7d284b34c208ebbb35871/cdm/core/src/test/java/ucar/nc2/iosp/hdf5/TestEosStructMetadata.java#L21)):*
> ```Java
> 
>   @Test
>   public void testStrucMetadataEosString() throws IOException {
> ```

To be on the same page since I'm writing similar tests: do we want tests to throw errors or catch them and fail the test (I don't know if it matters or if the end result even looks different)?

**Review by lesserwhirls — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/457)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @haileyajohnson)

___
*[cdm/core/src/test/java/ucar/nc2/iosp/hdf5/TestEosStructMetadata.java, line 21 at r1](https://reviewable.io/reviews/unidata/netcdf-java/457#-MGyZ6UGA-q7JY5UUmFg:-MGyr6F15E7vcp4WBMoO:b-2elmlr) ([raw file](https://github.com/unidata/netcdf-java/blob/a88c45ee68f8619297c7d284b34c208ebbb35871/cdm/core/src/test/java/ucar/nc2/iosp/hdf5/TestEosStructMetadata.java#L21)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

missing 't' in name (Struc)
</blockquote></details>

Good catch - will update with the 't'!
___
*[cdm/core/src/test/java/ucar/nc2/iosp/hdf5/TestEosStructMetadata.java, line 21 at r1](https://reviewable.io/reviews/unidata/netcdf-java/457#-MGyZDay9VSskM3nZ6YJ:-MGyr9I9ALzj9z0sbU3y:bofnhd2) ([raw file](https://github.com/unidata/netcdf-java/blob/a88c45ee68f8619297c7d284b34c208ebbb35871/cdm/core/src/test/java/ucar/nc2/iosp/hdf5/TestEosStructMetadata.java#L21)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

To be on the same page since I'm writing similar tests: do we want tests to throw errors or catch them and fail the test (I don't know if it matters or if the end result even looks different)?
</blockquote></details>

I am not sure what the best practice is when writing tests. My thought (currently) is that if I am writing a test, the code should not be expecting any exceptions (unless, of course, I'm actually testing that an exception is thrown). By having the test method throw an exception, I've sort of narrowed the focus of the written code on the thing I'm actually testing, and kept separate an "oh crap, what just happened" failure mode.

**Review by lesserwhirls — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/457)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @haileyajohnson)

___
*[cdm/core/src/test/java/ucar/nc2/iosp/hdf5/TestEosStructMetadata.java, line 21 at r1](https://reviewable.io/reviews/unidata/netcdf-java/457#-MGyZDay9VSskM3nZ6YJ:-MGysd7a1H02Bc3wXK-j:bouz2v9) ([raw file](https://github.com/unidata/netcdf-java/blob/a88c45ee68f8619297c7d284b34c208ebbb35871/cdm/core/src/test/java/ucar/nc2/iosp/hdf5/TestEosStructMetadata.java#L21)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

I am not sure what the best practice is when writing tests. My thought (currently) is that if I am writing a test, the code should not be expecting any exceptions (unless, of course, I'm actually testing that an exception is thrown). By having the test method throw an exception, I've sort of narrowed the focus of the written code on the thing I'm actually testing, and kept separate an "oh crap, what just happened" failure mode.
</blockquote></details>

Great question, BTW, and I'm open to other ideas!

**Review by haileyajohnson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/457)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @haileyajohnson and @lesserwhirls)

___
*[cdm/core/src/test/java/ucar/nc2/iosp/hdf5/TestEosStructMetadata.java, line 21 at r1](https://reviewable.io/reviews/unidata/netcdf-java/457#-MGyZDay9VSskM3nZ6YJ:-MGyxfz56ZrUTZS9JJtj:by9j385) ([raw file](https://github.com/unidata/netcdf-java/blob/a88c45ee68f8619297c7d284b34c208ebbb35871/cdm/core/src/test/java/ucar/nc2/iosp/hdf5/TestEosStructMetadata.java#L21)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

Great question, BTW, and I'm open to other ideas!
</blockquote></details>

The Java community appears to agree, so I'll run with that as well!

**Review by lesserwhirls — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/457)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @haileyajohnson)

___
*[cdm/core/src/test/java/ucar/nc2/iosp/hdf5/TestEosStructMetadata.java, line 21 at r1](https://reviewable.io/reviews/unidata/netcdf-java/457#-MGyZ6UGA-q7JY5UUmFg:-MGyyO4c-5Nygv9XTVeO:b-896fix) ([raw file](https://github.com/unidata/netcdf-java/blob/a88c45ee68f8619297c7d284b34c208ebbb35871/cdm/core/src/test/java/ucar/nc2/iosp/hdf5/TestEosStructMetadata.java#L21)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

Good catch - will update with the 't'!
</blockquote></details>

Done.
___
*[cdm/core/src/test/java/ucar/nc2/iosp/hdf5/TestEosStructMetadata.java, line 21 at r1](https://reviewable.io/reviews/unidata/netcdf-java/457#-MGyZDay9VSskM3nZ6YJ:-MGyyQNF2r4kt59MvEkq:betwb36) ([raw file](https://github.com/unidata/netcdf-java/blob/a88c45ee68f8619297c7d284b34c208ebbb35871/cdm/core/src/test/java/ucar/nc2/iosp/hdf5/TestEosStructMetadata.java#L21)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

The Java community appears to agree, so I'll run with that as well!
</blockquote></details>

Good to know - now I'll try to follow my own words :laughing:

**Pull request merged**
