### PR TITLE
Add GridAxisSpacing.nominalPoints, for horiz coords with both points and edges..

### PR DESCRIPTION
**Pull request by JohnLCaron**
(see TestGridCompareProblem.testNominalPointAxis)
Refactor some of the GridNetcdf classes to make them less awful.
Add comparision tests.
Fix Grib regular offset coords.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/746)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
Looking good! Thank you @johnlcaron!

> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/746#-:-MdcD9mL-7heQJ-1_WH1:be5wl44)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnLCaron)

**Comment by lesserwhirls** [comment]
Looks like this just needs a rebase?

**Comment by lesserwhirls** [comment]
That's got it - thanks @JohnLCaron!

**Pull request merged**
