### PR TITLE
nc2.grid.GridVariable must use short name.

### PR DESCRIPTION
**Pull request by JohnLCaron**
nc2.grid.GridVariable must use short name.
Improvements to CdmIndex ui.
Documentation and note tweaks.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/726)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
getting an error

 Error:  No such file or directory - /home/runner/work/netcdf-java/netcdf-java/docs/docs/userguide/src/test/java/examples/cdmdatasets/DatasetUrlExamples.java

**Comment by JohnLCaron** [comment]
Putting the fix to #725 in separate PR

**Comment by haileyajohnson** [comment]
There was an issue with the jekyll theme that should be fix by [this](https://github.com/Unidata/unidata-jekyll-theme/pull/18)

**Review by haileyajohnson — APPROVED** [review]
:lgtm:

> Reviewed 21 of 24 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/726#-:-MckjSiU-vtNxIkw2jed:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lesserwhirls)

**Pull request merged**
