### PR TITLE
Start of changes for version 6: legacy, Projection, Optional.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/358)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Failure down in `cdm/core/src/test/groovy/ucar/nc2/ft2/coverage/writer/CFGridCoverageWriter2Spec.groovy`

~~~
CFGridCoverageWriter2 properly adds 2D lat/lon variables
java.lang.NullPointerException
	at ucar.nc2.iosp.netcdf3.N3iosp.rewriteHeader(N3iosp.java:696)
	at ucar.nc2.NetcdfFileWriter.setRedefineMode(NetcdfFileWriter.java:930)
	at ucar.nc2.NetcdfFileWriter.close(NetcdfFileWriter.java:1139)
	at ucar.nc2.ft2.coverage.writer.CFGridCoverageWriter2Spec.CFGridCoverageWriter2 properly adds 2D lat/lon variables(CFGridCoverageWriter2Spec.groovy:128)
~~~

**Comment by lesserwhirls** [comment]
Well dang, that one works locally for me, but I'm getting failures elsewhere...still digging...

**Comment by JohnLCaron** [comment]
Im working on that failure now. Converting to CFGridCoverageWriter and seeing if it fails there. CFGridCoverageWriter2 is going away so it has to be done anyway.

**Comment by JohnLCaron** [comment]
It working locally with CFGridCoverageWriter . Sending a PR to see what happens.

**Comment by JohnLCaron** [comment]
Hmmm, I pushed a commit to JohnLCaron:

https://github.com/JohnLCaron/netcdf-java/tree/ver6merge

but its not showing up here after 6 minutes. Havent seen that before.... ???

**Comment by lesserwhirls** [comment]
Dang, I've not seen this one before. I visited your branch and selected the most recent commit, I got a 404:

https://github.com/Unidata/netcdf-java/commit/ff7e8bf4edfe76b9349de4dc9aa7b9fde04f2c05

When i tried again, it worked? Something weird happening on github.

**Comment by lesserwhirls** [comment]
I have an idea...one sec

**Comment by lesserwhirls** [comment]
So I switched the base branch of the PR and then switched it back to `develop`. Now I see the commit...let's see if the checks run

**Comment by lesserwhirls** [comment]
Wow, it's really confused. It looks like it's running now?

**Comment by lesserwhirls** [comment]
Ok, now we're good (or as good as 6 gets right now). The TDS checks will stop once I merge in my latest changes to 6.

**Comment by JohnLCaron** [comment]
Lets hope that was a github hiccup.
Should we turn TDS checks off?

**Comment by lesserwhirls** [comment]
I'm good with merging this in, but one quick question - I noticed that you had commented out `apply from: "$rootDir/gradle/root/fatJars.gradle"` in the main `build.gradle` file - I can snag that in my upcoming PR, but I wanted to check to see why you commented that one one to begin with just to make sure I'm not missing something?

**Comment by JohnLCaron** [comment]
I commented out fatJars because it uses legacy. I will start to leave out other "unported" modules (eg dap4, radial, mcidas) as I remove deprecated features. They will be added back in when they get ported. So disabling fatJars is the easiest temporary thing for now.

Im wondering what we want to do about fatJars for ver6 in the long term?

**Comment by lesserwhirls** [comment]
> I commented out fatJars because it uses legacy. I will start to leave out other "unported" modules (eg dap4, radial, mcidas) as I remove deprecated features. They will be added back in when they get ported.

That make sense.

> I'm wondering what we want to do about fatJars for ver6 in the long term?

That's a good question. Gradle 6 introduced a new plugin called `java-application`, which would allow us to keep producing `toolsUI` as an executable jar, but without relying on the shadow plugin to make a fatJar. But the others? TBD.

Merging - thanks @JohnLCaron!

**Pull request merged**
