### PR TITLE
Coord transforms

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/208)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Would you mind rebasing this one?

**Comment by JohnLCaron** [comment]
Not ready yet. Test failures appeared when I cleaned CompareNetcdf2 up. Stay tuned.

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
Looks good to me! Thanks @johnlcaron!

> Reviewed 46 of 47 files at r1, 2 of 12 files at r3, 13 of 18 files at r4, 14 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/208#-:-M0gy_yn9sw3O5TZt4UZ:brkafss)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
