### PR TITLE
Cleanup NetcdfFiles.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/424)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Comment by lesserwhirls** [comment]
Would you mind rebasing this one?

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/424)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by JohnLCaron** [comment]
ready

**Pull request merged**
