### PR TITLE
Ver6fixjenkins

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/369)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Im not positive this preserves the actual test, which is a bit obscure. Station is no longer an interface but a concrete class, so some of the previous casting is wrong.

**Comment by lesserwhirls** [comment]
This one just needs a rebase and it'll be good to go as well.

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 33 of 43 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/369)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Thanks @JohnLCaron!

**Pull request merged**
