### PR TITLE
Remove ft.point.writer

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/365)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
seems ready to go.

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/365)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Looks good. Would you mind rebasing? Also, would you mind adding one more commit to remove the travis.yml file at the base of the repo?

**Comment by JohnLCaron** [comment]
Sorry I should have made a seperate PR for travis. Not awake yet.

**Comment by lesserwhirls** [comment]
This is perfect - no need for a separate PR. This should take care of the travis check for future PRs. Thanks @JohnLCaron!

**Pull request merged**
