### PR TITLE
Fix add record

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/374)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Seems to be failing on a @Ignore test ??

**Comment by JohnLCaron** [comment]
Never mind - user error.

**Comment by JohnLCaron** [comment]
ready

**Comment by lesserwhirls** [comment]
I think this one just needs a rebase and we'll be good to go.

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 22 of 24 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/374)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Thanks @JohnLCaron!

**Pull request merged**
