### PR TITLE
Refactor Netcdf writing (pass 1)

### PR DESCRIPTION
**Pull request by JohnLCaron**
NetcdfFormatWriter only creates, doesnt update.
NetcdfFormatUpdater does the updating (not finished).
Remove IOServiceProviderWriter.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/479)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
How about this one next?

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 46 of 46 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/479)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lesserwhirls — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/479#-:-MHlwio48TW3OfithZEA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
