### PR TITLE
Move DateType, TimeCoverage, TimeDuration to thredds.client.catalog, …

### PR DESCRIPTION
**Pull request by JohnLCaron**
…refactor to make Immutable.

Deprecate current versions in ucar.nc2.units.
Deprecate mutable methods in TimeUnit.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/613)

### CODE REVIEW

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
> Reviewed 51 of 51 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/613)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnLCaron)

___
*[cdm/core/src/main/java/thredds/inventory/internal/package.html, line 6 at r1](https://reviewable.io/reviews/unidata/netcdf-java/613#-MUOD4-V1bZwaGEsVLxY:-MUOD4-V1bZwaGEsVLxZ:b-w8e76y) ([raw file](https://github.com/unidata/netcdf-java/blob/6efc2d0500dfaaa5204d55973587afe700b11a44/cdm/core/src/main/java/thredds/inventory/internal/package.html#L6)):*
> ```HTML
> </HEAD>
> <BODY>
> Multidimensional arrays stored in memory.
> ```

Looks like a copy/paste leftover snuck in here.
___
*[cdm/core/src/main/java/ucar/nc2/time/CalendarDateFormatter.java, line 180 at r1](https://reviewable.io/reviews/unidata/netcdf-java/613#-MUOGWq_6wUZNlP_XA2J:-MUOGTNg8yNRquskBsbh:b4ujevh) ([raw file](https://github.com/unidata/netcdf-java/blob/6efc2d0500dfaaa5204d55973587afe700b11a44/cdm/core/src/main/java/ucar/nc2/time/CalendarDateFormatter.java#L180)):*
> ```Java
>   }
> 
>   @VisibleForTesting
> ```

Do you think it would be useful for this annotation to be ignored when we produce the Javadocs?
___
*[uicdm/src/main/java/ucar/nc2/ui/widget/RangeDateSelector.java, line 98 at r1](https://reviewable.io/reviews/unidata/netcdf-java/613#-MUOIK5P6aetIQtKFWzS:-MUOIK5P6aetIQtKFWzT:b7deyx7) ([raw file](https://github.com/unidata/netcdf-java/blob/6efc2d0500dfaaa5204d55973587afe700b11a44/uicdm/src/main/java/ucar/nc2/ui/widget/RangeDateSelector.java#L98)):*
> ```Java
>    * @param help optional help text
>    * @param pointOnly if user can only select one point, otherwise can select a range of dates.
>    * @deprecated use ?
> ```

Is this deprecated because you want to find a better UI for doing this?

**Comment by JohnLCaron** [comment]
@VisibleForTesting

ideally anything annotated with this should not show up in public javadocs.

**Comment by JohnLCaron** [comment]
uicdm/src/main/java/ucar/nc2/ui/widget/RangeDateSelector.java, line 98

DateRange is deprecated and will go away in ver7, so I need to deprecate anyplace its in a public method.

RangeDateSelector needs to be rewritten, maybe discarded.

**Comment by lesserwhirls** [comment]
> @VisibleForTesting
> 
> ideally anything annotated with this should not show up in public javadocs.

Ok, cool. I think I can write an extension to the standard doclet to make sure those do not show up.

> uicdm/src/main/java/ucar/nc2/ui/widget/RangeDateSelector.java, line 98
> 
> DateRange is deprecated and will go away in ver7, so I need to deprecate anyplace its in a public method.
> 
> RangeDateSelector needs to be rewritten, maybe discarded.

Makes sense. I had added a dependency on [LGoodDatePicker](https://github.com/LGoodDatePicker/LGoodDatePicker) awhile back to make date/time selection a little cleaner in the TdsMonitor application. A widget could use it and be extended to include duration/resolution concepts, I think. Just one option.

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/613)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnLCaron)

___
*[cdm/core/src/main/java/thredds/inventory/internal/package.html, line 6 at r1](https://reviewable.io/reviews/unidata/netcdf-java/613#-MUOD4-V1bZwaGEsVLxY:-MUV7uEM85BWfRB8SKY-:b-wv8ray) ([raw file](https://github.com/unidata/netcdf-java/blob/6efc2d0500dfaaa5204d55973587afe700b11a44/cdm/core/src/main/java/thredds/inventory/internal/package.html#L6)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

Looks like a copy/paste leftover snuck in here.
</blockquote></details>

Do you want to grab this in the next PR?

**Review by lesserwhirls — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/613)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnLCaron)

___
*[cdm/core/src/main/java/thredds/inventory/internal/package.html, line 6 at r1](https://reviewable.io/reviews/unidata/netcdf-java/613#-MUOD4-V1bZwaGEsVLxY:-MUV8HVD6G9O5I40b-gY:byij7gv) ([raw file](https://github.com/unidata/netcdf-java/blob/6efc2d0500dfaaa5204d55973587afe700b11a44/cdm/core/src/main/java/thredds/inventory/internal/package.html#L6)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

Do you want to grab this in the next PR?
</blockquote></details>

Let's do that - I'll go ahead and merge this one.

**Pull request merged**
