### PR TITLE
Fix reading enums from netCDF-4 files

### PR DESCRIPTION
**Pull request by lesserwhirls**
Partial backport of Unidata/netcdf-java#479 (changes related to reading enums from netCDF-4 files). See Unidata/netcdf-java#352.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/496)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Ok, we're passing here and have no new failures on Jenkins. Whew!

**Review by haileyajohnson — COMMENTED** [review]
> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/496)* status: all files reviewed, 2 unresolved discussions (waiting on @lesserwhirls)

___
*[cdm/core/src/main/java/ucar/nc2/Group.java, line 927 at r1](https://reviewable.io/reviews/unidata/netcdf-java/496#-MIKd_zm45dLzxMfhG0B:-MIKd_zm45dLzxMfhG0C:b-t88v1v) ([raw file](https://github.com/unidata/netcdf-java/blob/34dfa90c9dba2882e95bc4f9069dea6849e622d2/cdm/core/src/main/java/ucar/nc2/Group.java#L927)):*
> ```Java
>     private AttributeContainerMutable attributes = new AttributeContainerMutable("");
>     private List<Dimension> dimensions = new ArrayList<>();
>     public List<EnumTypedef> enumTypedefs = new ArrayList<>();
> ```

I think I'm missing where this is used that it needs to be public...
___
*[cdm/core/src/main/java/ucar/nc2/iosp/netcdf3/N3iosp.java, line 1008 at r1](https://reviewable.io/reviews/unidata/netcdf-java/496#-MIKd7ke43IHXHAa4gNX:-MIKd7ke43IHXHAa4gNY:ba91hvp) ([raw file](https://github.com/unidata/netcdf-java/blob/34dfa90c9dba2882e95bc4f9069dea6849e622d2/cdm/core/src/main/java/ucar/nc2/iosp/netcdf3/N3iosp.java#L1008)):*
> ```Java
>   public String getFileTypeVersion() {
>     return "1";
>   }
> ```

can these strings be class constants?

**Review by lesserwhirls — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/496)* status: all files reviewed, 2 unresolved discussions (waiting on @haileyajohnson)

___
*[cdm/core/src/main/java/ucar/nc2/Group.java, line 927 at r1](https://reviewable.io/reviews/unidata/netcdf-java/496#-MIKd_zm45dLzxMfhG0B:-MILvCUE3V2b9_Ac3qLe:b-nfwwzq) ([raw file](https://github.com/unidata/netcdf-java/blob/34dfa90c9dba2882e95bc4f9069dea6849e622d2/cdm/core/src/main/java/ucar/nc2/Group.java#L927)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

I think I'm missing where this is used that it needs to be public...
</blockquote></details>

The access is down in `cdm/core/src/main/java/ucar/nc2/internal/iosp/hdf5/H5headerNew.java`, here:

https://github.com/Unidata/netcdf-java/pull/496/files#diff-552511b78a00abd0c3ead642c8491504R1573

There are cases where the enum name -> value map is attached to one object in the HDF5 file, but isn't named (even when there might be a named enum object with the same name -> value map). More info over at https://github.com/Unidata/netcdf-java/issues/352. In this case, we are streaming through the enums that have been added to the Group builder by name, and looking for any that have the same name -> value map. If we find one, we use it. rather than create a new one. If the group object was already built, we could use the `getEnumTypedefs()` method, but since we're still in the process of building the `NetcdfFile` object, we need to see what has been added to the builder up to this point.
___
*[cdm/core/src/main/java/ucar/nc2/iosp/netcdf3/N3iosp.java, line 1008 at r1](https://reviewable.io/reviews/unidata/netcdf-java/496#-MIKd7ke43IHXHAa4gNX:-MIM-1AAC9mGCt-01U3q:b1g8chq) ([raw file](https://github.com/unidata/netcdf-java/blob/34dfa90c9dba2882e95bc4f9069dea6849e622d2/cdm/core/src/main/java/ucar/nc2/iosp/netcdf3/N3iosp.java#L1008)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

can these strings be class constants?
</blockquote></details>

Yep, and we could even use `String.valueOf(NetcdfFileFormat.NETCDF3.version)` since it's already defined there! Let me fix those up real quick.

**Review by haileyajohnson — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/496)* status: all files reviewed, 2 unresolved discussions (waiting on @haileyajohnson)

**Pull request merged**
