### PR TITLE
Tds lite servlet with opendap 

### PR DESCRIPTION
**Pull request by JohnLCaron**
I forgot I had started a new branch. These are the (non-working) changes.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/463)

### CODE REVIEW

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
> Reviewed 11 of 37 files at r1, 727 of 727 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/463)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Before I merge this in, let's rename the `tds/` subproject (can just rename the directory), even if it's just a placeholder, otherwise we risk publishing a tds 6.0 snapshot artifact. Any placeholder would work for now (`cdm-lite`, maybe?).

**Comment by lesserwhirls** [comment]
Looks good - let me merge this in and take a crack at making the war / getting tests up-and-running.

**Comment by lesserwhirls** [comment]
If you're ready, that is.

**Comment by JohnLCaron** [comment]
I removed this from gretty.gradle farm task:

  // used by :dap4 test
  webapp 'edu.ucar:d4ts:5.0.0-SNAPSHOT@war', contextPath: '/d4ts'


Now I dont understand why it cant find this artifact now:

  webapp 'edu.ucar:dtswar:5.0.0-SNAPSHOT@war', contextPath: '/dts'
  integrationTestTask = 'test'

Execution failed for task ':httpservices:farmBeforeIntegrationTest'.
2020-09-01T23:07:10.2491519Z > Could not resolve all dependencies for configuration ':httpservices:farm'.
2020-09-01T23:07:10.2491994Z    > Could not find edu.ucar:dtswar:5.0.0-SNAPSHOT.
2020-09-01T23:07:10.2492276Z      Searched in the following locations:
2020-09-01T23:07:10.2492784Z        - https://jcenter.bintray.com/edu/ucar/dtswar/5.0.0-SNAPSHOT/maven-metadata.xml
2020-09-01T23:07:10.2493365Z        - https://jcenter.bintray.com/edu/ucar/dtswar/5.0.0-SNAPSHOT/dtswar-5.0.0-SNAPSHOT.pom
2020-09-01T23:07:10.2493943Z        - https://repo.maven.apache.org/maven2/edu/ucar/dtswar/5.0.0-SNAPSHOT/maven-metadata.xml
2020-09-01T23:07:10.2494523Z        - https://repo.maven.apache.org/maven2/edu/ucar/dtswar/5.0.0-SNAPSHOT/dtswar-5.0.0-SNAPSHOT.pom
2020-09-01T23:07:10.2495171Z        - https://artifacts.unidata.ucar.edu/repository/unidata-releases/edu/ucar/dtswar/5.0.0-SNAPSHOT/maven-metadata.xml
2020-09-01T23:07:10.2495819Z        - https://artifacts.unidata.ucar.edu/repository/unidata-releases/edu/ucar/dtswar/5.0.0-SNAPSHOT/dtswar-5.0.0-SNAPSHOT.pom
2020-09-01T23:07:10.2496449Z        - https://artifacts.unidata.ucar.edu/repository/unidata-snapshots/edu/ucar/dtswar/5.0.0-SNAPSHOT/maven-metadata.xml
2020-09-01T23:07:10.2497092Z        - https://artifacts.unidata.ucar.edu/repository/unidata-snapshots/edu/ucar/dtswar/5.0.0-SNAPSHOT/dtswar-5.0.0-SNAPSHOT.pom
2020-09-01T23:07:10.2497417Z      Required by:
2020-09-01T23:07:10.2497680Z          project :httpservices

**Comment by lesserwhirls** [comment]
Hmmm...I see the snapshots on the artifacts server. I wonder if it's an issue with gretty trying to run in farm mode with a single war (as opposed to multiple war files).

**Comment by lesserwhirls** [comment]
If you want, I can merge this in and take a look when I look at the cdm-lite war.

**Comment by JohnLCaron** [comment]
yes go ahead

**Pull request merged**
