### PR TITLE
Deprecate ma2

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/590)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/590)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnLCaron)

___
*[cdm/core/src/main/java/ucar/ma2/RangeScatter.java, line 10 at r1](https://reviewable.io/reviews/unidata/netcdf-java/590#-MO94A9j34ToOP6ILDkK:-MO94A9j34ToOP6ILDkL:b-n54pgr) ([raw file](https://github.com/unidata/netcdf-java/blob/44c788629d91c0b6f2cb6f431a5142a75fcdc8f9/cdm/core/src/main/java/ucar/ma2/RangeScatter.java#L10)):*
> ```Java
>  * A Range of indices describes by a list, rather than start:stop:stride.
>  * 
>  * @deprecated will move in ver7. TODO used?
> ```

I've wondered that myself...

**Comment by lesserwhirls** [comment]
Looks good - I can cleanly merge into `develop` via github, of if you want you can rebase. Either way works for me.

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/590#-:-MOGofL27_w5bkICp5GL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnLCaron)

**Review by lesserwhirls — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/590)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnLCaron)

**Pull request merged**
