### PR TITLE
IncludeCode plugin for netcdf-java docs

### PR DESCRIPTION
**Pull request by haileyajohnson**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/458)

### CODE REVIEW

**Review by haileyajohnson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/458)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @lesserwhirls)

___
*[cdm/core/src/test/java/examples/tutorials/NCTutorial.java, line 8 at r1](https://reviewable.io/reviews/unidata/netcdf-java/458#-MFldRyyC5C5h1K9pPdB:-MFldRyyC5C5h1K9pPdC:b-ei6md3) ([raw file](https://github.com/unidata/netcdf-java/blob/77c03a9de68bafcc6178efdb0423a1e96041cd21/cdm/core/src/test/java/examples/tutorials/NCTutorial.java#L8)):*
> ```Java
> 
> public class NCTutorial {
>     // logs error/info message in memory and can be accessed from test functions
> ```

Do we already have a way to mock logging in tests?
___
*[cdm/core/src/test/java/examples/tutorials/TestNCTutorial.java, line 36 at r1](https://reviewable.io/reviews/unidata/netcdf-java/458#-MFldeWd9qhsq-TMS5Sg:-MFldeWeD-NaghSzn5mb:b-b0y6tt) ([raw file](https://github.com/unidata/netcdf-java/blob/77c03a9de68bafcc6178efdb0423a1e96041cd21/cdm/core/src/test/java/examples/tutorials/TestNCTutorial.java#L36)):*
> ```Java
>      */
>     @Test
>     public void testCompileNCTutorial() {
> ```

So this will let us know any time the docs code snippet are deprecated (or throw any warning...), but it also might be Very Bad since it's compiling on the fly...

**Review by lesserwhirls — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/458)* status: all files reviewed, 3 unresolved discussions (waiting on @haileyajohnson)

___
*[cdm/core/src/test/java/examples/tutorials/NCTutorial.java, line 8 at r1](https://reviewable.io/reviews/unidata/netcdf-java/458#-MFldRyyC5C5h1K9pPdB:-MFpUEtA2A5PP_GfgBcP:b-sga66w) ([raw file](https://github.com/unidata/netcdf-java/blob/77c03a9de68bafcc6178efdb0423a1e96041cd21/cdm/core/src/test/java/examples/tutorials/NCTutorial.java#L8)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

Do we already have a way to mock logging in tests?
</blockquote></details>

I don't think we've done mock logging for testing. Might not be a bad idea though, and I think there are a few packages out there that will help us do that if you don't want to maintain our own (I'm guessing it can get a bit trick in some cases).
___
*[cdm/core/src/test/java/examples/tutorials/TestNCTutorial.java, line 36 at r1](https://reviewable.io/reviews/unidata/netcdf-java/458#-MFldeWd9qhsq-TMS5Sg:-MFpYFnq44zyU_hojZUd:b-9jpiy7) ([raw file](https://github.com/unidata/netcdf-java/blob/77c03a9de68bafcc6178efdb0423a1e96041cd21/cdm/core/src/test/java/examples/tutorials/TestNCTutorial.java#L36)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

So this will let us know any time the docs code snippet are deprecated (or throw any warning...), but it also might be Very Bad since it's compiling on the fly...
</blockquote></details>

We could go for a more simple approach here. We could move these tests to the `docs/` subproject, and setup a GitHub Action to specifically compile and run the tests. On the compile (e.g. `./gradlew :docs:compileTestJava`) we could look for deprecation warnings using something like a pipe to grep, and if found, fail the check. At that point, we could look at the output of the run to see what was throwing the deprecation warning.
___
*[docs/src/public/userguide/pages/netcdfJava/developer/DocGuide.md, line 353 at r2](https://reviewable.io/reviews/unidata/netcdf-java/458#-MFp_9aj23QMTvwQPQJm:-MFp_9ak2UPuJctWJ1JS:b-7ll2pr) ([raw file](https://github.com/unidata/netcdf-java/blob/96878a6e2725c96f2daa8216bea71023a9d4f7e3/docs/src/public/userguide/pages/netcdfJava/developer/DocGuide.md#L353)):*
> ```Markdown
> Note that the filters must be applied in this order.
> 
> ## Include code snippets contained elsewhere in the project
> ```

Super awesome +1 on updating the docs regarding how to use the new feature!!!

**Comment by haileyajohnson** [comment]
___
*[cdm/core/src/test/java/examples/tutorials/TestNCTutorial.java, line 36 at r1](https://reviewable.io/reviews/unidata/netcdf-java/458#-MFldeWd9qhsq-TMS5Sg:-MFptAwoDs2DhPUtNgxD:b4c9lyr) ([raw file](https://github.com/unidata/netcdf-java/blob/77c03a9de68bafcc6178efdb0423a1e96041cd21/cdm/core/src/test/java/examples/tutorials/TestNCTutorial.java#L36)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

We could go for a more simple approach here. We could move these tests to the `docs/` subproject, and setup a GitHub Action to specifically compile and run the tests. On the compile (e.g. `./gradlew :docs:compileTestJava`) we could look for deprecation warnings using something like a pipe to grep, and if found, fail the check. At that point, we could look at the output of the run to see what was throwing the deprecation warning.
</blockquote></details>

:thumbsup:

**Comment by haileyajohnson** [comment]
___
*[cdm/core/src/test/java/examples/tutorials/TestNCTutorial.java, line 36 at r1](https://reviewable.io/reviews/unidata/netcdf-java/458#-MFldeWd9qhsq-TMS5Sg:-MGL9EzpBT32p7dXk756:b-rxfyp3) ([raw file](https://github.com/unidata/netcdf-java/blob/77c03a9de68bafcc6178efdb0423a1e96041cd21/cdm/core/src/test/java/examples/tutorials/TestNCTutorial.java#L36)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

:thumbsup: 
</blockquote></details>

GitHub action is implemented now - catches "warning: [deprecation]" of any type on either stdout or stderr

**Review by lesserwhirls — COMMENTED** [review]
> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/458)* status: all files reviewed, 3 unresolved discussions (waiting on @haileyajohnson)

___
*[cdm/core/src/test/java/examples/tutorials/TestNCTutorial.java, line 36 at r1](https://reviewable.io/reviews/unidata/netcdf-java/458#-MFldeWd9qhsq-TMS5Sg:-MGNn1T34EpO2Drq01fN:b-7iaf29) ([raw file](https://github.com/unidata/netcdf-java/blob/77c03a9de68bafcc6178efdb0423a1e96041cd21/cdm/core/src/test/java/examples/tutorials/TestNCTutorial.java#L36)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

GitHub action is implemented now - catches "warning: [deprecation]" of any type on either stdout or stderr
</blockquote></details>

w00t!

**Review by lesserwhirls — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/458#-:-MGNnqeX7LMgryVFY6p8:bb6ywmx)* status: all files reviewed, 2 unresolved discussions (waiting on @haileyajohnson)

___
*[cdm/core/src/test/java/examples/tutorials/TestNCTutorial.java, line 36 at r1](https://reviewable.io/reviews/unidata/netcdf-java/458#-MFldeWd9qhsq-TMS5Sg:-MGNnngQ8e6370pabtit:bb6un1j) ([raw file](https://github.com/unidata/netcdf-java/blob/77c03a9de68bafcc6178efdb0423a1e96041cd21/cdm/core/src/test/java/examples/tutorials/TestNCTutorial.java#L36)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

w00t!
</blockquote></details>

Done
___
*[docs/src/public/userguide/pages/netcdfJava/developer/DocGuide.md, line 353 at r2](https://reviewable.io/reviews/unidata/netcdf-java/458#-MFp_9aj23QMTvwQPQJm:-MGNnjU68EWItQMwJGXo:bb6un1j) ([raw file](https://github.com/unidata/netcdf-java/blob/96878a6e2725c96f2daa8216bea71023a9d4f7e3/docs/src/public/userguide/pages/netcdfJava/developer/DocGuide.md#L353)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

Super awesome +1 on updating the docs regarding how to use the new feature!!!
</blockquote></details>

Done
___
*[cdm/core/src/test/java/examples/tutorials/NCTutorial.java, line 8 at r1](https://reviewable.io/reviews/unidata/netcdf-java/458#-MFldRyyC5C5h1K9pPdB:-MGNnao0C131Yo8E-I91:bb6un1j) ([raw file](https://github.com/unidata/netcdf-java/blob/77c03a9de68bafcc6178efdb0423a1e96041cd21/cdm/core/src/test/java/examples/tutorials/NCTutorial.java#L8)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

I don't think we've done mock logging for testing. Might not be a bad idea though, and I think there are a few packages out there that will help us do that if you don't want to maintain our own (I'm guessing it can get a bit trick in some cases).
</blockquote></details>

Done

**Review by lesserwhirls — APPROVED** [review]
> Dismissed @haileyajohnson from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/458)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Not sure why Reviewable isn't showing green here, but it is over there. This is ready go in from POV, but wanted to check with you first to make sure you're ready. Additional tests can be added in another PR :-)

**Comment by haileyajohnson** [comment]
Works for me!

**Pull request merged**
