### PR TITLE
Remove NetcdFileSubset, make NetcdfFile (almost) Immutable.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/409)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 42 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/409)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
This one has Unidata#407, Unidata#408, so reviewed this one instead of those individually. I noticed there were still a few `"public by accident, do not call directly."` comments, javadocs (e.g. `reallyRead` in `ucar.nc2.Variable`) - are those something we can deprecate in 6 and remove in 7?

**Comment by JohnLCaron** [comment]
Re: "public by accident, do not call directly"
I will review those, but my first guess is they still need to be visible unfortunately, because they implement an interface....

**Pull request merged**
