### PR TITLE
Cdm visad module

### PR DESCRIPTION
**Pull request by JohnLCaron**

### CODE REVIEW

**Comment by lesserwhirls** [comment]
So looks like this one includes Unidata/netcdf-java#116. If so, let's close 116 and get this one fixed up.

**Comment by JohnLCaron** [comment]
ok im working on this one now

**Comment by lesserwhirls** [comment]
Sounds good. Quick question though, before we go further. As of now, the new module names and artifacts look like `core.jar`, `image.jar`, and `radial.jar`. This will add a `misc.jar` and `mcidas.jar` artifacts. So, to use them in maven, it would look like:

~~~xml
<dependency>
  <groupId>edu.ucar</groupId>
  <artifactId>core</artifactId>
  <version>${netcdfJavaVersion}</version>
  <scope>compile</scope>
</dependency>

<dependency>
  <groupId>edu.ucar</groupId>
  <artifactId>image</artifactId>
  <version>${netcdfJavaVersion}</version>
  <scope>compile</scope>
</dependency>
~~~

or in gradle:

~~~groovy
dependencies {
  compile "edu.ucar:core:${netcdfJavaVersion}"
  compile "edu.ucar:image:${netcdfJavaVersion}"
}
~~~

Do we want to prepend a `cdm-` to some (all?) of those names, like `cdm-core`, `cdm-image`, `cdm-radial`, and `cdm-misc`, `cdm-mcidas`?

If so, I can do this after we get this merged in.

**Comment by JohnLCaron** [comment]
yes i agree we should rename with cdm- prefix.
let me finish these PRs (I hope) before you do that.

**Comment by lesserwhirls** [comment]
I'll hold off. I have already made the changes in a local branch (for cdm-core, cdm-image, and cdm-radial), but nothing is in a PR or merged yet.

**Comment by JohnLCaron** [comment]
ready to go

**Pull request merged**
