### PR TITLE
fix v6 deprecation labels and public api for Variable.builder

### PR DESCRIPTION
**Pull request by haileyajohnson**
Address discussion in #585

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/623)

### CODE REVIEW

**Comment by haileyajohnson** [comment]
@JohnLCaron does this cover what you had in mind? 
1) Added the method signature that v.5 deprecates in favor of to v.6 (see [here](https://github.com/Unidata/netcdf-java/blob/maint-5.x/cdm/core/src/main/java/ucar/nc2/Variable.java#L2173))
2) Added deprecation to that method in v.6
3) Deprecated setSourceData(ucar.ma2.Array) in v.6 in favor of setSourceData(ucar.array.Array<?>)

**Comment by JohnLCaron** [comment]
Yes, LGTM. I guess you need another PR for ver5?

**Comment by haileyajohnson** [comment]
I don't think v5 needs to change, it already has "Variable.setCachedData(Array cacheData) is deprecated in favor of Variable.Builder.setCachedData(ucar.ma2.Array cacheData)" Unless I'm missing something?

**Comment by lesserwhirls** [comment]
I think v5 is missing an additional "In version 6 it will be changed to Variable.Builder.setSourceData(ucar.array.Array<?> cacheData)"

**Comment by haileyajohnson** [comment]
It feels off to me, and potentially confusing, to warn users that the API will be changing to something that doesn't exists yet in v5 and won't be required until v7, but I'm open to changing my mind on that.

**Comment by JohnLCaron** [comment]
i agree with hailey, i think were good.

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/623)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnLCaron)

**Comment by lesserwhirls** [comment]
Thanks @haileyajohnson!

**Pull request merged**
