### PR TITLE
NUWG and GDV Conventions

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/201)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Looks like we have a logjam induced conflict on this one now. Sorry about that.

**Comment by JohnLCaron** [comment]
ready

**Comment by JohnLCaron** [comment]
Lets get this one in, will need to sync to Conventions5.

**Comment by lesserwhirls** [comment]
Thank you @JohnLCaron!

**Pull request merged**
