### PR TITLE
Move cdm-image tests out of cdm-test.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/345)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Here are the failures for `cdmTestBreakupImage`:

~~~
ucar.nc2.TestReadFormats.testAllFormat
ucar.nc2.TestReadStrides.testReadStridesAll
ucar.nc2.dt.grid.TestGridSubset.testAggByteGiniSubsetStride
ucar.nc2.dt.grid.TestGridSubset.testGiniSubsetStride
ucar.nc2.ncml.TestNcmlWriteAndCompareShared.compareNcML[/share/testdata/cdmUnitTest/thredds-test-data/local/thredds-test-data/cdmUnitTest/formats/gini/n0r_20041013_1852-compress]
ucar.nc2.ncml.TestNcmlWriteAndCompareShared.compareNcML[/share/testdata/cdmUnitTest/thredds-test-data/local/thredds-test-data/cdmUnitTest/formats/gini/ntp_20041206_2154]
ucar.nc2.ncml.TestOffAggDirDateFormat.classMethod
ucar.nc2.write.TestNetcdfCopier.doOne[/share/testdata/cdmUnitTest/thredds-test-data/local/thredds-test-data/cdmUnitTest/formats/gini/SUPER-NATIONAL_8km_WV_20051128_2200.gini]
~~~

https://jenkins-aws.unidata.ucar.edu/view/John/job/john-caron-netcdf-java/10/testReport/

**Comment by JohnLCaron** [comment]
ready for jenkins redo

**Comment by lesserwhirls** [comment]
Running at https://jenkins-aws.unidata.ucar.edu/job/john-caron-netcdf-java/11/

**Comment by JohnLCaron** [comment]
I believe I got them all now. Can run jenkins, or just accept and let it run in tonight's jenkins run.

**Comment by lesserwhirls** [comment]
I think we'll go with that.

**Pull request merged**
