### PR TITLE
Conventions

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/194)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Ready for review.
This fixes problems in existing code for CoordSysBuilders, and ports more CoordSysBuilders to the new builder framework.
Still have some bugs in cdm-test Im working on.

**Comment by JohnLCaron** [comment]
This should fix errors in cdm-test. 

Also the file

   conventions/cf/SUPER-NATIONAL_latlon_IR_20070222_1600.nc 

should be moved to conventions/problems, since it is not cf and it now disagrees with old code. I think the new code is probably correct.

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
> Reviewed 29 of 34 files at r1, 13 of 13 files at r2, 4 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/194)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnLCaron)

___
*[cdm/core/src/main/java/ucar/nc2/dataset/CoordinateTransform.java, line 230 at r2](https://reviewable.io/reviews/unidata/netcdf-java/194#-LzyNPaSDmvfwSUqBq3X:-LzyNPaT-urTDyHr00ZL:bj1giti) ([raw file](https://github.com/unidata/netcdf-java/blob/e7a64056d6d3dcff186d3706ee232ff4317b2549/cdm/core/src/main/java/ucar/nc2/dataset/CoordinateTransform.java#L230)):*
> ```Java
> 
>     public CoordinateTransform build(NetcdfDataset ncd) {
>       System.out.printf("Building transform %s%n", name);
> ```

Can we log this instead?
___
*[cdm/core/src/main/java/ucar/nc2/dataset/transform/CsmSigma.java, line 1 at r2](https://reviewable.io/reviews/unidata/netcdf-java/194#-LzyOtP51aNW3stpsd4j:-LzyOtP51aNW3stpsd4k:b-q9jczv) ([raw file](https://github.com/unidata/netcdf-java/blob/e7a64056d6d3dcff186d3706ee232ff4317b2549/cdm/core/src/main/java/ucar/nc2/dataset/transform/CsmSigma.java#L1)):*
> ```Java
> /* Copyright Unidata */
> ```

Minor: we've been using something like this:

/*
 * Copyright (c) 1998-2020 John Caron and University Corporation for Atmospheric Research/Unidata
 * See LICENSE for license information.
 */
___
*[cdm/core/src/main/java/ucar/nc2/internal/dataset/conv/ADASConvention.java, line 261 at r2](https://reviewable.io/reviews/unidata/netcdf-java/194#-LzyTDYf0t8dp2G36y3M:-LzyTDYf0t8dp2G36y3N:b-8qq2lu) ([raw file](https://github.com/unidata/netcdf-java/blob/e7a64056d6d3dcff186d3706ee232ff4317b2549/cdm/core/src/main/java/ucar/nc2/internal/dataset/conv/ADASConvention.java#L261)):*
> ```Java
>   }
> 
>   /*
> ```

Do you know what's up with all of this commented code? Can we nuke it?
___
*[cdm/core/src/test/java/ucar/nc2/dataset/TestCoordSysCompareProblem.java, line 1 at r4](https://reviewable.io/reviews/unidata/netcdf-java/194#-LzyVXSt-TgojQc5YzUK:-LzyVXSu2GLoTAgj4_Tf:b-17124o) ([raw file](https://github.com/unidata/netcdf-java/blob/4ede58f8e377a0d4617791ed5418dad17499f8ae/cdm/core/src/test/java/ucar/nc2/dataset/TestCoordSysCompareProblem.java#L1)):*
> ```Java
> /* Copyright Unidata */
> ```

Same comment re: copyright
___
*[cdm/core/src/test/java/ucar/nc2/dataset/conv/SearchForConventions.java, line 1 at r2](https://reviewable.io/reviews/unidata/netcdf-java/194#-LzyUvtz61GHM2q78_uf:-LzyUvtz61GHM2q78_ug:b-h28d7m) ([raw file](https://github.com/unidata/netcdf-java/blob/e7a64056d6d3dcff186d3706ee232ff4317b2549/cdm/core/src/test/java/ucar/nc2/dataset/conv/SearchForConventions.java#L1)):*
> ```Java
> /* Copyright Unidata */
> ```

Same comment about copyright

**Comment by lesserwhirls** [comment]
> Also the file
> 
> conventions/cf/SUPER-NATIONAL_latlon_IR_20070222_1600.nc
> 
> should be moved to conventions/problems, since it is not cf and it now disagrees with old code. I think the new code is probably correct.

I believe the rec center is blocking port 22, so I can't do that just yet, but I will soon. Have you been able to use the https://github.com/Unidata/thredds-test-data stuff?

**Comment by JohnLCaron** [comment]
Done. 
Have not used thredds-test-data.

**Review by lesserwhirls — APPROVED** [review]

**Comment by lesserwhirls** [comment]
Sounds good. The thredds-test-data repo helps with managing the test data locally using rsync, which is nice. It makes for easy resetting after running the tests. I have the change to the test data updated on aws (so Jenkins will see it), and will update it on our rsync server shortly. I plan on updating the jenkins workers to run the rsync stuff before the test to make sure we always have the latest and greatest there.

**Comment by lesserwhirls** [comment]
thredds-test-data updated now.

**Pull request merged**
