### PR TITLE
ZarrIosp: Watch for floating point fill values encoded as Strings

### PR DESCRIPTION
**Pull request by rschmunk**
## Description of Changes

If a Zarr variable's fill value attribute had a String value ("NaN", "Infinity", or "-Infinity") or was reported as null, a ClassCastException would occur when IospHelper tried to cast the String to a Number.

Edited ZarrIosp to watch for such fill values in several cases and convert them to the appropriate datatype and value.

## PR Checklist

- [ ] Link to any issues that the PR addresses
- [ ] Add labels
- [ ] Open as a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/)
       until ready for review
- [ ] Make sure GitHub tests pass
- [ ] Mark PR as "Ready for Review"

### CODE REVIEW

**Comment by haileyajohnson** [comment]
Thanks, @rschmunk ! This was actually a recent issue for a bunch of Zarr implementations, thanks for fixing it. I think the failing tests here are just a fluke, but I'm going to add a test case for this scenario to your PR before merging, if you don't mind.

**Comment by rschmunk** [comment]
@haileyajohnson, Thought I responded to your comment earlier, but maybe I closed the browser window before hitting save.

As you can see from the list of 4 commits to this pull request above, it passed all tests after the third commit. In the fourth commit, I changed one word on a logging message. So that it didn't pass all tests after that is indeed fluky.

**Review by haileyajohnson — APPROVED** [review]

**Comment by haileyajohnson** [comment]
Looks good to me, added a test and moved some test data around, feel free to merge if you're good with it!

**Comment by rschmunk** [comment]
@haileyajohnson, Who is the comment about merging addressed to?

**Pull request merged**
