### PR TITLE
Upgrade gradle to 6.8.2.

### PR DESCRIPTION
**Pull request by JohnLCaron**
Bump version number to 6.1.0.
Move dependencies out of uibase to uicdm (pass 1).
Reword module descriptions.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/603)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Getting failure in S3:

```
2021-02-19T17:25:48.4520425Z thredds.inventory.s3.TestMFileS3 > bucketAndKeyOsdc FAILED
2021-02-19T17:25:48.4521417Z     expected: 1603308465000
2021-02-19T17:25:48.4521997Z     but was : 1611593614000
2021-02-19T17:25:48.4523973Z         at thredds.inventory.s3.TestMFileS3.checkWithBucketAndKey(TestMFileS3.java:197)
2021-02-19T17:25:48.4526250Z         at thredds.inventory.s3.TestMFileS3.bucketAndKeyOsdc(TestMFileS3.java:109)
```

**Comment by lesserwhirls** [comment]
Ah, yes. that's hitting the Open Science Data Cloud, which is hosted on whatever kind of ObjectStore that Open Stack provides (I think). At any rate, I fixed that on the `maint-5.x` branch recently:

https://github.com/Unidata/netcdf-java/pull/601/files#diff-a08431f99d6201b26e98c13f525c5bd5a78780fa2085aa57c3a9a49df8cf0b1a

It's pretty minor (looks like maybe they moved the data to a different bucket, and the last modified time was changed). I have not had a chance to port that change to 6, so if you want to add that change to this PR, that works.

Thanks @JohnLCaron!

**Comment by lesserwhirls** [comment]
One other comment, since we have not released `6.0.0` yet, we don't need to bump to `6.1.0`.

**Comment by JohnLCaron** [comment]
? that number keeps jumping around ??

**Comment by lesserwhirls** [comment]
I didn't expect the last modified to change since each check is for a single region (AWS), or the object store does not have a region (like the Open Science Data Cloud). No idea what is going on there, as these are archive data and should not be modified without some kind of announcement. At any rate, let's `@Ignore` the  `bucketAndKey*` tests for now, and I will fix them to look for a better response property.

**Review by lesserwhirls — APPROVED** [review]
Looks good! Thanks @johnlcaron!

> Reviewed 14 of 15 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/603#-:-MTwsehn3KSp5J3ny5Pk:bv8pxcp)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnLCaron)

**Pull request merged**
