### PR TITLE
Duplicate ucar.ma2.Range, Section, InvalidRangeException to ucar.array.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/633)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
I think a quick merge will do the trick on this one now that I've merged in Hailey's ports.

**Comment by JohnLCaron** [comment]
Sorry this got so big - got away from me some.

**Comment by lesserwhirls** [comment]
> Sorry this got so big - got away from me some.

It's all good - taking a look now.

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
Really like those new tests! It's satisfying to read though those and know that they are tested at that basic level going forward. Just a few comments/questions.

> Reviewed 67 of 68 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/633#-:-MWQ8Ln77wOCeR2siA4r:bj1qk0p)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnLCaron)

___
*[cdm/core/src/main/java/ucar/array/Arrays.java, line 9 at r2](https://reviewable.io/reviews/unidata/netcdf-java/633#-MWQ-URT9p9c2mw3o2RY:-MWQ-URT9p9c2mw3o2RZ:bpucj3j) ([raw file](https://github.com/unidata/netcdf-java/blob/d4c23185f3fc8325fd25681f35af1f9e60a55f88/cdm/core/src/main/java/ucar/array/Arrays.java#L9)):*
> ```Java
> import com.google.common.base.Preconditions;
> import ucar.ma2.DataType;
> import ucar.ma2.IndexIterator;
> ```

I don't think this import is needed, right?
___
*[cdm/core/src/main/java/ucar/array/IsMissingEvaluator.java, line 2 at r2](https://reviewable.io/reviews/unidata/netcdf-java/633#-MWQ-tWj88H35mC7JJ_G:-MWQ-tWj88H35mC7JJ_H:bv94c15) ([raw file](https://github.com/unidata/netcdf-java/blob/d4c23185f3fc8325fd25681f35af1f9e60a55f88/cdm/core/src/main/java/ucar/array/IsMissingEvaluator.java#L2)):*
> ```Java
> /*
>  * Copyright (c) 1998-2021 University Corporation for Atmospheric Research/Unidata
> ```

Don't forget your name (same with other copyright blocks in this PR). Also, there are a few new files that are missing this block all together.
___
*[cdm/core/src/main/java/ucar/ma2/Range.java, line 30 at r2](https://reviewable.io/reviews/unidata/netcdf-java/633#-MWQ2Q7sBRyLBE4ZF7ec:-MWQ2Q7sBRyLBE4ZF7ed:b-rk86yx) ([raw file](https://github.com/unidata/netcdf-java/blob/ab5a9c8d0187197fc2ba5822a4f59c4baf307e73/cdm/core/src/main/java/ucar/ma2/Range.java#L30)):*
> ```Java
>  * </pre>
>  * 
>  * @deprecated will move to ucar.array in ver7.
> ```

Will ucar.ma2 stay around in version 7?

**Comment by JohnLCaron** [comment]
Im currently thinking we will keep ma2 in ver7, and remove in 8.

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 26 of 26 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/633)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnLCaron)

**Review by lesserwhirls — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/633)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnLCaron)

**Comment by lesserwhirls** [comment]
Cool - thanks @JohnLCaron!

**Pull request merged**
