### PR TITLE
CdmrRemote gRPC service.

### PR DESCRIPTION
**Pull request by JohnLCaron**
Handle Structures, VLEN, large data requests.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/468)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/468)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Thanks @JohnLCaron! It looks like some of this might be useful to backport to 5 (changes in CDM core). I can do that if you think those changes in isolation would be useful.

**Comment by JohnLCaron** [comment]
Sure, backport if you want.

**Comment by lesserwhirls** [comment]
Thanks @JohnLCaron!

**Pull request merged**
