### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by JohnLCaron**
Some tests depending on addRecordStructure, not ready in N3iospNew.
Convention assignment must check name before isMine().
Bug in GribIospBuiler; wasnt adding nested groups.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/243)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Hopefully, all unit tests failures will resolve, once this PR and issue #242 is in.

**Comment by JohnLCaron** [comment]
2020-04-04T20:29:27.4473855Z E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/h/hdf5/hdf5-helpers_1.10.0-patch1+docs-4_amd64.deb  Could not connect to azure.archive.ubuntu.com:80 (52.177.174.250), connection timed out

**Comment by JohnLCaron** [comment]
Dont see an option to "try again"

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/243)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnLCaron)

___
*[grib/src/test/data/berkes.grib2, line 0 at r1](https://reviewable.io/reviews/unidata/netcdf-java/243#-M4HRBRL56nbo7TCAes0:-M4HRBRL56nbo7TCAes1:b-b3i1bc) ([raw file](https://github.com/unidata/netcdf-java/blob/759ddf1d1c239a15418cfe41e675c4cff06e4665/grib/src/test/data/berkes.grib2#L0)):*
Out of curiosity, where did this one come from?

**Comment by lesserwhirls** [comment]
> Dont see an option to "try again"

*sigh* I'm going to try to get the underlying issue fixed tomorrow. Sorry it's taken so long.

**Pull request merged**
