### PR TITLE
Add Builder for StructureMembers.

### PR DESCRIPTION
**Pull request by JohnLCaron**
remove usages of deprecated methods.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/298)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Travis failure:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'thredds-data-server'.
> Could not resolve all files for configuration ':classpath'.
   > Could not download spring-boot-devtools.jar (org.springframework.boot:spring-boot-devtools:1.3.3.RELEASE)
      > Could not get resource 'https://jcenter.bintray.com/org/springframework/boot/spring-boot-devtools/1.3.3.RELEASE/spring-boot-devtools-1.3.3.RELEASE.jar'.
         > Could not HEAD 'https://jcenter.bintray.com/org/springframework/boot/spring-boot-devtools/1.3.3.RELEASE/spring-boot-devtools-1.3.3.RELEASE.jar'. Received status code 504 from server: Gateway Time-out

**Comment by JohnLCaron** [comment]
Otherwise, I think its ready.

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 30 of 32 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/298)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Thanks @JohnLCaron - I'm getting close to removing the TravisCI stuff and going with GitHub Actions. Just a few more ansible tricks to learn.

**Pull request merged**
