### PR TITLE
Move cdm-radial tests out of cdm-test.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/347)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready for jenkins retest

**Comment by lesserwhirls** [comment]
Running at https://jenkins-aws.unidata.ucar.edu/view/Sean/job/sean-netcdf-java/59/

**Comment by JohnLCaron** [comment]
ready

**Comment by lesserwhirls** [comment]
Sorry for the delay - this one just needs a rebase.

**Comment by JohnLCaron** [comment]
rebased other branch

**Comment by lesserwhirls** [comment]
Closed by Unidata/netcdf-java#348 - thanks @JohnLCaron!

**Pull request closed without merging**
