### PR TITLE
Cdm test breakup visad

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/348)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready for jenkins

**Comment by lesserwhirls** [comment]
This one ran with one failure (https://jenkins-aws.unidata.ucar.edu/view/github%20runners/job/github-netcdf-java/), but now needs a rebase now. I should have pulled this one in instead of Unidata/netcdf-java#345 - my bad.

**Comment by JohnLCaron** [comment]
Im just going to rebase this one, since it includes radial.

**Comment by JohnLCaron** [comment]
You can rerun jenkins or accept and we'll catch any more failures in regular jenkins.
Except or course, spotlessAnnoy.

**Comment by lesserwhirls** [comment]
Sounds good to me. I'll merge this in and spin up a jenkins run just to see. Thanks @JohnLCaron!

**Pull request merged**
