### PR TITLE
Calendar time refactor.

### PR DESCRIPTION
**Pull request by JohnLCaron**
Use java.time instead of joda-time.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/688)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Work in progress, but cant seem to mark it as such.

**Comment by lesserwhirls** [comment]
Looks like there are a few time related failures on Jenkins. Want to knock those out here, or go ahead and get these changes into `develop` and take care of it in a different PR?

**Comment by JohnLCaron** [comment]
Ill catch them in the next PR.

**Review by lesserwhirls — APPROVED** [review]
Just a few comments, but no showstoppers. Can get this in now and address things as we move forward.

> Reviewed 291 of 291 files at r1, 16 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/688#-:-MbOAfFc4jv02WiI2tY1:bwmnh84)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnLCaron)

___
*[cdm-core/src/main/java/ucar/nc2/calendar/CalendarDateFormatter.java, line 85 at r1](https://reviewable.io/reviews/unidata/netcdf-java/688#-MbNaeizCk3lOVFcJ4do:-MbNaej-EcJKi17fOKYI:bgwvj53) ([raw file](https://github.com/unidata/netcdf-java/blob/179ed4ccc2b4d01e5925f285517ba7092cc04e1f/cdm-core/src/main/java/ucar/nc2/calendar/CalendarDateFormatter.java#L85)):*
> ```Java
>   /**
>    * Date formatter with specified pattern.
>    * NOTE: we are using jodatime patterns right now, but may switch to jsr-310 when thats available in java 8.
> ```

Since we are using DateTimeFormatter, should this table be updated to follow https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/format/DateTimeFormatter.html?
___
*[cdm-core/src/main/java/ucar/nc2/calendar/chrono/AbstractDate.java, line 392 at r1](https://reviewable.io/reviews/unidata/netcdf-java/688#-MbNdyVv9JHTwVHkW4rD:-MbNdyVv9JHTwVHkW4rE:b-uiob3j) ([raw file](https://github.com/unidata/netcdf-java/blob/179ed4ccc2b4d01e5925f285517ba7092cc04e1f/cdm-core/src/main/java/ucar/nc2/calendar/chrono/AbstractDate.java#L392)):*
> ```Java
>   public int hashCode() {
>     return getChronology().getId().hashCode()
>         ^ ((getProlepticYear() & 0xFFFFF800) ^ ((getProlepticYear() << 11) + (getMonth() << 6) + (getDayOfMonth())));
> ```

Any reason to use this instead of `java.util.Objects.hash(Object... values)`?
___
*[grib/src/main/java/ucar/nc2/grib/grib2/table/NwsMetDevTables.java, line 80 at r1](https://reviewable.io/reviews/unidata/netcdf-java/688#-MbO5ymYDocHQAC-LFNz:-MbO5ymYDocHQAC-LFO-:bckh8ui) ([raw file](https://github.com/unidata/netcdf-java/blob/179ed4ccc2b4d01e5925f285517ba7092cc04e1f/grib/src/main/java/ucar/nc2/grib/grib2/table/NwsMetDevTables.java#L80)):*
> ```Java
>       return super.getForecastTimeIntervalSizeInHours(pds);
>     }
>     // LOOK barf
> ```

:vomiting_face:

**Comment by lesserwhirls** [comment]
Whoops, looks like you added a commit as I was reviewing and now some github tests are failing.

**Comment by JohnLCaron** [comment]
Looks like netCDF-Java Tests (14, temurin) doesnt have TestDir.cdmUnitTestDir, and there were 2 tests that forgot to use @Category(NeedsCdmUnitTest.class).

Im going to leave the hashCode in AbstractDate; its a copy from threeten-extra, and I would have to look closer. Probably your right, though.

jenkins-aws is donw do I cant check how many tests are still failing - but i fixed some of them.

Sorry to interfere with your review.

**Comment by lesserwhirls** [comment]
> Looks like netCDF-Java Tests (14, temurin) doesnt have TestDir.cdmUnitTestDir, and there were 2 tests that forgot to use @category(NeedsCdmUnitTest.class).

Yeah, the github tests don't have access to the big test datasets like Jenkins. It was probably the missing `@category(NeedsCdmUnitTest.class)` that was causing the main failure.

> 
> Im going to leave the hashCode in AbstractDate; its a copy from threeten-extra, and I would have to look closer. Probably your right, though.

That's right - I forgot some of these classes were based on threeten-extra classes, so best to leave as is.

> jenkins-aws is donw do I cant check how many tests are still failing - but i fixed some of them.

Not sure what happened to Jenkins. I had to bounce the ec2 instance and do some updates, but it looks to be back now.  I just started a run on your copy of the project.

> Sorry to interfere with your review.

No worries there! It's easy enough to isolate the new additions in Reviewable, so not a big deal 👍

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/688)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnLCaron)

**Review by lesserwhirls — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/688)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnLCaron)

**Comment by lesserwhirls** [comment]
> 
> > ```java
> >       return super.getForecastTimeIntervalSizeInHours(pds);
> >     }
> >     // LOOK barf
> > ```
> 
> 🤮

This was more of a comment in agreement that yeah, barf indeed. Nothing like GRIB to force the need for barf comments because messages can be encoded without critical information. It's a shame we can't use emojis in package names...just imagine `ucar.nc2.grib🤮`...ok, yeah, probably best that I am not allowed to do that.

**Comment by lesserwhirls** [comment]
At any rate, merging in now - thanks @JohnLCaron!

**Pull request merged**
