### PR TITLE
Service provider for IOSPs.

### PR DESCRIPTION
**Pull request by JohnLCaron**
5.2 branch.

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Not sure why this dap4 test is failing:

dap4.test.TestNc4Iosp > testNc4Iosp STANDARD_ERROR
    Netcdf-c library version: 4.5.0 of Dec  9 2017 03:15:29 $
    Testcase: /home/travis/build/Unidata/netcdf-java/dap4/d4tests/src/test/data/resources/testfiles/test_one_var.nc
    Testpath: /home/travis/build/Unidata/netcdf-java/dap4/d4tests/src/test/data/resources/testfiles/test_one_var.nc
    Baseline: /home/travis/build/Unidata/netcdf-java/dap4/d4tests/src/test/data/resources/TestIosp/baseline/test_one_var.nc.nc4
    DMR Comparison:
    Files are Identical
    DATA Comparison:
    Files are Identical
    Testcase: /home/travis/build/Unidata/netcdf-java/dap4/d4tests/src/test/data/resources/testfiles/test_one_vararray.nc
    Testpath: /home/travis/build/Unidata/netcdf-java/dap4/d4tests/src/test/data/resources/testfiles/test_one_vararray.nc
    Baseline: /home/travis/build/Unidata/netcdf-java/dap4/d4tests/src/test/data/resources/TestIosp/baseline/test_one_vararray.nc.nc4
    DMR Comparison:
    Files are Identical
    DATA Comparison:
    Files are Identical
    Testcase: /home/travis/build/Unidata/netcdf-java/dap4/d4tests/src/test/data/resources/testfiles/test_atomic_types.nc
    Testpath: /home/travis/build/Unidata/netcdf-java/dap4/d4tests/src/test/data/resources/testfiles/test_atomic_types.nc
    Baseline: /home/travis/build/Unidata/netcdf-java/dap4/d4tests/src/test/data/resources/TestIosp/baseline/test_atomic_types.nc.nc4
    DMR Comparison:
    >>>> 18 CHANGED FROM
        enum cloud_class_t primary_cloud;
          string primary_cloud:_FillValue = "Missing";
        enum cloud_class_t secondary_cloud;
    >>>>     CHANGED TO
        enum primary_cloud primary_cloud;
          string primary_cloud:_FillValue = "Missing";
        enum secondary_cloud secondary_cloud;
    >>>> Dap4 Testing: End of differences.

The only thing different is a different way to get the netcdf4 iosp (java or c++). Possible i screwed that up, but why dont the other change?

The java version is different anyway:

**Comment by lesserwhirls** [comment]
This is a tricky one. `dap4` seem to heavily depend on the C library. I'm pretty sure Dennis changed the code to explicitly look for the C library (outside of IOSP loading) and make direct JNA calls, but it looks like the test is still trying to load the IOSP. Locally, using netCDF-C 4.7.0, I get 

~~~java
java.lang.Error: Invalid memory access

	at com.sun.jna.Native.read(Native Method)
	at com.sun.jna.Pointer.read(Pointer.java:179)
	at com.sun.jna.Pointer.getIntArray(Pointer.java:716)
	at ucar.nc2.jni.netcdf.Nc4Iosp.decodeVlen(Nc4Iosp.java:1975)
	at ucar.nc2.jni.netcdf.Nc4Iosp.convertHeap(Nc4Iosp.java:1911)
	at ucar.nc2.jni.netcdf.Nc4Iosp.readCompound(Nc4Iosp.java:1843)
	at ucar.nc2.jni.netcdf.Nc4Iosp.readDataAll(Nc4Iosp.java:1804)
	at ucar.nc2.jni.netcdf.Nc4Iosp.readData(Nc4Iosp.java:1568)
	at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:2175)
~~~

My 2 cents for the moment - annotate that failing class with `@Category(NotTravis.class)` and see how the other tests go. The failure will still show up on Jenkins, but it won't hold up github. Travis is using an older netcdf-c library; Jenkins isn't much better. Once we have the `netcdf4-native` package, then we'll be able to better test these.

**Comment by lesserwhirls** [comment]
Shouldn't that annotation have been added to `dap4.test.TestNc4Iosp`?

**Comment by JohnLCaron** [comment]
Now it looks like TestNc4Iosp in TDS is failing?
Pain because I dont have libnetcdf loaded, so cant test locally. 

I wonder about reverting "NetcdfFile.registerIOProviderPreferred not needed", since I dont really understand why registerIOProviderPreferred was needed in the first place:

 NetcdfFile.registerIOProviderPreferred(NC4IOSP, ucar.nc2.iosp.hdf5.H5iosp.class);

**Comment by lesserwhirls** [comment]
The `NetcdfFile.registerIOProviderPreferred` was all about providing a way to force the usage of netCDF-C for reading as opposed to the pure java HDF5 reader. It was introduced [here](https://github.com/Unidata/thredds/commit/1f052ab2c0a6f78c46c1fc14071b29d40021c530), but not clear what exact problem it solved. I'd say the fact that we get a difference is indeed a bug, but not enough of one to hold up this PR. Given that it's annotated now to not run on travis, and everything else passes, I'm happy to let this light up on Jenkins and try to address the actual underlying issue in differences in behavior between the way C and Java see things.

**Comment by JohnLCaron** [comment]
Did the revert of the deletion of registerIOProviderPreferred() change the test result?

**Comment by JohnLCaron** [comment]
It appears not? We should disable the test until we can fix it. Otherwise, all subsequent PRs fail Travis check.

**Comment by JohnLCaron** [comment]
Errors on TDS are like:

`
/home/travis/build/Unidata/netcdf-java/tds_git_repo/it/src/test/java/thredds/tds/TestRestrictDataset.java:90: error: incompatible types: UsernamePasswordCredentials cannot be converted to URI
      session.setCredentials(new UsernamePasswordCredentials("baadss", "changeme"));
`
Is this from changes Dennis made?

**Comment by lesserwhirls** [comment]
Dang...so the netcdf-java tests were passing, and the tds tests failed due to change Dennis made (that I'm working on getting into the tds). I didn't see that spotless failed, but I'll grab that real quick.

**Pull request merged**
