### PR TITLE
Proto style and enum migration

### PR DESCRIPTION
**Pull request by lesserwhirls**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/679)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
This PR is an attempt to apply the [Google Protocol Buffers Style Guide](https://developers.google.com/protocol-buffers/docs/style) to the gCDM `.proto` files. Some of these changes are somewhat trivial, and include:

1. rename proto files using `snake_case` (e.g. `gcdmNetcdf.proto` &rarr; `gcdm_netcdf.proto`)
1. reorganize general `proto` file structure (syntax, package ,imports (sorted), file options, everything else)
1. migrating proto fields from `camelCase` to `snake_case` (e.g. `gridAxisType` to `grid_axis_type`)
   1. note: protoc will "do the expected thing", language-wise, and convert these to `camelCase` fields in the generated Java classes, maintain `snake_case` in the generated python, etc..
1. Use pluralized names for repeated fields (ugly, but hidden from the end user by `*Converter` classes).
1. Adding a license header

Not all changes in this PR are trivial, however. These non-trivial changes focus on `enum`s, and include:
* moving `enum`s defined within a `message` to outside of the `message`
* prefixing all `enum` values with by their `type`
* using `SCREAMING_SNAKE_CASE` for `enum` values
* using the suffix `UNSPECIFIED` for the first `enum` value (which maps to 0)
   * exception: `gcdm_netcdf.proto`: I did not change `DATA_TYPE_UNDEFINED`, although for consistency it should probably be `DATA_TYPE_UNSPECIFIED`)

There were also some cases in `gcdm_grid.proto` where I made the call to rename an `enum` type to avoid possible conflicts or go with the "cdm" theme, such as renaming `AxisType` to `CdmAxisType`. I also renamed `Calendar` to `CdmCalendar`, as `Calendar` seemed too generic, and given the requirement that `enum`s be unique globally, it seemed like a good idea. I could also see doing the same to some messages (adding a `Cdm` prefix) such as `CalendarDateRange`, `Rectangle` (maybe a better name, although currently unused?), and `Projection`).

Can discuss here or over at Unidata/netcdf-java#627.

**Review by JohnLCaron — COMMENTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/679)* status: all files reviewed, 2 unresolved discussions (waiting on @lesserwhirls)

___
*[gcdm/build.gradle, line 67 at r1](https://reviewable.io/reviews/unidata/netcdf-java/679#-M_WnYys2QgLdBHo-dYw:-M_WnYys2QgLdBHo-dYx:bwjo8bn) ([raw file](https://github.com/unidata/netcdf-java/blob/126644c2b9f8dddb1cb02c2dac6f32c64f972e18/gcdm/build.gradle#L67)):*
> ```Gradle
>     java {
>       // only needed for grpc (proto/main/java taken care of by
>       // $rootDir/gradle/any/protobuf.gradle)
> ```

ok to delete this comment i think
___
*[gcdm/src/main/proto/ucar/gcdm/gcdm_netcdf.proto, line 147 at r1](https://reviewable.io/reviews/unidata/netcdf-java/679#-M_WoAEI2WZs9RK0_7Yc:-M_WoAEJ6lMFPEbZe0Q-:bydexql) ([raw file](https://github.com/unidata/netcdf-java/blob/126644c2b9f8dddb1cb02c2dac6f32c64f972e18/gcdm/src/main/proto/ucar/gcdm/gcdm_netcdf.proto#L147)):*
> ```protobuf
> 
>   // oneof, depends on data_type
>   repeated bytes bdata = 3;   // ENUM1, BYTE, OPAQUE
> ```

I think this should now be ENUM1, BYTE, OPAQUE, CHAR

**Comment by JohnLCaron** [comment]
lgtm

**Comment by lesserwhirls** [comment]
Cool - thanks for taking a look. I've updated just a few things (your comments, a few typos) as well as renamed `DATA_TYPE_UNDEFINED` to `DATA_TYPE_UNSPECIFIED` in `gcdm_netcdf.proto` for consistency. I punted on the others for now.

**Review by haileyajohnson — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/679)* status: all files reviewed, 2 unresolved discussions (waiting on @lesserwhirls)

**Pull request merged**
