### PR TITLE
Grib GridDataset

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/739)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ucar.nc2.grid2 has a first pass at a new Grid API, except data reading.

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
A few minor things and a couple questions, but otherwise looks good, although I hate that GRIB forces its own GRID implementation...but GRIB gonna GRIB I guess.

> Reviewed 45 of 45 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/739#-:-MdJjC9nAnw7C5C7nBVv:b-o1iasr)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnLCaron)

___
*[cdm-core/src/main/java/ucar/nc2/grid2/GridAxisDependenceType.java, line 17 at r1](https://reviewable.io/reviews/unidata/netcdf-java/739#-MdJd-lf8j3FsYr3z_bA:-MdJd-lf8j3FsYr3z_bB:b-fpwmti) ([raw file](https://github.com/unidata/netcdf-java/blob/e5c20d194e0e609dfd2ccdfec88d2a8dbc0c16b3/cdm-core/src/main/java/ucar/nc2/grid2/GridAxisDependenceType.java#L17)):*
> ```Java
>    * Has its own dimension, so is a coordinate variable, eg x(x).
>    */
>   independent, //
> ```

Can get rid of the inline comment (minor)
___
*[cdm-core/src/main/java/ucar/nc2/grid2/GridAxisInterval.java, line 19 at r1](https://reviewable.io/reviews/unidata/netcdf-java/739#-MdJdBZE0gJu5wHvxxQJ:-MdJdBZE0gJu5wHvxxQK:b3ti7gq) ([raw file](https://github.com/unidata/netcdf-java/blob/e5c20d194e0e609dfd2ccdfec88d2a8dbc0c16b3/cdm-core/src/main/java/ucar/nc2/grid2/GridAxisInterval.java#L19)):*
> ```Java
> import java.util.List;
> 
> /** Interval Grib coordinates with values stored in memory. */
> ```

Grid? (although most interval coordinates come from GRIB)
___
*[cdm-core/src/main/java/ucar/nc2/grid2/GridAxisPoint.java, line 19 at r1](https://reviewable.io/reviews/unidata/netcdf-java/739#-MdJcxSj6-IKgVJ6mWmi:-MdJcxSj6-IKgVJ6mWmj:b-87h8i4) ([raw file](https://github.com/unidata/netcdf-java/blob/e5c20d194e0e609dfd2ccdfec88d2a8dbc0c16b3/cdm-core/src/main/java/ucar/nc2/grid2/GridAxisPoint.java#L19)):*
> ```Java
> import java.util.List;
> 
> /** Point Grib coordinates with values stored in memory. */
> ```

Grid?
___
*[cdm-core/src/main/java/ucar/nc2/grid2/GridAxisSpacing.java, line 18 at r1](https://reviewable.io/reviews/unidata/netcdf-java/739#-MdJdq-O6J74Dbfy3SX-:-MdJdq-O6J74Dbfy3SX0:b-pxvjd8) ([raw file](https://github.com/unidata/netcdf-java/blob/e5c20d194e0e609dfd2ccdfec88d2a8dbc0c16b3/cdm-core/src/main/java/ucar/nc2/grid2/GridAxisSpacing.java#L18)):*
> ```Java
>    * resol = (start - end) / (npts-1)
>    */
>   regularPoint, //
> ```

Can remove inline comments
___
*[cdm-core/src/main/java/ucar/nc2/grid2/GridDatasetFactory.java, line 97 at r1](https://reviewable.io/reviews/unidata/netcdf-java/739#-MdJfbIxDXNoEYrTYlmr:-MdJfbIxDXNoEYrTYlms:blhsd24) ([raw file](https://github.com/unidata/netcdf-java/blob/e5c20d194e0e609dfd2ccdfec88d2a8dbc0c16b3/cdm-core/src/main/java/ucar/nc2/grid2/GridDatasetFactory.java#L97)):*
> ```Java
>     // LOOK what happens when grib module is not present?
>     try {
>       Class<?> c = GridDatasetFactory.class.getClassLoader().loadClass("ucar.nc2.grib.grid.GribGridDataset");
> ```

We'll need to make sure that the grib module is open for access by the core when we modularize (assuming we won't want `ucar.nc2.grib.grid.GribGridDataset` in the public API, and assuming we can't get rid of reflection here). I can create a github issue to track these cases.
___
*[cdm-core/src/main/java/ucar/nc2/grid2/GridTimeCoordinateSystem.java, line 23 at r1](https://reviewable.io/reviews/unidata/netcdf-java/739#-MdJgl-MDxieE8wYRkYD:-MdJgl-MDxieE8wYRkYE:bcoptfj) ([raw file](https://github.com/unidata/netcdf-java/blob/e5c20d194e0e609dfd2ccdfec88d2a8dbc0c16b3/cdm-core/src/main/java/ucar/nc2/grid2/GridTimeCoordinateSystem.java#L23)):*
> ```Java
>     SingleRuntime, // Single runtime
>     Offset, // All runtimes have the same offsets
>     OffsetRegular, // All runtimes, grouped by minutes from 0z, have the same offsets.
> ```

Does it need to be strictly "minutes since 0Z" or can it be any duration from a base time?

**Comment by JohnLCaron** [comment]
Ok to pick up these changes in the next PR?

**Comment by lesserwhirls** [comment]
Yeah, let's pick up over on PR Unidata/netcdf-java#742

**Pull request closed without merging**
