### PR TITLE
Fix jenkins tests (2)

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/373)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — COMMENTED** [review]
For the tests marked `@Ignore("too long")`, is that due to how long it takes them to run? If so, we could mark them with `@Slow` and then they would be skipped unless the `runSlowTests` [property was set](https://github.com/Unidata/netcdf-java/wiki/Testing#test-related-system-properties).

> Reviewed 17 of 17 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/373#-:-MCsOao286EWUzY0ASrf:bnd14sr)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by JohnLCaron** [comment]
Yes, could change to @Slow. Regenerating the indices might be needed (TestGribIndexCreation, TestGribIndexCreationOther)? I disabled for now.

**Comment by lesserwhirls** [comment]
Sounds good. Thanks @JohnLCaron!

**Pull request merged**
