### PR TITLE
Make Dimension Immutable.

### PR DESCRIPTION
**Pull request by JohnLCaron**
Remove syncExtend() from IOSP.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/392)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Note Nc4Iosp now broken. Will remove from build for now.

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 18 of 18 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/392)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Let me know when you're ready and we'll bring it in

**Comment by JohnLCaron** [comment]
ready

**Pull request merged**
