### PR TITLE
Misc deletions of deprecated classes.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/368)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Comment by lesserwhirls** [comment]
Reviewable is down (was just about to submit the review). Would you mind updating the `Main-Class` attribute we set in the jar manifest in `cdm/core/build.gradle`?

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
> Reviewed 110 of 110 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/368)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Awesome - thanks @JohnLCaron!

**Review by lesserwhirls — APPROVED** [review]

**Pull request merged**
