### PR TITLE
Move cdm-misc tests out of cdm-test.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/344)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
So we wont know if this is really right until we run cdm-test tests, though Jenkins? Is there a way to run those tests before its committed?

**Comment by JohnLCaron** [comment]
And now the question occurs: Is jenkins set up to run tests in all the modules? So as we move tests to their respective modules, will they get picked up?

**Comment by lesserwhirls** [comment]
I have this one running on Jenkins now. Jenkins runs the `testAll` task, which will run the test task for all subprojects, so things should get picked up automagically. I'll also get the cdm-image PR running as well.

**Comment by lesserwhirls** [comment]
Here are the failures for `cdmTestBreakupMisc`:

~~~

ucar.nc2.TestReadFormats.testAllFormat
ucar.nc2.TestSequence.testRead
ucar.nc2.ft.coverage.TestCoverageClassificationP.testAdapter[/share/testdata/cdmUnitTest/thredds-test-data/local/thredds-test-data/cdmUnitTest/formats/dmsp/F14200307192230.s.OIS]
ucar.nc2.ft.coverage.TestCoverageClassificationP.testFactory[/share/testdata/cdmUnitTest/thredds-test-data/local/thredds-test-data/cdmUnitTest/formats/dmsp/F14200307192230.s.OIS]
ucar.nc2.ft.coverage.TestCoverageSwath.TestCoverageSize
ucar.nc2.ft.point.TestPointDatasets.checkPointFeatureDataset[/share/testdata/cdmUnitTest/thredds-test-data/local/thredds-test-data/cdmUnitTest/ft/point/200929100.ingest]
ucar.nc2.ft.point.TestPointDatasets.checkPointFeatureDataset[/share/testdata/cdmUnitTest/thredds-test-data/local/thredds-test-data/cdmUnitTest/ft/point/uspln_20061023.18]
ucar.nc2.ncml.TestNcmlWriteAndCompareShared.compareNcML[/share/testdata/cdmUnitTest/thredds-test-data/local/thredds-test-data/cdmUnitTest/formats/dmsp/F14200307192230.n.OIS]
ucar.nc2.geotiff.TestGeoTiffWriter.testWriteCoverage[/share/testdata/cdmUnitTest/thredds-test-data/local/thredds-test-data/cdmUnitTest/gribCollections/tp/GFS_Global_onedeg_ana_20150326_0600.grib2.ncx4]
ucar.nc2.geotiff.TestGeoTiffWriter.testWriteCoverage[/share/testdata/cdmUnitTest/thredds-test-data/local/thredds-test-data/cdmUnitTest/gribCollections/tp/GFSonedega.ncx4] 
ucar.nc2.geotiff.TestGeoTiffWriter.testWriteCoverage[/share/testdata/cdmUnitTest/thredds-test-data/local/thredds-test-data/cdmUnitTest/gribCollections/gfs_2p5deg/gfs_2p5deg.ncx4]
ucar.nc2.geotiff.TestGeoTiffWriter.testWriteCoverage[/share/testdata/cdmUnitTest/thredds-test-data/local/thredds-test-data/cdmUnitTest/gribCollections/gfs_2p5deg/gfs_2p5deg.ncx4]
~~~

I ran this one under my Jenkins job: https://jenkins-aws.unidata.ucar.edu/view/Sean/job/sean-netcdf-java/lastCompletedBuild/testReport/

**Comment by JohnLCaron** [comment]
Why did jenkins run #57 drop to 4 failures? Hmmm.

Anyway, I have a bunch of changes Im about to send over.

**Comment by JohnLCaron** [comment]
This should now pass jenkins test.

**Comment by lesserwhirls** [comment]
Sorry for the delay - yeah, it's not clear how I was doing the multiple runs on jenkins. 57 dropped to 4 because that run was using your `cdmTestBreakupRadial` branch.

Here is what we have as of now:

`cdmTestBreakupMisc` (before your most recent commit) -> https://jenkins-aws.unidata.ucar.edu/job/sean-netcdf-java/56/
`cdmTestBreakupImage` -> https://jenkins-aws.unidata.ucar.edu/view/John/job/john-caron-netcdf-java/10/
`cdmTestBreakupRadial` -> https://jenkins-aws.unidata.ucar.edu/job/sean-netcdf-java/57/

Running this one once more to pick up the most recent commit. It will be at https://jenkins-aws.unidata.ucar.edu/job/sean-netcdf-java/58/

**Comment by JohnLCaron** [comment]
ready

**Pull request merged**
