### PR TITLE
Clean up URLDumpPane

### PR DESCRIPTION
**Pull request by JohnLCaron**
add some methods in httpservices for better visibility.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/233)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready for review

**Review by lesserwhirls — APPROVED** [review]
Awesome. Looks good to me. Begin able to see the headers easily is super useful.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/233#-:-M2noXgc1iGE2p2I4Xca:bn0iyei)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Want me to merge this in before or after Unidata/netcdf-java#231?

**Comment by JohnLCaron** [comment]
Doesnt matter, they should be independent. But do 231 first in case im wrong.

**Pull request merged**
