### PR TITLE
String eos metadata

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/486)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
WHen you get a chance, can you add complete VNP10A1_A2018001_h31v11_001_2019126193423_HEGOUT.nc to cdmUnitTest files? I will need it to test with. thanks

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/486)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnLCaron)

___
*[cdm-test/src/test/java/ucar/nc2/internal/iosp/hdf5/TestH5eos.java, line 89 at r1](https://reviewable.io/reviews/unidata/netcdf-java/486#-MHm-UId3N3yPDa0ALBs:-MHm-UId3N3yPDa0ALBt:b-jgbt7o) ([raw file](https://github.com/unidata/netcdf-java/blob/3ec05ffba8ec4eaca683b943d0d9358daeca999a/cdm-test/src/test/java/ucar/nc2/internal/iosp/hdf5/TestH5eos.java#L89)):*
> ```Java
>    * public void testNetcdf4() throws IOException {
>    * try (NetcdfFile ncfile =
>    * NetcdfFiles.open("C:/Users/snake/Downloads/VNP10A1_A2018001_h31v11_001_2019126193423_HEGOUT.nc")) {
> ```

Should be available at `TestDir.cdmUnitTestDir + "cdmUnitTest/formats/netcdf4/VNP10A1_A2018001_h31v11_001_2019126193423_HEGOUT.nc"` (after running rsync).

**Comment by JohnLCaron** [comment]
ready

**Comment by lesserwhirls** [comment]
Almost caught up! This one just needs a rebase (and the test that uses the new file, if you want to do that on this PR).

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/486)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Awesome - thank you @JohnLCaron!

**Pull request merged**
