### PR TITLE
fix remaining failing jenkins tests

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/349)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Sorry for the delay - just ran this on Jenkins and we're down to one failure:

https://jenkins-aws.unidata.ucar.edu/view/John/job/john-caron-netcdf-java/12/

Happy to merge this one in, unless you think the fix is quick and you'd like to tack it on (I'm also happy to take a stab).

**Comment by JohnLCaron** [comment]
The remaining failure is mysterious.

Good=31 Fail=0

But then apparently at line 41

    assert countFail == 0 : "Failed = " + countFail;

Running locally is fine.

Have a look at it, maybe some new eyes will see the obvious.

**Comment by JohnLCaron** [comment]
Its not even obvious what class is failing, since there are 4 TestReadFormats now, but based on what files are run, it must be

..netcdf-java\visad\mcidas\src\test\java\ucar\nc2\TestReadFormats.java

maybe there are raw jenkins logs somewhere with more info?

**Comment by lesserwhirls** [comment]
The full log is here:

https://jenkins-aws.unidata.ucar.edu/view/John/job/john-caron-netcdf-java/12/consoleText

The good news is that it's an "ok" failure:

~~~
ucar.nc2.TestReadFormats > testReadFormats STANDARD_OUT
      GOOD on /share/testdata/cdmUnitTest/thredds-test-data/local/thredds-test-data/cdmUnitTest/formats/gempak/19580807_upa.gem == GempakSounding
      FAIL on /share/testdata/cdmUnitTest/thredds-test-data/local/thredds-test-data/cdmUnitTest/formats/gempak/19580807_upa.gem.hexdat.txt == java.io.IOException: Cant read /share/testdata/cdmUnitTest/thredds-test-data/local/thredds-test-data/cdmUnitTest/formats/gempak/19580807_upa.gem.hexdat.txt: not a valid CDM file.
~~~

Yep, reading a hexdump isn't going to work out so well. I can remove that from the test datasets and we'll be good to go :-)

**Comment by lesserwhirls** [comment]
Yep, that was it. Thanks @JohnLCaron - we're at zero!

**Pull request merged**
