### PR TITLE
a few more CoordSystemBuilders ported.

### PR DESCRIPTION
**Pull request by JohnLCaron**
Some mostly minor cleanup on docs and API.
Some changes for defining what will be in the public API.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/206)

### CODE REVIEW

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 27 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/206)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnLCaron)

___
*[cdm/core/src/main/java/ucar/nc2/dataset/CoordinatesHelper.java, line 20 at r1](https://reviewable.io/reviews/unidata/netcdf-java/206#-M-y_b6sC7SePetO3gIu:-M-y_b6sC7SePetO3gIv:b32v57) ([raw file](https://github.com/unidata/netcdf-java/blob/9572b0dd9072413752965d6ba2ff14e2a27bd99b/cdm/core/src/main/java/ucar/nc2/dataset/CoordinatesHelper.java#L20)):*
> ```Java
> /**
>  * A helper class for NetcdfDataset to build and manage coordinates.
>  * Probably want to move to ucar.nc2.internal.dataset, so its not part of the public API.
> ```

+1

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/206)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnLCaron)

___
*[docs/build.gradle, line 101 at r1](https://reviewable.io/reviews/unidata/netcdf-java/206#-M-ycISl8j6763eLON4x:-M-ycISl8j6763eLON4y:bid6mik) ([raw file](https://github.com/unidata/netcdf-java/blob/c0194adac0a3bcbec90fce32dd5a65c276468154/docs/build.gradle#L101)):*
> ```Gradle
>     include 'ucar/nc2/dataset/**/*.java'
>     include 'ucar/nc2/dt/RadialDatasetSweep.java'
>     include 'ucar/nc2/ft/*.java'
> ```

Are some of these removals temporary?

**Comment by JohnLCaron** [comment]
Not trying to be definitive here, but I am thinking of removing packages we're not sure of yet and just including ones that we think are in the public API. But even for that, just a strawman to see what the HTML looks like.
If you want to release this soon, Im ok with reverting this list to original, since the API is not really that close.

**Review by lesserwhirls — COMMENTED** [review]
Sounds good to me. Maybe revert with comments indicating things on the slate after the next release. It feels like most of those could probably go into a new module, if not a new project.

> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/206#-:-M-zme_m1buuJF-M9ABP:b-ay5avj)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnLCaron)

**Pull request merged**
