### PR TITLE
Cleanup unidata.geoloc

### PR DESCRIPTION
**Pull request by JohnLCaron**
Make ProjectionRect immutable by adding a builder.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/445)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
???
2020-08-17T22:41:32.8039982Z Reading package lists...
2020-08-17T22:41:32.8457768Z E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (129084 != 128880). Mirror sync in progress? [IP: 13.82.67.141 443]
2020-08-17T22:41:32.8458281Z    Hashes of expected file:
2020-08-17T22:41:32.8458706Z     - Filesize:128880 [weak]
2020-08-17T22:41:32.8459240Z     - SHA512:1efddff25021ac53b4710ba4ae97c38faed3cf40ca7c32d30a064f997f9c28732ead02e52d34f266dbefc59a9a34760b5d85ed1c9a223d1f6d2c3616fd139658
2020-08-17T22:41:32.8459714Z     - SHA256:f8c839d306df54d68365ccd0238dfd90d978bd0b7e18f77de3a301a514b1713f
2020-08-17T22:41:32.8460148Z     - SHA1:945b754c2d1f7299d4219efd378c6b1a15f56bec [weak]
2020-08-17T22:41:32.8460562Z     - MD5Sum:c97ad3a1e8b48f125c79588119cd8a0f [weak]
2020-08-17T22:41:32.8461101Z    Release file created at: Mon, 17 Aug 2020 17:08:46 +0000
2020-08-17T22:41:32.8461436Z E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by lesserwhirls** [comment]
Looks like a hiccup with ubuntu installing netCDF-C (looks like it worked this time).

**Comment by lesserwhirls** [comment]
Would you mind rebasing this one?

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 118 of 119 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/445)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
I think we're getting to the point where we can go through the `cdm` subproject's `build.gradle` and clarify some of the `compile` dependencies as either `api` or `implementation`. I can take a pass at that.

**Comment by JohnLCaron** [comment]
that would be great

> I think we're getting to the point where we can go through the cdm subproject's build.gradle and clarify some of the compile dependencies as either api or implementation. I can take a pass at that.

theres also this annoying message:

>> Configure project :httpservices
Found slf4j-api dependency but no providers were found.  Did you mean to add slf4j-simple? See https://www.slf4j.org/codes.html#noProviders .

**Comment by JohnLCaron** [comment]
ready

**Comment by lesserwhirls** [comment]
> Configure project :httpservices
Found slf4j-api dependency but no providers were found. Did you mean to add slf4j-simple? See

Yeah, that's an issue with gretty. It behaves like it expects that the project it is applied to has a logging binding on the runtime classpath, which isn't the case for `httpservices` (but we use gretty to spinup a server for the test). I'm looking into it though.

**Comment by lesserwhirls** [comment]
> It behaves like it expects that the project it is applied to has a logging binding on the runtime classpath

Turns out that's exactly what's happening:

https://github.com/gretty-gradle-plugin/gretty/blob/81bf115d7f39ee1060a2b0a6f02e503366645dcb/libs/gretty/src/main/groovy/org/akhikhl/gretty/GrettyPlugin.groovy#L126-L131

Unfortunately, gradle logging isn't super configurable, so the best we can do is change the overall gradle logging level by adding `org.gradle.logging.level=quiet` to `gradle.properties`, for example. That will kill all WARN level messages though, so it's best to set that in your local `~/.gradle/gradle.properties` file as opposed to the `gradle.properties` file in the project root.

**Pull request merged**
