### PR TITLE
Refactor grid subsetting.

### PR DESCRIPTION
**Pull request by JohnLCaron**
GridTimeCoordinateSystem Time2d -> OffsetIrregular

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/756)

### CODE REVIEW

**Review by lesserwhirls — COMMENTED** [review]
> Reviewed 37 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/756)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnLCaron)

___
*[cdm-core/src/main/java/ucar/nc2/internal/grid2/SubsetHelpers.java, line 245 at r1](https://reviewable.io/reviews/unidata/netcdf-java/756#-Me7UZMg-mktEYSXZ9kx:-Me7UZMg-mktEYSXZ9ky:bvhhqp0) ([raw file](https://github.com/unidata/netcdf-java/blob/ffef2d5085c488e48007f748e176738e795d1658/cdm-core/src/main/java/ucar/nc2/internal/grid2/SubsetHelpers.java#L245)):*
> ```Java
>   // return index of closest value to target
>   // For Discontiguous Intervals, "closest" means:
>   // - time coordinate axis? Interval such that the end of the interval is closest to the target value
> ```

One of the things I did with subsetting Coverages in 5 was to really try to understand how best to subset the time axis for interval times. That's why there is a bit of complexity in these methods and why time is treated differently. I'm not sure it is the 100% right thing to do, but maybe the 90% right thing to do. I'd love to chat about this differentiation specifically and why I went this route, to get your thoughts.
___
*[docs/developer/src/site/pages/grid/subsetting.md, line 1 at r1](https://reviewable.io/reviews/unidata/netcdf-java/756#-Me7W36UA9mGMF_9uy4E:-Me7W36UA9mGMF_9uy4F:bj95k8u) ([raw file](https://github.com/unidata/netcdf-java/blob/ffef2d5085c488e48007f748e176738e795d1658/docs/developer/src/site/pages/grid/subsetting.md#L1)):*
> ```Markdown
> # Grid Dataset subsetting
> ```

At the top of this file, add something like:

```
---
title: Grid Dataset subsetting
last_updated: 2021-07-08
sidebar: developer_sidebar 
permalink: grid_subsetting.html
toc: false
---
```

Then, in `docs/developer/src/site/_data/sidebars/developer_sidebar.yml`, just above line 93`- title: Reading CDM`, I would say add the following:

```
  - title: Feature Types
    output: web, pdf
    folderitems:
    subfolders:
        - title: GRID
          output: web, pdf
          subfolderitems:
            - title: Subsetting
              url: /grid_subsetting.html
              output: web, pdf
```

This should add a new top level entry to the left sidebar on https://docs.unidata.ucar.edu/netcdf-java/7.0/developer/ called "Feature Types", and when it expands, there will be an entry called "GRID". When that expands, there will be an entry called "Subsetting" that takes you to the html rendered version of this markdown file.

If this makes no sense and you don't want to deal with it, I can pick it up in another PR.

**Comment by JohnLCaron** [comment]
Yes, lets talk about subsetting time coordinates. How do they differ from vertical intervals? Can we document that in subsetting.md?

More generally, Im trying to wrap my head around what subset options there should be.

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
Ok, cool - I'll reach out about meeting. But for now, I'll get this merged in. Thanks @johnlcaron!

> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/756#-:-MeBZ5gu12bcESR7Cc_J:b-q0c609)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnLCaron)

**Pull request merged**
