### PR TITLE
Runtime config cleanup and testing.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/449)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 28 of 30 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/449)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
So this one and Unidata/netcdf-java#450 show a conflict with the last merge. Would you mind taking a look?

**Comment by JohnLCaron** [comment]
Im rebasing #451 which includes this

**Comment by JohnLCaron** [comment]
ready

**Comment by JohnLCaron** [comment]
oh, i see its already in #451

**Pull request closed without merging**
