### PR TITLE
Fix Jenkins errors.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/553)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Comment by lesserwhirls** [comment]
Hmm. I thought this one was in Unidata/netcdf-java#557, but maybe not?

**Comment by JohnLCaron** [comment]
Let me rebase and find out

**Comment by JohnLCaron** [comment]
Looks like it was.

**Pull request closed without merging**
