### PR TITLE
Clarify VerticalCTBuilder and VerticalTransformBuilder.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/557)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 7 of 64 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/557)* status: 8 of 98 files reviewed, 3 unresolved discussions (waiting on @JohnLCaron and @lesserwhirls)

___
*[cdm/core/src/main/java/ucar/nc2/NetcdfFile.java, line 767 at r2](https://reviewable.io/reviews/unidata/netcdf-java/557#-MLm7tDXAwy_z3ef52Ja:-MLm7tDXAwy_z3ef52Jb:b-lcvwge) ([raw file](https://github.com/unidata/netcdf-java/blob/db6ade310b7118fd369fe79e24be00e84845c754/cdm/core/src/main/java/ucar/nc2/NetcdfFile.java#L767)):*
> ```Java
> 
>   /** @deprecated do not use */
>   @Deprecated
> ```

Should we remove the deprecation in 5.x as well?
___
*[cdm/core/src/main/java/ucar/nc2/dataset/VariableDS.java, line 160 at r7](https://reviewable.io/reviews/unidata/netcdf-java/557#-MLm8RDUAe54ZciMa4IH:-MLm8RDUAe54ZciMa4II:brj1m9c) ([raw file](https://github.com/unidata/netcdf-java/blob/db6ade310b7118fd369fe79e24be00e84845c754/cdm/core/src/main/java/ucar/nc2/dataset/VariableDS.java#L160)):*
> ```Java
>   }
> 
>   public boolean hasCachedDataRecurse() {
> ```

Need to add deprecation in 5.x?
___
*[cdm/core/src/main/java/ucar/nc2/dataset/VerticalCT.java, line 85 at r2](https://reviewable.io/reviews/unidata/netcdf-java/557#-MLm8oaJ8OEupmzT-aIh:-MLm8oaK4zwtfzd_yP8O:b-dogv8v) ([raw file](https://github.com/unidata/netcdf-java/blob/db6ade310b7118fd369fe79e24be00e84845c754/cdm/core/src/main/java/ucar/nc2/dataset/VerticalCT.java#L85)):*
> ```Java
>    * @param builder creates the VerticalTransform
>    */
>   public VerticalCT(String name, String authority, VerticalCT.Type type, VertTransformBuilderIF builder) {
> ```

5.x deprecation?

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
> Reviewed 57 of 64 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 17 of 17 files at r5, 46 of 46 files at r6, 35 of 35 files at r7.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/557)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnLCaron)

___
*[cdm/core/src/main/java/ucar/nc2/AttributeContainerMutable.java, line 4 at r6](https://reviewable.io/reviews/unidata/netcdf-java/557#-MLmC1B01uQ8-OVThyDq:-MLmC1B13eehuAAqGD1T:bokkwvj) ([raw file](https://github.com/unidata/netcdf-java/blob/bff5303548be81cf5aba914b831edfc55ca5a34a/cdm/core/src/main/java/ucar/nc2/AttributeContainerMutable.java#L4)):*
> ```Java
> package ucar.nc2;
> 
> import com.google.common.base.Objects;
> ```

Any reason to the Guava `Objects` in place of `java.util.Objects`?
___
*[cdm/core/src/main/java/ucar/nc2/dataset/CoordinateTransform.java, line 7 at r7](https://reviewable.io/reviews/unidata/netcdf-java/557#-MLmDwZ-9vEBeOL3C26d:-MLmDwZ-9vEBeOL3C26e:br2lrvc) ([raw file](https://github.com/unidata/netcdf-java/blob/bcac8b4913bd50f2e2083bf24b055344185b9a48/cdm/core/src/main/java/ucar/nc2/dataset/CoordinateTransform.java#L7)):*
> ```Java
> package ucar.nc2.dataset;
> 
> import com.google.common.base.Objects;
> ```

`java.util.Objects`?

**Review by lesserwhirls — COMMENTED** [review]
Looks good. Just a few questions about adding/removing deprecations in `5.x` and the use of Guava `Objects` over `java.util.Objects`.

> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/557#-:-MLmE3jK5o63vUAwAMxX:b-lr0trp)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnLCaron)

**Comment by JohnLCaron** [comment]
Yes, the deprecation changes should be backported to 5.

Yes, I see that guava Objects should be changed to java Objects. Perhaps we should do a big sweep for that, rather than piecemeal.

**Comment by lesserwhirls** [comment]
Sounds good to me. Thanks @JohnLCaron!

**Pull request merged**
