### PR TITLE
Add GribTable information to GribIosp.getDetailInfo().

### PR DESCRIPTION
**Pull request by JohnLCaron**
Capture all TwoD types in CdmIndexScan.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/733)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Review by haileyajohnson — CHANGES_REQUESTED** [review]
> Reviewed 12 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/733)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @JohnLCaron and @lesserwhirls)

___
*[cdm-test/src/test/java/ucar/nc2/grib/coord/TestIsRegular.java, line 68 at r1](https://reviewable.io/reviews/unidata/netcdf-java/733#-Mcyy9595-xmOyzCMDLG:-Mcyy9595-xmOyzCMDLH:brsur1o) ([raw file](https://github.com/unidata/netcdf-java/blob/affd56393d313a239f8c78bb3c6711c7e59593ff/cdm-test/src/test/java/ucar/nc2/grib/coord/TestIsRegular.java#L68)):*
> ```Java
>     }
>     fail();
>     return false;
> ```

Is there a reason to fail in this method instead of returning false and failing on the next assert?
___
*[cdm-test/src/test/java/ucar/nc2/grib/coord/TestIsRegular.java, line 74 at r1](https://reviewable.io/reviews/unidata/netcdf-java/733#-McyyTeiBVVsByP5qcjQ:-McyyTeiBVVsByP5qcjR:b-qspf8c) ([raw file](https://github.com/unidata/netcdf-java/blob/affd56393d313a239f8c78bb3c6711c7e59593ff/cdm-test/src/test/java/ucar/nc2/grib/coord/TestIsRegular.java#L74)):*
> ```Java
>   private boolean testRegular(CoordinateTime2D time2D) {
>     // group time coords by offset
>     TreeMap<Integer, List<CoordinateTimeAbstract>> minuteMap = new TreeMap<>(); // <hour, all coords for that hour>
> ```

I think I'm missing why we would want this to be a TreeMap - do the times need to be ordered?

**Comment by JohnLCaron** [comment]
I removed the fail(), thanks.

testRegular() also prints out information, and it needs to be sorted to be sensible. I use this test to understand whats going on under the hood, and the printf's are part of this "manual debug" mode.

**Review by haileyajohnson — COMMENTED** [review]
> Reviewed 1 of 13 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/733)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnLCaron and @lesserwhirls)

**Review by haileyajohnson — APPROVED** [review]
gotcha, all looks good to me then

> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/733#-:-MczQQLoE9oVErm8CN1Q:b-ogt175)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnLCaron and @lesserwhirls)

**Pull request merged**
