### PR TITLE
Upgrade github actions

### PR DESCRIPTION
**Pull request by lesserwhirls**
## Description of Changes

GitHub is closing down `actions/cache` `v1` and `v2`, and this PR bumps us to the latest (`v4`). This also bumps `actions/setup-java` to the latest version (`v4`).

Also, disable the dap2 test that hits iridl.ldeo.columbia.edu (see https://github.com/Unidata/netcdf-java/pull/1396#issuecomment-2536495050) when testing PRs, and update the CODEOWNERS file.

## PR Checklist

- [x] Link to any issues that the PR addresses
- [x] Add labels
- [x] Open as a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/)
       until ready for review
- [x] Make sure GitHub tests pass
- [x] Mark PR as "Ready for Review"

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Updates based on the result of [this wayback machine diff](https://web.archive.org/web/diff/20200121200008/20241211171229/https://www.ucar.edu/who-we-are/ethics-integrity/codes-conduct/contributors)

**Comment by lesserwhirls** [comment]
@DennisHeimbigner - would you like to remain in the CODEOWNERS file? It's currently setup to automatically tag you as a reviewer for changes made to anything living under `httpservices/**`,`netcdf4/**`, `**/opendap/**`, and `**/dap4/**`.

**Comment by DennisHeimbigner** [comment]
If I am useful in that role, then yes. But I will defer to Ward about this.

**Comment by DennisHeimbigner** [comment]
And of course defer to you about the Java repositories. I am ok either way.

**Comment by lesserwhirls** [comment]
Thank you Dennis! I'd love to keep you in the loop on the dap2/dap4/netcdf4/httpservices netCDF-Java modules as long as you are willing (and if at any point the notifications become too much, just let me know!) The only dap2 related change is this PR is to disable a test that hits iridl.ldeo.columbia.edu, as I have noticed over the years that github periodically has trouble reaching the site (the test will still be run as part of other testing workflows, just not GitHub pull requests).

**Comment by DennisHeimbigner** [comment]
If memory serves, may years ago, Columbia was running a fork of the OPeNDAP Hyrax DAP2 server.
At the time, we decided to support the Columbia server. It is possible that they no longer
run a modified server. If they use standard Hyrax, then there is no particular point
in having a special test. We could also remove whatever quirky change they implemented from
our code.

**Comment by lesserwhirls** [comment]
It looks like that is still the case ([InGrid Docs](https://iridl.ldeo.columbia.edu/dochelp/topics/DODS/index.html)).

**Comment by DennisHeimbigner** [comment]
Sigh! Oh well.

**Pull request merged**
