### PR TITLE
Update JNA version

### PR DESCRIPTION
**Pull request by ethanrd**
## Description of Changes

For JNA before version 5.7.0, use of JNA fails at runtime on MacOS with M1 chip.

This PR updates to current JNA version 5.12.1.

## PR Checklist

- [ ] Link to any issues that the PR addresses
- [ ] Add labels
- [x] Open as a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/)
       until ready for review
- [ ] Make sure GitHub tests pass
- [ ] Mark PR as "Ready for Review"

### CODE REVIEW

**Comment by lesserwhirls** [comment]
How will this play out with the version used by Chronicle map on the TDS-side?

**Comment by lesserwhirls** [comment]
Here is an example describing where things went sideways when there was a version mismatch: https://github.com/Unidata/tds/pull/37

**Comment by lesserwhirls** [comment]
In happier news though, the update would address https://github.com/Unidata/netcdf-java/issues/199 as JNA 5.7.0 removed the native library code for darwin x86.

**Comment by ethanrd** [comment]
Hi @lesserwhirls - I ran into this failure while building/testing TDS on a new M1 machine. The symptoms where similar to what you described in Unidata/tds#37: `500` on any service except `catalog` and there were messages about null `datasetMap` like you mentioned and several related errors including a `NoClassDefFoundError` for JNA:

```
2022-11-16T15:29:11.957-0700 [     70500][        ] ERROR serverStartup: TdsInit: Failed initialize GridDatasetInv cache= /Users/edavis/code/tds/tds/src/test/content/thredds/cache/collection/
net.openhft.chronicle.hash.ChronicleHashRecoveryFailedException: java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at net.openhft.chronicle.map.ChronicleMapBuilder.openWithExistingFile(ChronicleMapBuilder.java:1926) ~[chronicle-map-3.21ea6.jar:3.21ea6]
	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1716) ~[chronicle-map-3.21ea6.jar:3.21ea6]
        ...
```

I found an [issue](https://github.com/oshi/oshi/issues/1462) (from Jan 2021) that seemed relevant, "Apple M1 hardware incompatibility for JNA Native class", and [mentions](https://github.com/oshi/oshi/issues/1462#issuecomment-768676937) the problem being fixed in JNA 5.7.0.

Since bumping the JNA version to "5.12.1" in `netcdf-java-platform/build.gradle`, my local build of TDS 5 using the netCDF-Java with the updated JNA no longer has failures on non-catalog requests or the various error messages.

Also, it looks like TDS now inherits the JNA version from the declaration in `netcdf-java-platform/build.gradle` rather than in `tds/gradle/any/dependencies.gradle` as in Unidata/tds#37. So maybe the potential conflict is gone now that the JNA version is only declared in one place?

**Comment by tdrwenski** [comment]
If it is helpful, I can do some testing on the chronicle map cache with this JNA version (was working on testing that recently anyhow).

**Comment by lesserwhirls** [comment]
The issue isn't so much the version of JNA that the TDS uses, it's the version that `chronical-map` uses. The version of `chronical-map` that the TDS is pulling in (`3.21ea6` from `chronical-bom` `2.21ea74`) currently uses JNA `5.5.0`. So the question is, how well will chronical-map handle having JNA version `5.5.0` swapped out with `5.12.1` at runtime?

We don't use much of the features of `chronical-map`, so my guess is it will fail spectacularly as before (tons of 500s), but it will need to be tested on multiple platforms to be sure. I'd be happy to give it a spin on Windows 10 if no devs are running Windows.

Longer term, we should probably look for a replacement for `chronical-map`. It was used to help with ESGF performance issues, but since they are moving away from the TDS, maybe it does not matter at this point given the headaches we've had.

**Comment by ethanrd** [comment]
Ah, yes, I see. And, unfortunately, the current chronicle-map still uses JNA 5.5.0. Except on mac os, if I'm reading [this](https://repo1.maven.org/maven2/net/openhft/third-party-bom/3.22.3/third-party-bom-3.22.3.pom) right, where it uses 5.8.0.

**Comment by lesserwhirls** [comment]
> Ah, yes, I see. And, unfortunately, the current chronicle-map still uses JNA 5.5.0. Except on mac os, if I'm reading [this](https://repo1.maven.org/maven2/net/openhft/third-party-bom/3.22.3/third-party-bom-3.22.3.pom) right, where it uses 5.8.0.

That's correct, but that is selected at build time, so only active if building on a mac. So in order to keep JNA versions between the TSD and netCDF-Java in-line (which we may or may not need, depending on testing) while also supporting M1 chips, we'd need to 1) update netCDF-Java to use JNA version `5.8.0` and build/publish a snapshot, 2) update the TDS to use the latest `chronicle-bom` (version `2.24ea9`) and latest snapshot of netCDF-Java, and 3) build the TDS war on a Mac -or- have Gradle ensure the TDS selects JNA `5.8.0` when resolving dependencies.

**Comment by ethanrd** [comment]
Sounds good. I'll start testing and will update this PR to use JNA 5.8.0 instead of 5.12.1.

**Comment by dbwiddis** [comment]
Hi, a JNA maintainer here.
> So the question is, how well will chronical-map handle having JNA version 5.5.0 swapped out with 5.12.1 at runtime?

JNA follows [semver](https://semver.org/), so I don't think this should cause any problems staying within 5.x.  I just reviewed the [change log](https://github.com/java-native-access/jna/blob/master/CHANGES.md) and don't see anything that would be risky at all, and several bug fixes/improvements between those versions.   The previous version mismatch issues linked earlier in this thread look like a 4.x to 5.x change.

> In happier news though, the update would address https://github.com/Unidata/netcdf-java/issues/199 

Yep, you definitely need 5.6.0+ for macOS 11+ compatibility.  If chronical-map is still on 5.5.0 it is incompatible with macOS 11, 12, and 13.

**Comment by lesserwhirls** [comment]
Thank you for reaching out @dbwiddis! Sounds like going with 5.12.1 will be ok @ethanrd.

**Comment by ethanrd** [comment]
Sounds good! I had dropped back to 5.8.0 just to match what Chronicle currently uses. But I will bump back to 5.12.1 and finish up some testing.

Thanks! @dbwiddis and @lesserwhirls

**Review by haileyajohnson — APPROVED** [review]

**Pull request merged**
