### PR TITLE
Added support to parse variable length char element from ncml

### LINKED ISSUE #1235: [VERSION]: 5.5.2 Exception thrown when accessing char data  from NetcdfDatasets.openNcmlDataset
### Versions impacted by the bug

v5.x

### What went wrong?

When processing variable length char data , the ncml parser attempts to read outside of bounds and throws an exception. 

Minimal example
```	
public static void main(String[] args) throws FileNotFoundException, URISyntaxException {

		ClassLoader classloader = Thread.currentThread().getContextClassLoader();
		URL input_ncml_url = classloader.getResource("test.ncml");
		Path path = Paths.get(input_ncml_url.toURI());
		File input_ncml = path.toFile();

		NetcdfDataset dataset = null;
		FileReader reader = new FileReader(input_ncml);

		try {
			dataset = NetcdfDatasets.openNcmlDataset(reader, null, null);
			Variable x = dataset.findVariable("variable_length_char");
			for (int i = 0; i < x.getSize(); i++) {
				System.out.println((int)x.read().getChar(i));
			}

		} catch (Exception e) {
			e.printStackTrace();
		}

	}
```

```
<?xml version="1.0" encoding="UTF-8"?>
<netcdf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2  http://www.unidata.ucar.edu/schemas/netcdf/ncml-2.2.xsd" xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
	<dimension name="num_fields" length="4" isUnlimited="false"/>
	<dimension name="max_len" length="4" isUnlimited="false"/>
	<variable name="variable_length_char" type="char" shape="num_fields max_len">
		<values>a bb ccc dddd</values>
	</variable>
</netcdf>
```

### Relevant stack trace

```shell
java.lang.ArrayIndexOutOfBoundsException: Index 13 out of bounds for length 13
	at ucar.ma2.ArrayChar.getChar(ArrayChar.java:472)
	at ucar.ma2.IteratorFast.getCharNext(IteratorFast.java:150)
	at ucar.ma2.MAMath.copyChar(MAMath.java:318)
	at ucar.ma2.MAMath.copy(MAMath.java:191)
	at ucar.ma2.Array.copy(Array.java:657)
	at ucar.nc2.Variable._read(Variable.java:733)
	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:430)
	at ucar.nc2.Variable.read(Variable.java:614)
	at ncml_test.Ncml_Test.main(Ncml_Test.java:34)
```

### Relevant log messages

_No response_

### If you have an example file that you can share, please attach it to this issue.
If so, may we include it in our test datasets to help ensure the bug does not return once fixed?
Note: the test datasets are publicly accessible without restriction.

Yes

### Code of Conduct

- [X] I agree to follow the UCAR/Unidata Code of Conduct

### PR DESCRIPTION
**Pull request by jmasson-l3h**
## Description of Changes

Added support to parse variable length tokens  for char arrays  in the ncml reader.   This is to help resolve issue #1235 

## PR Checklist

- [ ] Link to any issues that the PR addresses
- [ ] Add labels
- [ ] Open as a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/)
       until ready for review
- [ ] Make sure GitHub tests pass
- [ ] Mark PR as "Ready for Review"

### CODE REVIEW

**Comment by mnlerman** [comment]
@jmasson-l3h thank you for your contribution! The code looks good but please sign the CLA so that we can review and merge it.

**Comment by jmasson-l3h** [comment]
> @jmasson-l3h thank you for your contribution! The code looks good but please sign the CLA so that we can review and merge it.

Hello , when attempting to sign that I get "Internal Server Error"  on url "https://cla-assistant.io/auth/github/callback?code=9d9c182fce4a29a1e7a6" . 

Is there another mechanism to sign ?

**Comment by mnlerman** [comment]
https://cla-assistant.io/Unidata/netcdf-java?pullRequest=1236 Try this link

**Comment by jmasson-l3h** [comment]
> https://cla-assistant.io/Unidata/netcdf-java?pullRequest=1236 Try this link

Same issue with the internal server error.  I will  try on my personal computer later tonight.

**Comment by mnlerman** [comment]
Ahh hmm, I got the internal server error when I opened the link you provided but I was able to open the one that I sent. I wonder if the problem is associated with this message from above:

> Jeffrey Masson seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Unidata/netcdf-java?pullRequest=1236) it.

**Comment by jmasson-l3h** [comment]
> Ahh hmm, I got the internal server error when I opened the link you provided but I was able to open the one that I sent. I wonder if the problem is associated with this message from above:
> 
> > Jeffrey Masson seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> > You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Unidata/netcdf-java?pullRequest=1236) it.

I was able to do it from home, was probably a network/security issue on my side.

**Review by mnlerman — APPROVED** [review]

**Pull request merged**
