### PR TITLE
CoordSystemBuilder needs to track Dimensions with their Group.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/544)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
When this is right, will want to backport to ver5. See TestCoordSystemBuilder for example fail.

**Comment by lesserwhirls** [comment]
I think I just tackled the `TestCoordSystemBuilder` issue on the `maint-5.x` branch - see Unidata/netcdf-java#545

**Comment by JohnLCaron** [comment]
Ill have a look at your #545. The problem that I was seeing was that CoordSystemBuilder.isCoordinateAxisForVariable() was getting false positives for the common GRIB case of multiple groups (Best, TwoD) with equal dimensions, now that Dimension doesnt have a Group reference. Not sure if your case is different or the same. 

If you look at  ToolsUI coverage for TestDir.cdmUnitTestDir + "gribCollections/gdsHashChange/noaaport/NDFD-CONUS_noaaport.ncx4", you would see extra axes in the Coordinate Systems.

**Comment by JohnLCaron** [comment]
Just the changes in Group, NetcdfDataset and CoordSystemBuilder need to be backported.

**Comment by JohnLCaron** [comment]
ready

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
Looks good @johnlcaron - I made backports for `Group` and `NetcdfDataset` - I was able to get `CoordSystemBuilder` to work without the use of `AutoValue` (which would have added a new dependency in 5). I'll respond to your emails next.

> Reviewed 9 of 10 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/544#-:-ML8pYtE3Vgvybe8_dHp:b-t7ixen)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
