### PR TITLE
Optimize, re-format RotatedPole.

### PR DESCRIPTION
**Pull request by msdsoftware**

### CODE REVIEW

**Comment by msdsoftware** [comment]
Cannot figure out why Github is complaining about the license agreement, and offering me instructions about my commit e-mail address that make no sense.

**Comment by lesserwhirls** [comment]
Github looks at the email address in the commit and tries to map that to a github account. I think what's going on is that CLAHub looks for a github account. If CLAHub cannot find you as a github user (because the commit does not link your email address to an account), then it complains.

The email used in this commit is different than the one used in your commits over in the Unidata/thredds repo, so maybe it's not linked to you github account? You could either [add that email address to your github account](https://help.github.com/en/articles/adding-an-email-address-to-your-github-account), or change the email address on the commit to use the one you used over in Unidata/thredds (which looks to be an anonymous @users.noreply.github.com address). If you want to do the latter, you should be able to do this from within your local netcdf-java repository directory:

~~~bash
git config user.email 8718035+msdsoftware@users.noreply.github.com
git commit --amend --reset-author
~~~

This assumes you only have one commit to fix up (looks like that's the case). You'd then need to do a force push back to your branch on github to overwrite the commit message. You'd only need to do this once - the @users.noreply.github.com will be used in all future commits in your netcdf-java repo.

**Comment by msdsoftware** [comment]
@lesserwhirls, How do i figure what e-mail address was used in commit or pull request? I have 3 addresses attached to my Github account and it's a mystery to me why another might be used. Weee, maybe it's something flaky with my copy of Xcode and the related Apple developer ID.

**Comment by lesserwhirls** [comment]
I don't know of a way to see it through github's web interface, but I am able to see all of the commit info locally by running `git log`. For example, here is one of my commits:

~~~bash
commit 98c59c23ec59219ca71c317ef8504ea90ec96796 (sean/docs, docs)
Author: Sean Arms <67096+lesserwhirls@users.noreply.github.com>
Date:   Mon Jul 8 13:34:39 2019 -0600

    publish docs to new raw repo
~~~

**Comment by msdsoftware** [comment]
Looks like the address attached to the commit to my forked repo used my primary Github e-mail address. I see that I have commits/PRs to the thredds repo using that address as recent as late March.

**Comment by lesserwhirls** [comment]
Hmmm. @dopplershift - have you seen anything like this before?

**Comment by msdsoftware** [comment]
Replaced this PR attempt with #3.

**Comment by dopplershift** [comment]
Not sure what happened, but this was not giving me the warm and fuzzies:

image

I think a new repo/PR was a good way to go...

**Pull request closed without merging**
