### PR TITLE
IFPS, M3IO, MADIS conventions.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/202)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Failed on oraclejdk8:

edu.ucar.build.ui.ToolsUiJnlpExtensionTaskSpec > just the writer FAILED
    org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':runtime'.
        at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.rethrowFailure(DefaultLenientConfiguration.java:192)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$1.collectFiles(DefaultLenientConfiguration.java:141)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:810)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:376)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolve(DefaultConfiguration.java:372)
        at edu.ucar.build.ui.ToolsUiJnlpExtensionTask$Writer$_write_closure1.closure2$_closure4(ToolsUiJnlpExtensionTask.groovy:100)
        at edu.ucar.build.ui.ToolsUiJnlpExtensionTask$Writer$_write_closure1.closure2$_closure4(ToolsUiJnlpExtensionTask.groovy)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:408)
        at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:147)
        at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:67)
        at edu.ucar.build.ui.ToolsUiJnlpExtensionTask$Writer.write_closure1$_closure2(ToolsUiJnlpExtensionTask.groovy:97)
        at edu.ucar.build.ui.ToolsUiJnlpExtensionTask$Writer.write_closure1$_closure2(ToolsUiJnlpExtensionTask.groovy)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:408)
        at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:147)
        at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:67)
        at edu.ucar.build.ui.ToolsUiJnlpExtensionTask$Writer.write_closure1(ToolsUiJnlpExtensionTask.groovy:90)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:430)
        at edu.ucar.build.ui.ToolsUiJnlpExtensionTask$Writer.write(ToolsUiJnlpExtensionTask.groovy:83)
        at edu.ucar.build.ui.ToolsUiJnlpExtensionTaskSpec.just the writer(ToolsUiJnlpExtensionTaskSpec.groovy:69)

        Caused by:
        org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve org.slf4j:slf4j-api:1.7.7.

**Comment by JohnLCaron** [comment]
Another weird failure:

Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://artifacts.unidata.ucar.edu/repository/unidata-snapshots/org/bounce/bounce/0.18/bounce-0.18.pom'.

**Comment by JohnLCaron** [comment]
Ready to go

**Comment by lesserwhirls** [comment]
Travis gets flaky sometimes, and I don't know why. I'm looking at moving to GitHub actions, and this is one of the reasons...Thanks @JohnLCaron!

**Pull request merged**
