### PR TITLE
Fix failing tests

### PR DESCRIPTION
**Pull request by JohnLCaron**
Fixes Issue #659, which was apparently an error in our testing.
Add start of docs for Array.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/660)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
I believe this captures Unidata/netcdf-java#650, Unidata/netcdf-java#656, and Unidata/netcdf-java#657 (although the hashes changed between the 650 and the other two). I'll start with this one.

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, 26 of 26 files at r2, 3 of 3 files at r3, 18 of 18 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 6 of 6 files at r9, 5 of 5 files at r10, 6 of 6 files at r11.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/660)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnLCaron)

___
*[cdm/core/src/main/java/ucar/nc2/internal/iosp/netcdf3/N3iospWriter.java, line 47 at r2](https://reviewable.io/reviews/unidata/netcdf-java/660#-MYtVDej-rOpO8Y_71zB:-MYtVDej-rOpO8Y_71zC:b4v2m47) ([raw file](https://github.com/unidata/netcdf-java/blob/c3aef4dce015392637625c64a0e7f379f4962c1c/cdm/core/src/main/java/ucar/nc2/internal/iosp/netcdf3/N3iospWriter.java#L47)):*
> ```Java
>   }
> 
>   // open existing only. mapbe problem is using N3iospWriter for both cases.
> ```

Small typo ("maybe")
___
*[cdm/core/src/main/java/ucar/nc2/util/Misc.java, line 206 at r1](https://reviewable.io/reviews/unidata/netcdf-java/660#-MYqsfNAD5mhVLyglH5Y:-MYqsfNAD5mhVLyglH5Z:b-mbrbp4) ([raw file](https://github.com/unidata/netcdf-java/blob/c13fe432afa9d6898cebeab4b20a6ec3e46d82cc/cdm/core/src/main/java/ucar/nc2/util/Misc.java#L206)):*
> ```Java
>   }
> 
>   public static void showClassPath() {
> ```

Was this for debugging in `cdmr`? If we want to add it to the public api (which this would do), I just want to be sure it's going to be useful outside of one place.
___
*[cdm-test/src/test/java/ucar/nc2/write/TestNetcdfFormatWriterBig.java, line 35 at r2](https://reviewable.io/reviews/unidata/netcdf-java/660#-MYtWY-43OCApZaV4veG:-MYtWY-43OCApZaV4veH:b-m3vbuj) ([raw file](https://github.com/unidata/netcdf-java/blob/c3aef4dce015392637625c64a0e7f379f4962c1c/cdm-test/src/test/java/ucar/nc2/write/TestNetcdfFormatWriterBig.java#L35)):*
> ```Java
> import static ucar.nc2.NetcdfFile.IOSP_MESSAGE_GET_NETCDF_FILE_FORMAT;
> 
> /** Test write a Netcdf-3 file larger than 2 Gb. Takes a few minutes, so leave out of cdm unit tests. */
> ```

If we annotate with `@Category(NotPullRequest.class)`, it will skip running on GitHub Actions, but will still run on Jenkins.
___
*[gradle/any/dependencies.gradle, line 63 at r1](https://reviewable.io/reviews/unidata/netcdf-java/660#-MYqwS8OAS5jrw6yXOk-:-MYqwS8P1wEYYpaec1Tu:b-eotr21) ([raw file](https://github.com/unidata/netcdf-java/blob/c13fe432afa9d6898cebeab4b20a6ec3e46d82cc/gradle/any/dependencies.gradle#L63)):*
> ```Gradle
>     //    |    ...
>     //
>     substitute module('commons-logging:commons-logging') because 'we want to control JCL logging with slf4j' with module("org.slf4j:jcl-over-slf4j:${depVersion.slf4j}")
> ```

I think we talked about this, but can you remind me what issue this was causing? I believe we needed it elsewhere to keep jcl from shipping out as a dependency with our artifacts, which would take over as the slf4j implementation for our downstream users. I think I know a way around this while keeping it from applying to `cdmr` if that was the issue. If so, I can do that in another PR (if you would not mind opening an issue to remind me).
___
*[netcdf-java-platform/build.gradle, line 71 at r1](https://reviewable.io/reviews/unidata/netcdf-java/660#-MYqwuudB8rwgwqZj7De:-MYqwuudB8rwgwqZj7Df:b-xwwsua) ([raw file](https://github.com/unidata/netcdf-java/blob/c13fe432afa9d6898cebeab4b20a6ec3e46d82cc/netcdf-java-platform/build.gradle#L71)):*
> ```Gradle
>     api "org.slf4j:slf4j-api:${depVersion.slf4j}"
>     runtime 'ch.qos.logback:logback-classic:1.2.3'
>     runtime "org.slf4j:slf4j-jdk14:${depVersion.slf4j}"
> ```

I think `api` should  capture `runtimeOnly`, which is the replacement of `runtime`. So somewhere we must be using `org.slf4j:slf4j-jdk14` as `runtime` instead of `runtimeOnly` (I think). I can look at this as well, because we should not need to specifically add this here. I need to revisit the `netcdf-java-platfrom` setup anyways, so I'll take a look.

**Comment by JohnLCaron** [comment]
cdm/core/src/main/java/ucar/nc2/util/Misc.java, line 206 at r1 (raw file):

yes, I moved it to Misc because its broadly useful.

**Comment by JohnLCaron** [comment]
gradle/any/dependencies.gradle, line 63 at r1 (raw file):

The problem is that when this override is present, we cant (or I dont know how to) control jdk14 logging, used by gRpc. For some reason then all debug logs are sent and useful info is lost. Note that Ive added cdmr/src/main/resources/logging.cfg and ive been using -Djava.util.logging.config.file=cdmr/src/main/resources/logging.cfg on CdmrServer and tests.

I could add that Misc.showClassPath() is part of debugging whats going on.

Happy to have a better solution.

**Comment by JohnLCaron** [comment]
netcdf-java-platform/build.gradle, line 71 at r1 (raw file):

OK, im going to let you tackle the logging dependencies problems.

Maybe get these PRs done, then revisit this issue? Or let me know what changes you want.

**Review by lesserwhirls — APPROVED** [review]
Looks good - I'll take care of the others. Thank you @johnlcaron!

> Reviewed 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/660#-:-MYufTmb487bACdOyOtc:b600xxc)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnLCaron)

**Review by lesserwhirls — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/660)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnLCaron)

**Comment by JohnLCaron** [comment]
failing on s3 ??

**Comment by lesserwhirls** [comment]
The job hung so I canceled and restarted the run. I am about to make a PR with some changes to those tests.

**Pull request merged**
