### PR TITLE
Add suggested Java Style guidelines.

### PR DESCRIPTION
**Pull request by JohnLCaron**

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Maybe we should modify the [eclipse](https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml) and [intellij](https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml) java styles from https://github.com/google/styleguide with the changes you mention and include them in the repo for people to use?

**Comment by JohnLCaron** [comment]
Sounds good. I done see anyting in intellij style guide about the blank
javadoc. So just line width?

**Comment by JohnLCaron** [comment]
sorry, not sure how those extra PRs got tangled in here. Will redo when i have time.

**Comment by lesserwhirls** [comment]
I fixed it up 👍

**Comment by msdsoftware** [comment]
Thx for this. I noticed that after I blew up, refactored and reformatted various UI code earlier this year, that @JohnLCaron's subsequent changes to some of those classes reformatted the style again. So nice to know that there is now a guideline I can consult.

**Pull request merged**
