### PR TITLE
ucar.array.ArrayType

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/591)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
This allows array and ma2 to coexist, and to stabilize the array API.
More changes will be needed, but I wanted to get unit tests checked for these changes.
Ive also realized that I want to make array independent of nc2. The thought is to move it to its own module in version 7.

**Comment by lesserwhirls** [comment]
Looks like a conflict after the last PR merged. A rebase or merge should fix that up.

> Ive also realized that I want to make array independent of nc2. The thought is to move it to its own module in version 7.

That makes total sense. I know there are projects using netCDF-Java simply for the the current `ucar.ma2` package.

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
:lgtm:

> Reviewed 78 of 78 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/591#-:-MOJVJHM1-qZkclW8UxI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnLCaron)

**Comment by lesserwhirls** [comment]
Thanks @JohnLCaron!

**Pull request merged**
