### PR TITLE
Remove references to ucar.nc2.grid.

### PR DESCRIPTION
**Pull request by JohnLCaron**
First pass port Gcdm (not finished).

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/767)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 114 of 114 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/767)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnLCaron)

___
*[cdm-core/src/main/java/ucar/nc2/dataset/DatasetUrl.java, line 28 at r1](https://reviewable.io/reviews/unidata/netcdf-java/767#-MezPVIF-UIQTUg4GTBd:-MezKyeUAa5gW1t79Jza:b3y4n3d) ([raw file](https://github.com/unidata/netcdf-java/blob/63b17cb0c8a2eea50d98cd88aa318f55b11c2375/cdm-core/src/main/java/ucar/nc2/dataset/DatasetUrl.java#L28)):*
> ```Java
>  *
>  * @see "DatasetUrls.md"
>  *      LOOK should this be deprecated? its quite a mess.
> ```

I'll open a discussion on this one.

**Review by lesserwhirls — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/767)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnLCaron)

**Comment by lesserwhirls** [comment]
> > Reviewed 114 of 114 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/767)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnLCaron)
> 
> _[cdm-core/src/main/java/ucar/nc2/dataset/DatasetUrl.java, line 28 at r1](https://reviewable.io/reviews/unidata/netcdf-java/767#-MezPVIF-UIQTUg4GTBd:-MezKyeUAa5gW1t79Jza:b3y4n3d) ([raw file](https://github.com/unidata/netcdf-java/blob/63b17cb0c8a2eea50d98cd88aa318f55b11c2375/cdm-core/src/main/java/ucar/nc2/dataset/DatasetUrl.java#L28)):_
> 
> > ```java
> >  *
> >  * @see "DatasetUrls.md"
> >  *      LOOK should this be deprecated? its quite a mess.
> > ```
> 
> I'll open a discussion on this one.

Discussion here: https://github.com/Unidata/netcdf-java/discussions/769

**Pull request merged**
