### PR TITLE
Fix jenkins2

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/476)

### CODE REVIEW

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/476)* status: 17 of 21 files reviewed, 1 unresolved discussion (waiting on @JohnLCaron and @lesserwhirls)

___
*[cdmr/src/test/java/ucar/cdmr/client/TestCdmrNetcdf4.java, line 27 at r2](https://reviewable.io/reviews/unidata/netcdf-java/476#-MGxugMo8N0kfml1tsDt:-MGxugMo8N0kfml1tsDu:b95rqwv) ([raw file](https://github.com/unidata/netcdf-java/blob/67278a24e3daf1d1201e430819b100c4e9ca82f6/cdmr/src/test/java/ucar/cdmr/client/TestCdmrNetcdf4.java#L27)):*
> ```Java
> /** Test {@link CdmrNetcdfFile} */
> @RunWith(Parameterized.class)
> @Category({NotJenkins.class, NeedsCdmUnitTest.class}) // Needs CmdrServer to be started up
> ```

You'll want to keep `NeedsExternalResource.class` to keep these tests from running on Github Actions.

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 4 of 5 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/476)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lesserwhirls — APPROVED** [review]
I think all this one needs is a rebase and it will be good to go. Thanks @johnlcaron!

> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/476#-:-MGyy1yCArmvSFq3mEZG:bjqpnqk)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by JohnLCaron** [comment]
ready

**Comment by JohnLCaron** [comment]
would like to get this one in to clear jenkins errors

**Pull request merged**
