### PR TITLE
HDF5 iosp with builders

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/155)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
done.

Note that HdfEos support with HDF5 is not finished.

**Comment by JohnLCaron** [comment]
Note that String.format() uses the %s form, not the {}.

          log.warn(String.format("adjustDimensions %s missing vinfo (new)%n", v.shortName));

No particular reason to prefer over 

  log.warn("adjustDimensions {} missing vinfo (new)", v.shortName);

except that sometimes I like to do printf directly to stdout when debugging. 

Its too bad slf4j didnt use the standard java idiom. I prefer flogger as a logging package, "fluent logging" API. But only works with java.util.logging for the "backend".

**Comment by rschmunk** [comment]
Whoops, @JohnLCaron, sorry about that. Somehow I stared at that bit of code and never noticed the `String.format`.

**Comment by lesserwhirls** [comment]
Flogger looks really cool, and the [Anatomy of a logging API](https://google.github.io/flogger/anatomy) document is an interesting read. Thanks @JohnLCaron !

**Pull request merged**
