### PR TITLE
Use netcdf datasets

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/241)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Comment by lesserwhirls** [comment]
Would you mind rebasing? That will cut down on the number of files to review :-)

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 92 of 92 files at r1, 25 of 25 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/241)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Thank you @JohnLCaron!

**Pull request merged**
