### PR TITLE
Upgrade to Gradle 6.7, other build tweaks

### PR DESCRIPTION
**Pull request by lesserwhirls**
* Upgrade to gradle 6.7.
* Configure dependency checker to fail build if vulnerabilities are found.
* Fix `cdm-test` gradle config to make the relationship between `testIndexCreation` and `test` work smoothly with IntelliJ
* Add Adoptium 15 to the test matrix in place of Adoptium 14.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/550)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Although gradle 6.7 adds support for Java 15, [jacoco does not support Java 15 yet](https://github.com/gradle/gradle/issues/15038#issuecomment-719428344), so need to move the test matrix back to Adoptium 14.

**Comment by lesserwhirls** [comment]
I'll rebase this one after Unidata/netcdf-java#548 goes in.

**Comment by haileyajohnson** [comment]
548 is in =)

**Review by haileyajohnson — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/550)* status: all files reviewed, 1 unresolved discussion (waiting on @lesserwhirls)

___
*[cdm-test/src/test/java/ucar/nc2/grib/TestGribIndexCreation.java, line 418 at r2](https://reviewable.io/reviews/unidata/netcdf-java/550#-MLhyGPKC6wzEY6ykEQU:-MLhyGPKC6wzEY6ykEQV:bc52tdo) ([raw file](https://github.com/unidata/netcdf-java/blob/bbab117f203016a83433455db96dc693e9a86ffd/cdm-test/src/test/java/ucar/nc2/grib/TestGribIndexCreation.java#L418)):*
> ```Java
> 
>   @Test
>   public void makeGradleHappy() {
> ```

:laughing:

**Pull request merged**
