### PR TITLE
HdfEos dimension conflicts

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/162)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Issue #149

**Comment by JohnLCaron** [comment]
https://artifacts.unidata.ucar.edu/repository/unidata-releases/org/bounce/bounce/0.18/bounce-0.18.pom

artifacts is down??

**Comment by dopplershift** [comment]
I can get to https://artifacts.unidata.ucar.edu just fine, but not to that URL...

**Comment by lesserwhirls** [comment]
The issue isn't that the bounce does not exist (that's just gradle checking the repos for the artifact - it actually lives in our 3rd party repo), the issue is that gradle cannot do a HEAD request due to not being able to understand our certificate. This is the key error is:

~~~java
Caused by: java.lang.RuntimeException: Could not generate DH keypair
	... 182 more
Caused by: java.security.InvalidAlgorithmParameterException: DH key size must be multiple of 64, and can only range from 512 to 2048 (inclusive). The specific key size 4096 is not supported
~~~

@oxelson - did we recently change the cert on artifacts? This error was generated from Oracle JDK 1.8 u151 as used on the Travis CI service, and we see similar issues on Jenkins. It looks like java 8 only support 2048 for Diffie-Hellman. Java 9 would give us 3072, 4096, 6144, 8192.

There is a [reported work around](https://stackoverflow.com/questions/6851461/why-does-ssl-handshake-give-could-not-generate-dh-keypair-exception/29176597#29176597), but man...

imma head out

**Comment by oxelson** [comment]
@lesserwhirls yes, we modified our ciphers to be compatible with TLS 1.3.  Unfortunately, it looks like the Sonatype Nexus Repository Manager currently doesn't support OpenJDK versions greater than version 8 (https://issues.sonatype.org/browse/NEXUS-19183).

I can back us out of TLS 1.3 on that server for now, but it needs to be considered a temporary fix.  I'll also add our voice to the chorus on the Sonatype issue tracker for support of OpenJDK 11.

**Comment by oxelson** [comment]
@lesserwhirls, @JohnLCaron  TLS1.3 has been disabled.

**Comment by lesserwhirls** [comment]
Thanks Jen! I'm surprised this is an issue related to java on the server side, but I totally believe it. The message above was from a client-side stacktrace, as in it was the JVM client-side that didn't understand what to do with 4096 bit DH cert it was handed by the server. I was able to get to the server through my browser, and the browser showed it was using the 4096 bit DH cert, so I assume it was all a client-side issue.

Now that we can grab artifacts and build, we're seeing the same thing in our tests when they try to hit thredds-dev, for example:

https://travis-ci.com/Unidata/netcdf-java/jobs/263696653#L16900-L16952

**Comment by oxelson** [comment]
Yeah, it's a client issue and we're running into it all over the place.  :-(   I enabled all of our servers to use TLS 1.3.  I'll roll back thredds-dev and thedds-test.  Do I need to do so for thredds.ucar.edu?

**Comment by lesserwhirls** [comment]
That would be great if you could with the total understand on my end that it's temporary. AdoptOpenJDK/openjdk-build#1254 looks promising. Azul JREs/JDKs have it now (I wonder if nexus could run under Azul's [Zulu Community JDK](https://www.azul.com/downloads/zulu-community/?&architecture=x86-64-bit&package=jdk)). Oracle plans on adding TLS 1.3 support to their JRE/JDK 8 [sometime in 2020](https://java.com/en/jre-jdk-cryptoroadmap.html).

Maybe there is some hope for Java 8 (although we need to, and will move ourselves), specifically for others who are "stuck" on 8 but can still use the latest Java 8.

**Comment by oxelson** [comment]
giphy



Okay, TLS 1.3 has been disabled for the thredds-dev, thredds-test and thredds hosts.  


With modern browsers to stop supporting ciphers < TLS 1.2 next year, I suspect (hope) we're going to see a scramble to adopt clients that support TLS 1.3 ciphers (including java).

**Comment by lesserwhirls** [comment]
Ok, we're green on this one now - merging! Thanks @JohnLCaron!

**Pull request merged**
