### PR TITLE
Upgrade to latest theme and minor tweaks

### PR DESCRIPTION
**Pull request by lesserwhirls**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/691)

### CODE REVIEW

**Review by haileyajohnson — APPROVED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/691)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lesserwhirls)

**Comment by lesserwhirls** [comment]
Oops...one more thing to change up on this one.

**Comment by lesserwhirls** [comment]
Ok, this should be ready @haileyajohnson

**Review by haileyajohnson — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/691)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lesserwhirls)

**Pull request merged**
