### PR TITLE
Remote access to Grids.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/580)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Comment by lesserwhirls** [comment]
This one now shows conflict after merging Unidata/netcdf-java#578 - a quick rebase might do the trick?

**Comment by JohnLCaron** [comment]
This one had some difficult merges, and Ive managed to hose up the next PR because of it, and Im stuck until I can get this one in. So as soon as this passes, can you get it in so I can unravel the mess? thanks

**Comment by JohnLCaron** [comment]
Ready!

**Pull request merged**
