### PR TITLE
Refactor FileWriter, add new nc3 writing (pass 1)

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/239)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
2020-03-28T20:28:32.7867736Z E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/h/hdf5/hdf5-helpers_1.10.0-patch1+docs-4_amd64.deb  Could not connect to azure.archive.ubuntu.com:80 (52.177.174.250), connection timed out
...

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
> Reviewed 35 of 35 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/239)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnLCaron)

___
*[cdm/core/src/main/java/ucar/nc2/write/Nccopy.java, line 123 at r2](https://reviewable.io/reviews/unidata/netcdf-java/239#-M3cjJwW7M1kOYtvKTsl:-M3cjJwXB7NqlsqYulaz:bcstkp3) ([raw file](https://github.com/unidata/netcdf-java/blob/7173d019ed6b6bcbdab790979f974ddda0ba4dc9/cdm/core/src/main/java/ucar/nc2/write/Nccopy.java#L123)):*
> ```Java
>           result = NetcdfFileFormat.NETCDF4_CLASSIC;
>           break;
>         case "netcdf3c":
> ```

Should this be documented in the `outformat` parameter? Then again, do we need this as an option since the user can set the `useJni` option?
___
*[cdm/core/src/main/java/ucar/nc2/write/NetcdfFileFormat.java, line 125 at r1](https://reviewable.io/reviews/unidata/netcdf-java/239#-M3cf6pU40xqxUzTliGg:-M3cf6pU40xqxUzTliGh:b-unm2qp) ([raw file](https://github.com/unidata/netcdf-java/blob/8f8df372bf0e1e571c7ab941f4d3fca1bea79127/cdm/core/src/main/java/ucar/nc2/write/NetcdfFileFormat.java#L125)):*
> ```Java
>   NETCDF4(3, "netcdf-4"), // This is really just HDF-5, dont know yet if its written by netcdf4.
>   NETCDF4_CLASSIC(4, "netcdf-4 classic"), // psuedo format I think
>   NETCDF3_64BIT_DATA(5, "netcdf-5"), // what is this ?
> ```

CDF5 came out of the PnetCDF project. It was officially added to netCDF-C in 2016. For a long time I thought the support was read only, but that's not the case - the netCDF-C library will also write to it, and is now considered an official netCDF format. No one mentioned it at the time. It just sort of showed up. I'm pushing to make extensions to netCDF more formal to prevent things like this from just dropping out of nowhere...
___
*[cdm/core/src/main/java/ucar/nc2/write/NetcdfFileFormat.java, line 127 at r1](https://reviewable.io/reviews/unidata/netcdf-java/239#-M3cgXnfA2uyiIpdvGDV:-M3cgXng25_LSmnsVFVC:b-edu7a8) ([raw file](https://github.com/unidata/netcdf-java/blob/8f8df372bf0e1e571c7ab941f4d3fca1bea79127/cdm/core/src/main/java/ucar/nc2/write/NetcdfFileFormat.java#L127)):*
> ```Java
>   NETCDF3_64BIT_DATA(5, "netcdf-5"), // what is this ?
> 
>   NCSTREAM(42, "ncstream"); // No assigned version, not part of C library. Does this belong here?
> ```

That's a good question. If the C library is the sole arbitrator of truth, then probably not. I don't think that is, or should be, the case. I'm ok keeping this here for now.

**Comment by lesserwhirls** [comment]
> 2020-03-28T20:28:32.7867736Z E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/h/hdf5/hdf5-helpers_1.10.0-patch1+docs-4_amd64.deb Could not connect to azure.archive.ubuntu.com:80 (52.177.174.250), connection timed out
> ...

I'm going to change the way we get netCDF-C to avoid this kind of issue in the future. Did you check the action page to see if you were able to see the [re-run option](https://github.com/Unidata/netcdf-java/pull/236#issuecomment-603821265)

**Comment by lesserwhirls** [comment]
One more thing that popped into my head as I looked over this PR. We often refer to JNI in documentation, package names, etc., but wouldn't it be more appropriate to say JNA since that's what we are using now?

**Comment by JohnLCaron** [comment]
> > Reviewed 35 of 35 files at r1, 4 of 4 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/239)_ status: all files reviewed, 3 unresolved discussions (waiting on @JohnLCaron)
> 
> _[cdm/core/src/main/java/ucar/nc2/write/Nccopy.java, line 123 at r2](https://reviewable.io/reviews/unidata/netcdf-java/239#-M3cjJwW7M1kOYtvKTsl:-M3cjJwXB7NqlsqYulaz:bcstkp3) ([raw file](https://github.com/unidata/netcdf-java/blob/7173d019ed6b6bcbdab790979f974ddda0ba4dc9/cdm/core/src/main/java/ucar/nc2/write/Nccopy.java#L123)):_
> 
> > ```java
> >           result = NetcdfFileFormat.NETCDF4_CLASSIC;
> >           break;
> >         case "netcdf3c":
> > ```
> 
> Should this be documented in the `outformat` parameter? Then again, do we need this as an option since the user can set the `useJni` option?

The old --format is deprecated, this code just maps the old to the new; I suppose for backwards compatibilty we could have it set useJni = true.  But Nccopy is new and doesnt need to be backwards compatible. So maybe better to not even have --format anymore? Will do that unless you have better idea.

> 
> _[cdm/core/src/main/java/ucar/nc2/write/NetcdfFileFormat.java, line 125 at r1](https://reviewable.io/reviews/unidata/netcdf-java/239#-M3cf6pU40xqxUzTliGg:-M3cf6pU40xqxUzTliGh:b-unm2qp) ([raw file](https://github.com/unidata/netcdf-java/blob/8f8df372bf0e1e571c7ab941f4d3fca1bea79127/cdm/core/src/main/java/ucar/nc2/write/NetcdfFileFormat.java#L125)):_
> 
> > ```java
> >   NETCDF4(3, "netcdf-4"), // This is really just HDF-5, dont know yet if its written by netcdf4.
> >   NETCDF4_CLASSIC(4, "netcdf-4 classic"), // psuedo format I think
> >   NETCDF3_64BIT_DATA(5, "netcdf-5"), // what is this ?
> > ```
> 
> CDF5 came out of the PnetCDF project. It was officially added to netCDF-C in 2016. For a long time I thought the support was read only, but that's not the case - the netCDF-C library will also write to it, and is now considered an official netCDF format. No one mentioned it at the time. It just sort of showed up. I'm pushing to make extensions to netCDF more formal to prevent things like this from just dropping out of nowhere...

ok

> 
> _[cdm/core/src/main/java/ucar/nc2/write/NetcdfFileFormat.java, line 127 at r1](https://reviewable.io/reviews/unidata/netcdf-java/239#-M3cgXnfA2uyiIpdvGDV:-M3cgXng25_LSmnsVFVC:b-edu7a8) ([raw file](https://github.com/unidata/netcdf-java/blob/8f8df372bf0e1e571c7ab941f4d3fca1bea79127/cdm/core/src/main/java/ucar/nc2/write/NetcdfFileFormat.java#L127)):_
> 
> > ```java
> >   NETCDF3_64BIT_DATA(5, "netcdf-5"), // what is this ?
> > 
> >   NCSTREAM(42, "ncstream"); // No assigned version, not part of C library. Does this belong here?
> > ```
> 
> That's a good question. If the C library is the sole arbitrator of truth, then probably not. I don't think that is, or should be, the case. I'm ok keeping this here for now.

ok

**Comment by JohnLCaron** [comment]
> > 2020-03-28T20:28:32.7867736Z E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/h/hdf5/hdf5-helpers_1.10.0-patch1+docs-4_amd64.deb Could not connect to azure.archive.ubuntu.com:80 (52.177.174.250), connection timed out
> > ...
> 
> I'm going to change the way we get netCDF-C to avoid this kind of issue in the future. Did you check the action page to see if you were able to see the [re-run option](https://github.com/Unidata/netcdf-java/pull/236#issuecomment-603821265)

Sorry, I didnt notice. Ill check next time.

**Comment by JohnLCaron** [comment]
> One more thing that popped into my head as I looked over this PR. We often refer to JNI in documentation, package names, etc., but wouldn't it be more appropriate to say JNA since that's what we are using now?

Yes, you're right. I changed to JNA in this PR. Can migrate as we run across other examples.

**Comment by JohnLCaron** [comment]
> The old --format is deprecated, this code just maps the old to the new; I suppose for backwards compatibilty we could have it set useJni = true. But Nccopy is new and doesnt need to be backwards compatible. So maybe better to not even have --format anymore? Will do that unless you have better idea.

Sorry, Nccopy is not new, so should be backwards compatible here. Will probably remove --format in version 6.

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
Looks good to me - Thanks @johnlcaron!

> Reviewed 2 of 3 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/239#-:-M3hSPg98a10ld1Fj-3Z:bjaa3tq)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
