### PR TITLE
SequenceDS

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/262)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Thanks @JohnLCaron!

**Comment by lesserwhirls** [comment]
Sorry for the delay - would you mind rebasing this PR?

**Comment by lesserwhirls** [comment]
Thanks @JohnLCaron - looks good to me. I still have a hard time following the various unbounded wildcards in the generics, but I think it will just take me some time to get used to. I think it will be helpful to see how any of those show up in the public API.

**Comment by JohnLCaron** [comment]
When you figure out unbounded wildcards, explain them to me. ;^(

**Pull request merged**
