### PR TITLE
Add tests for Grid.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/578)

### CODE REVIEW

**Review by lesserwhirls — APPROVED** [review]
Looks good to me. If this is ready, I'll go ahead and merge it in. Thanks @johnlcaron!

> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/578#-:-MNeg8a980zx86iEZW26:b-pv6l0j)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnLCaron)

**Comment by lesserwhirls** [comment]
I think this just needs a rebase and we'll be good.

**Comment by JohnLCaron** [comment]
ready

**Comment by JohnLCaron** [comment]
ready

**Comment by lesserwhirls** [comment]
Thanks @JohnLCaron!

**Pull request merged**
