### PR TITLE
Create pull request template and update issue templates

### LINKED ISSUE #747: Pls include major version  number in issues/pull requests
It's getting a bit tough out here for us following aged repo feeds to figure out what the latest commits affect and how much we should pay attention to them.

It seems the development branch is now 7.0 (?), but then there's still 6.0, and of course the 5.4 maintenance branch. At least the the 5.x backports usually say so in their titles.

It would help if coders posting issues and/or pull requests would preface the titles with the major version number of the NJ that they are hitting on.

### PR DESCRIPTION
**Pull request by lesserwhirls**
Addresses Unidata/netcdf-java#747 using GitHub Templates.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/755)

### CODE REVIEW

**Comment by dopplershift** [comment]
I'm really interested to see what this form ends up looking like...

**Comment by lesserwhirls** [comment]
I tested it out on my fork and passed it by @haileyajohnson first, just to be sure. There were a lot of trial and error bumps along the way, and this PR squashed all of those into something that looks like I know what I'm doing. Git magic! 🧙‍♂️

**Review by haileyajohnson — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/755)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dopplershift)

**Review by dopplershift — APPROVED** [review]

**Comment by rschmunk** [comment]
Thx, @lesserwhirls.

**Pull request merged**
