### PR TITLE
Updated Grid Datasets user guide page

### PR DESCRIPTION
**Pull request by irpfander**
Code snippets were updated in the GridDatasetsTutorial class and tested in the TestGridDatasetsTutorial class. Changes were made to the writing and updated images were added to GridDatasets.md.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/689)

### CODE REVIEW

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
I think this is a great chunk of work to get into the codebase (just a few URL tweaks for now). w00t! @haileyajohnson, what do you think?

> Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/689#-:-MbBm7d--5dRBOc0vbhH:b29jmm5)* status: all files reviewed, 2 unresolved discussions (waiting on @irpfander)

___
*[docs/userguide/src/site/images/featuretypes/GridStructure.png, line 0 at r2](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbBh84A0kDl7FsBfmGZ:-MbBh84A0kDl7FsBfmG_:bopk1f9) ([raw file](https://github.com/unidata/netcdf-java/blob/440225faab30d205d9c75b15ec8945135fcef05f/docs/userguide/src/site/images/featuretypes/GridStructure.png#L0)):*
I'm curious - what tool did you use to produce this diagram?
___
*[docs/userguide/src/site/pages/featuretypes/GridDatasets.md, line 16 at r2](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbBjBeQ5KJ2fJZPjwZI:-MbBjBeQ5KJ2fJZPjwZJ:b-sssrj9) ([raw file](https://github.com/unidata/netcdf-java/blob/440225faab30d205d9c75b15ec8945135fcef05f/docs/userguide/src/site/pages/featuretypes/GridDatasets.md#L16)):*
> ```
> https://www.unidata.ucar.edu/software/netcdf-java/v4.6/reference/FeatureDatasets/Overview.html
> ```

I would use https://docs.unidata.ucar.edu/netcdf-java/current/userguide/feature_datasets.html for the URL. I would also add a line that the Scientific Feature Type interface is undergoing a lot of change, so it's best to treat the overview as a conceptual goal more than documentation.
___
*[docs/userguide/src/site/pages/featuretypes/GridDatasets.md, line 30 at r2](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbBkwxD3elYboIcI-Nf:-MbBkwxD3elYboIcI-Ng:bb3ddqp) ([raw file](https://github.com/unidata/netcdf-java/blob/440225faab30d205d9c75b15ec8945135fcef05f/docs/userguide/src/site/pages/featuretypes/GridDatasets.md#L30)):*
> ```Markdown
> 
> 
> The most general way to open a `GridDataset` is to use the `FeatureDatasetFactoryManager` class. This allows third parties to plug-in alternative implementations of `GridDataset` at runtime. The `wantFeatureType` parameter is checked, logging an error if incompatible. For example:
> ```

I don't think `FeatureDatasetFactoryManager` ties into `ucar.nc2.grid.GridDatasetFactory`, but rather `ucar.nc2.dt.grid.GridDataset`. But, a lot of this is in flux, so that's ok for now.  I'll add this to my list of "needs to be revisited when the dust settles".
___
*[docs/userguide/src/site/pages/featuretypes/GridDatasets.md, line 94 at r2](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbBmLeb2sh5iYMnpIJ2:-MbBmLeb2sh5iYMnpIJ3:b-my5mds) ([raw file](https://github.com/unidata/netcdf-java/blob/440225faab30d205d9c75b15ec8945135fcef05f/docs/userguide/src/site/pages/featuretypes/GridDatasets.md#L94)):*
> ```
> [Writing CDM](https://www.unidata.ucar.edu/software/netcdf-java/v4.6/reference/FeatureDatasets/Overview.html){:target="_blank"}
> ```

I think we want to use`[Writing CDM](writing_netcdf.html)` here.

**Review by irpfander — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/689)* status: all files reviewed, 2 unresolved discussions (waiting on @irpfander)

___
*[docs/userguide/src/site/images/featuretypes/GridStructure.png, line  at r2](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbBh84A0kDl7FsBfmGZ:-MbCqVxuDAT2-i-9gC88:b-isgyt0) ([raw file](https://github.com/unidata/netcdf-java/blob/440225faab30d205d9c75b15ec8945135fcef05f/docs/userguide/src/site/images/featuretypes/GridStructure.png#L)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

I'm curious - what tool did you use to produce this diagram?
</blockquote></details>

I made it on Google slides! I took inspiration from the old diagram and added/deleted classes as needed.

**Review by haileyajohnson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/689)* status: 6 of 8 files reviewed, 7 unresolved discussions (waiting on @irpfander and @lesserwhirls)

___
*[docs/userguide/src/site/pages/featuretypes/GridDatasets.md, line 16 at r2](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbBjBeQ5KJ2fJZPjwZI:-MbCNy3f3VZd_E4_x2Lp:b-wn0r8n) ([raw file](https://github.com/unidata/netcdf-java/blob/440225faab30d205d9c75b15ec8945135fcef05f/docs/userguide/src/site/pages/featuretypes/GridDatasets.md#L16)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

> ```
> https://www.unidata.ucar.edu/software/netcdf-java/v4.6/reference/FeatureDatasets/Overview.html
> ```

I would use https://docs.unidata.ucar.edu/netcdf-java/current/userguide/feature_datasets.html for the URL. I would also add a line that the Scientific Feature Type interface is undergoing a lot of change, so it's best to treat the overview as a conceptual goal more than documentation.
</blockquote></details>

Would it not just be [Scientific Feature types](feature_datasets.html)?

Similarly, I think it shouldn't have the {:target="_blank"} tag, since we've generally been opening in current tab for links within the current docset and opening in a different tab for external links or links to other docsets.
___
*[docs/userguide/src/site/pages/featuretypes/GridDatasets.md, line 94 at r2](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbBmLeb2sh5iYMnpIJ2:-MbDI7c2C-qpgiufKoEs:b-y1pedb) ([raw file](https://github.com/unidata/netcdf-java/blob/440225faab30d205d9c75b15ec8945135fcef05f/docs/userguide/src/site/pages/featuretypes/GridDatasets.md#L94)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

> ```
> [Writing CDM](https://www.unidata.ucar.edu/software/netcdf-java/v4.6/reference/FeatureDatasets/Overview.html){:target="_blank"}
> ```

I think we want to use`[Writing CDM](writing_netcdf.html)` here.
</blockquote></details>

And again, no target=blank
___
*[docs/userguide/src/site/pages/featuretypes/GridDatasets.md, line 11 at r3](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbDc_lY5GtmbjMw98GE:-MbDc_lY5GtmbjMw98GF:b4ma8q1) ([raw file](https://github.com/unidata/netcdf-java/blob/f48f1d623a6d35d65065f17d410baae272877f19/docs/userguide/src/site/pages/featuretypes/GridDatasets.md#L11)):*
> ```Markdown
> 
> ### Scientific Feature Types
> The Common Data Model (CDM) Scientific Feature Type layer adds another layer of functionality on top of NetcdfDataset, by specializing in various kinds of data that are common in earth science. The abstract concepts and concrete classes are continually evolving, and we have concentrated on, for obvious reasons, the types of datasets and data that Unidata is most familiar with, mainly from the atmospheric and ocean sciences.
> ```

This `NetcdfDataset` is missing code tags
___
*[docs/userguide/src/site/pages/featuretypes/GridDatasets.md, line 18 at r3](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbDcumD9S-klu_VWZI3:-MbDcumD9S-klu_VWZI4:bqxwd86) ([raw file](https://github.com/unidata/netcdf-java/blob/f48f1d623a6d35d65065f17d410baae272877f19/docs/userguide/src/site/pages/featuretypes/GridDatasets.md#L18)):*
> ```Markdown
> [Scientific Feature Types.](https://docs.unidata.ucar.edu/netcdf-java/current/userguide/feature_datasets.html ){:target="_blank"}
> 
> The Grid Feature Type
> ```

I think this is supposed to be a subheading
___
*[docs/userguide/src/site/pages/featuretypes/GridDatasets.md, line 19 at r3](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbDd3Cr4zjFLWFBd2ZK:-MbDd3Cr4zjFLWFBd2ZL:b1rf8jm) ([raw file](https://github.com/unidata/netcdf-java/blob/f48f1d623a6d35d65065f17d410baae272877f19/docs/userguide/src/site/pages/featuretypes/GridDatasets.md#L19)):*
> ```Markdown
> 
> The Grid Feature Type
> A Grid Coordinate System at a minimum has a Lat and Lon coordinate axis, or a GeoX and GeoY coordinate axis plus a Projection that maps x, y to lat, lon. It usually has a time coordinate axis. It may optionally have a vertical coordinate axis, classified as Height, Pressure, or GeoZ. If it is a GeoZ axis, it may have a Vertical Transform that maps GeoZ to height or pressure. A Grid may also optionally have a Runtime and/or Ensemble coordinate axis.
> ```

There's a lot of squishy terms in here that could either be in code tags or not, e.g. Project, Grid... I think a good rule of thumb is it should either be capitalized as one word and in code blocks, or lower case. So Height, Pressure, and GeoZ can either be general or explicitly referencing a property, but not just hanging around in caps. Same with Runtime and Ensemble. I think I'd lean towards code tags for them, but it's a bit of a gray area...
___
*[docs/userguide/src/test/java/examples/featuretypes/GridDatasetsTutorial.java, line 71 at r3](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbDeJVM9R0wBMM7rjUp:-MbDeJVM9R0wBMM7rjUq:bqub560) ([raw file](https://github.com/unidata/netcdf-java/blob/f48f1d623a6d35d65065f17d410baae272877f19/docs/userguide/src/test/java/examples/featuretypes/GridDatasetsTutorial.java#L71)):*
> ```Java
>         // puts entries from stringMap into a HashMap
>         GridSubset subset = new GridSubset( stringMap);
>     }
> ```

These look awesome =)
___
*[docs/userguide/src/test/java/tests/featuretypes/TestGridDatasetsTutorial.java, line 3 at r2](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbCQRQo-BMnOeTYIjzq:-MbCQRQpCcxRqjR8mCB2:be9e1kn) ([raw file](https://github.com/unidata/netcdf-java/blob/440225faab30d205d9c75b15ec8945135fcef05f/docs/userguide/src/test/java/tests/featuretypes/TestGridDatasetsTutorial.java#L3)):*
> ```Java
> package tests.featuretypes;
> 
> import examples.cdmdatasets.ReadingCdmTutorial;
> ```

Tests looks great! Only nitpick is a bunch of these imports aren't been used - in intellij, if you expand the list of imports, the ones that are kind of grated out aren't being used and can be deleted.

**Review by irpfander — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/689)* status: 6 of 8 files reviewed, 7 unresolved discussions (waiting on @haileyajohnson, @irpfander, and @lesserwhirls)

___
*[docs/userguide/src/site/pages/featuretypes/GridDatasets.md, line 16 at r2](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbBjBeQ5KJ2fJZPjwZI:-MbD-noMBRcB9zujmerp:b-896fix) ([raw file](https://github.com/unidata/netcdf-java/blob/440225faab30d205d9c75b15ec8945135fcef05f/docs/userguide/src/site/pages/featuretypes/GridDatasets.md#L16)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

Would it not just be [Scientific Feature types](feature_datasets.html)?

Similarly, I think it shouldn't have the {:target="_blank"} tag, since we've generally been opening in current tab for links within the current docset and opening in a different tab for external links or links to other docsets.
</blockquote></details>

Done.
___
*[docs/userguide/src/site/pages/featuretypes/GridDatasets.md, line 94 at r2](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbBmLeb2sh5iYMnpIJ2:-MbD-yu2-GuEMVYXHTjt:b-896fix) ([raw file](https://github.com/unidata/netcdf-java/blob/440225faab30d205d9c75b15ec8945135fcef05f/docs/userguide/src/site/pages/featuretypes/GridDatasets.md#L94)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

And again, no target=blank
</blockquote></details>

Done.
___
*[docs/userguide/src/site/pages/featuretypes/GridDatasets.md, line 11 at r3](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbDc_lY5GtmbjMw98GE:-MbDsXBZES6kC2NAmk94:b-896fix) ([raw file](https://github.com/unidata/netcdf-java/blob/f48f1d623a6d35d65065f17d410baae272877f19/docs/userguide/src/site/pages/featuretypes/GridDatasets.md#L11)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

This `NetcdfDataset` is missing code tags
</blockquote></details>

Done.
___
*[docs/userguide/src/site/pages/featuretypes/GridDatasets.md, line 18 at r3](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbDcumD9S-klu_VWZI3:-MbIVjDN0PcLuJ7IO735:b-896fix) ([raw file](https://github.com/unidata/netcdf-java/blob/f48f1d623a6d35d65065f17d410baae272877f19/docs/userguide/src/site/pages/featuretypes/GridDatasets.md#L18)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

I think this is supposed to be a subheading
</blockquote></details>

Done.
___
*[docs/userguide/src/site/pages/featuretypes/GridDatasets.md, line 19 at r3](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbDd3Cr4zjFLWFBd2ZK:-MbIWqmE4Cg6XE5Yn5-N:b-896fix) ([raw file](https://github.com/unidata/netcdf-java/blob/f48f1d623a6d35d65065f17d410baae272877f19/docs/userguide/src/site/pages/featuretypes/GridDatasets.md#L19)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

There's a lot of squishy terms in here that could either be in code tags or not, e.g. Project, Grid... I think a good rule of thumb is it should either be capitalized as one word and in code blocks, or lower case. So Height, Pressure, and GeoZ can either be general or explicitly referencing a property, but not just hanging around in caps. Same with Runtime and Ensemble. I think I'd lean towards code tags for them, but it's a bit of a gray area...
</blockquote></details>

Done.
___
*[docs/userguide/src/test/java/tests/featuretypes/TestGridDatasetsTutorial.java, line 3 at r2](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbCQRQo-BMnOeTYIjzq:-MbIYFbJAN7XvLCHvPSm:b-896fix) ([raw file](https://github.com/unidata/netcdf-java/blob/440225faab30d205d9c75b15ec8945135fcef05f/docs/userguide/src/test/java/tests/featuretypes/TestGridDatasetsTutorial.java#L3)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

Tests looks great! Only nitpick is a bunch of these imports aren't been used - in intellij, if you expand the list of imports, the ones that are kind of grated out aren't being used and can be deleted.
</blockquote></details>

Done.

**Review by irpfander — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/689)* status: 6 of 8 files reviewed, 7 unresolved discussions (waiting on @haileyajohnson and @lesserwhirls)

___
*[docs/userguide/src/test/java/examples/featuretypes/GridDatasetsTutorial.java, line 71 at r3](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbDeJVM9R0wBMM7rjUp:-MbI_rX-AmtqgQxgPtIA:b-896fix) ([raw file](https://github.com/unidata/netcdf-java/blob/f48f1d623a6d35d65065f17d410baae272877f19/docs/userguide/src/test/java/examples/featuretypes/GridDatasetsTutorial.java#L71)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

These look awesome =)
</blockquote></details>

Done.

**Review by haileyajohnson — APPROVED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/689)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @haileyajohnson and @lesserwhirls)

**Review by lesserwhirls — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/689#-:-MbIuj8iBCyrnW12ObhP:bb6ywmx)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @haileyajohnson and @lesserwhirls)

___
*[docs/userguide/src/site/images/featuretypes/GridStructure.png, line  at r2](https://reviewable.io/reviews/unidata/netcdf-java/689#-MbBh84A0kDl7FsBfmGZ:-MbIuMXS5SgCpwPVx4n3:b-qso05n) ([raw file](https://github.com/unidata/netcdf-java/blob/440225faab30d205d9c75b15ec8945135fcef05f/docs/userguide/src/site/images/featuretypes/GridStructure.png#L)):*
<details><summary><i>Previously, irpfander (Isabelle (Izzy) Pfander) wrote…</i></summary><blockquote>

I made it on Google slides! I took inspiration from the old diagram and added/deleted classes as needed. 
</blockquote></details>

Cool! Looks good to me. IntelliJ can generate diagrams like that, but it can be a little tricky to get it to show exactly what you want it to show.

**Pull request merged**
