### PR TITLE
AWIPS Conventions using builder

### PR DESCRIPTION
**Pull request by JohnLCaron**
Also a few minor unit tests fixups

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/197)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Ready to go

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 9 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/197)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @JohnLCaron and @lesserwhirls)

___
*[cdm/core/src/test/java/ucar/nc2/dataset/TestCoordSysCompareProblem.java, line 31 at r1](https://reviewable.io/reviews/unidata/netcdf-java/197#-M-FUV7G1lZ6CEw17Wmb:-M-FUV7G1lZ6CEw17Wmc:b-7hj7j5) ([raw file](https://github.com/unidata/netcdf-java/blob/ab5a3b9cdf9467042d6ef97b1e2575d509c8e609/cdm/core/src/test/java/ucar/nc2/dataset/TestCoordSysCompareProblem.java#L31)):*
> ```Java
>   @Test
>   public void compareProblemFile() throws IOException {
>     String filename = "/usr/local/google/home/jlcaron/Downloads/HistDumpTest9.nc";
> ```

I can put this in our test dataset collection (for Jenkins as well as available through thredds-test-data). Where should it live? Somewhere in TestDir.cdmUnitTestDir + "/formats/hdf5"?
___
*[cdm/core/src/test/java/ucar/nc2/dataset/conv/SearchForConventions.java, line 81 at r2](https://reviewable.io/reviews/unidata/netcdf-java/197#-M-FWvLn1fgbCrYxGovk:-M-FWvLn1fgbCrYxGovl:b-l6hbva) ([raw file](https://github.com/unidata/netcdf-java/blob/e845bca8d08bb62fdb53b64d3c503644c611efa8/cdm/core/src/test/java/ucar/nc2/dataset/conv/SearchForConventions.java#L81)):*
> ```Java
>   }
> 
>   // @Test
> ```

Rather than comment out, is it possible to use @Ignore("Not ready yet"), or something like that?

**Comment by JohnLCaron** [comment]
Would be good to put  HistDumpTest9.nc into conventions/default. That way TestCoordSysCompare will read the data and test it against the old H5iosp.
The next PR Im sending will change TestCoordSysCompareProblem, so I wouldnt worry about the test failure there.

**Comment by JohnLCaron** [comment]
SearchForConventions is really a utility, not a test. Not sure where we put those. I can move if you want, but would be convenient to do in a follow up PR (that Im about to send you).

**Comment by JohnLCaron** [comment]
Bit of a logjam. Checking to see if youre waiting for something from me.

**Comment by lesserwhirls** [comment]
Logjam all on my end - sorry about that.

**Pull request merged**
