### PR TITLE
Attributes are immutable

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/391)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Comment by lesserwhirls** [comment]
I think a rebase or merge on this one will do the trick, and will take care of Unidata/netcdf-java#390.

**Comment by JohnLCaron** [comment]
ready

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 98 of 98 files at r1, 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/391)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dopplershift)

**Pull request merged**
