### PR TITLE
SequenceDS inherits from Sequence.

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/402)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
unrelated failure?

> Task :httpservices:farmBeforeIntegrationTest FAILED
2020-08-01T17:57:10.8624468Z :httpservices:farmBeforeIntegrationTest (Thread[Execution worker for ':',5,main]) completed. Took 4.54 secs.
2020-08-01T17:57:10.8625047Z :rootTestReport (Thread[Execution worker for ':',5,main]) started.
2020-08-01T17:57:10.9616037Z 
2020-08-01T17:57:10.9616509Z FAILURE: Build failed with an exception.
2020-08-01T17:57:10.9616683Z 
2020-08-01T17:57:10.9617084Z * What went wrong:
2020-08-01T17:57:10.9617899Z Execution failed for task ':httpservices:farmBeforeIntegrationTest'.
2020-08-01T17:57:10.9618369Z > Could not resolve all dependencies for configuration ':httpservices:farm'.
2020-08-01T17:57:10.9618785Z    > Could not find edu.ucar:d4ts:5.0.0-SNAPSHOT.
2020-08-01T17:57:10.9619030Z      Searched in the following locations:
2020-08-01T17:57:10.9619462Z        - https://jcenter.bintray.com/edu/ucar/d4ts/5.0.0-SNAPSHOT/maven-metadata.xml
2020-08-01T17:57:10.9619939Z        - https://jcenter.bintray.com/edu/ucar/d4ts/5.0.0-SNAPSHOT/d4ts-5.0.0-SNAPSHOT.pom
2020-08-01T17:57:10.9620419Z        - https://repo.maven.apache.org/maven2/edu/ucar/d4ts/5.0.0-SNAPSHOT/maven-metadata.xml
2020-08-01T17:57:10.9620921Z        - https://repo.maven.apache.org/maven2/edu/ucar/d4ts/5.0.0-SNAPSHOT/d4ts-5.0.0-SNAPSHOT.pom
2020-08-01T17:57:10.9621431Z        - https://artifacts.unidata.ucar.edu/repository/unidata-releases/edu/ucar/d4ts/5.0.0-SNAPSHOT/maven-metadata.xml
2020-08-01T17:57:10.9621961Z        - https://artifacts.unidata.ucar.edu/repository/unidata-releases/edu/ucar/d4ts/5.0.0-SNAPSHOT/d4ts-5.0.0-SNAPSHOT.pom
2020-08-01T17:57:10.9622086Z 
2020-08-01T17:57:10.9622723Z        - https://artifacts.unidata.ucar.edu/repository/unidata-snapshots/edu/ucar/d4ts/5.0.0-SNAPSHOT/maven-metadata.xml
2020-08-01T17:57:10.9623251Z        - https://artifacts.unidata.ucar.edu/repository/unidata-snapshots/edu/ucar/d4ts/5.0.0-SNAPSHOT/d4ts-5.0.0-SNAPSHOT.pom
2020-08-01T17:57:10.9623544Z      Required by:
2020-08-01T17:57:10.9623750Z          project :httpservices
2020-08-01T17:57:10.9624121Z    > Could not find edu.ucar:dtswar:5.0.0-SNAPSHOT.
2020-08-01T17:57:10.9624359Z      Searched in the following locations:
2020-08-01T17:57:10.9624815Z        - https://jcenter.bintray.com/edu/ucar/dtswar/5.0.0-SNAPSHOT/maven-metadata.xml
2020-08-01T17:57:10.9625310Z        - https://jcenter.bintray.com/edu/ucar/dtswar/5.0.0-SNAPSHOT/dtswar-5.0.0-SNAPSHOT.pom
2020-08-01T17:57:10.9625797Z        - https://repo.maven.apache.org/maven2/edu/ucar/dtswar/5.0.0-SNAPSHOT/maven-metadata.xml
2020-08-01T17:57:10.9626495Z        - https://repo.maven.apache.org/maven2/edu/ucar/dtswar/5.0.0-SNAPSHOT/dtswar-5.0.0-SNAPSHOT.pom
2020-08-01T17:57:10.9627009Z        - https://artifacts.unidata.ucar.edu/repository/unidata-releases/edu/ucar/dtswar/5.0.0-SNAPSHOT/maven-metadata.xml
2020-08-01T17:57:10.9627532Z        - https://artifacts.unidata.ucar.edu/repository/unidata-releases/edu/ucar/dtswar/5.0.0-SNAPSHOT/dtswar-5.0.0-SNAPSHOT.pom
2020-08-01T17:57:10.9628388Z        - https://artifacts.unidata.ucar.edu/repository/unidata-snapshots/edu/ucar/dtswar/5.0.0-SNAPSHOT/maven-metadata.xml
2020-08-01T17:57:10.9628819Z        - https://artifacts.unidata.ucar.edu/repository/unidata-snapshots/edu/ucar/dtswar/5.0.0-SNAPSHOT/dtswar-5.0.0-SNAPSHOT.pom
2020-08-01T17:57:10.9629078Z      Required by:
2020-08-01T17:57:10.9629189Z          project :httpservices

**Comment by lesserwhirls** [comment]
Not quite - turns out gradle 6 does not play nice when publishing artifacts to nexus 3. PRs coming on that soon, but let me see if I can push out new artifacts from the TDS project with the fixes that I have in place.

**Comment by lesserwhirls** [comment]
yep

**Comment by lesserwhirls** [comment]
We should be back up and running now...

**Pull request merged**
