### PR TITLE
Remove coverage all

### PR DESCRIPTION
**Pull request by JohnLCaron**
Remove ft2.coverage, ft.remote, ft.point.remote.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/833)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Comment by JohnLCaron** [comment]
Error: The operation was canceled.
 ??

**Comment by JohnLCaron** [comment]
2021-09-16T03:23:59.0246673Z Failed to get resource: HEAD. [HTTP HTTP/1.1 502 Bad Gateway: https://jcenter.bintray.com/software/amazon/awssdk/arns/2.16.9/arns-2.16.9.pom)]

hmmm, i know jcenter is going away, maybe its getting flaky? 
May 1st, 2021 | Bintray services will no longer be available.

But i dont see jcenter in our gradle files...???

2021-09-16T03:18:00.5247763Z Resource missing. [HTTP GET: https://jcenter.bintray.com/com/diffplug/spotless/spotless-lib/2.1.0/spotless-lib-2.1.0.module]

spotless using jcenter ??

**Review by haileyajohnson — APPROVED** [review]
> Reviewed 96 of 96 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/833)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lesserwhirls)

**Comment by lesserwhirls** [comment]
> 2021-09-16T03:23:59.0246673Z Failed to get resource: HEAD. [HTTP HTTP/1.1 502 Bad Gateway: https://jcenter.bintray.com/software/amazon/awssdk/arns/2.16.9/arns-2.16.9.pom)]
> 
> hmmm, i know jcenter is going away, maybe its getting flaky?
> May 1st, 2021 | Bintray services will no longer be available.
> 
> But i dont see jcenter in our gradle files...???
> 
> 2021-09-16T03:18:00.5247763Z Resource missing. [HTTP GET: https://jcenter.bintray.com/com/diffplug/spotless/spotless-lib/2.1.0/spotless-lib-2.1.0.module]
> 
> spotless using jcenter ??

I wonder if an upstream dependency is adding jcenter as a repo, because yeah, we migrated everything away from jcenter awhile back. We should be grabbing spotless from the Gradle Plugin Portal [plugins.gradle.org](https://plugins.gradle.org/plugin/com.diffplug.gradle.spotless/4.5.1).

**Pull request merged**
