### PR TITLE
Iosp hdf4

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/147)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
some tweaks to CompareNetcdf2.ObjFilter causing compile errors in

**Comment by JohnLCaron** [comment]
ready for review

**Comment by lesserwhirls** [comment]
With exception of the "does this method need to be public" questions (and that's just to make sure they do need to be public, as they look like they were package private before), I'm happy to pick up any changes on another PR. I used Reviewable this time, so let's see how that goes.

**Comment by JohnLCaron** [comment]
ready i think

**Comment by lesserwhirls** [comment]
Thanks @JohnLCaron!

**Pull request merged**
