### PR TITLE
Collection management for AWS S3 compatible object stores

### PR DESCRIPTION
**Pull request by lesserwhirls**
This PR enables the fundamental capabilities needed to manage `MFile` collections on AWS S3 compatible object stores. Specifically:

1. Implement service provider interface for `MFile` and `MController`, and make sure `MFileCollectionManager`, `Aggregation`, and `AggregationOuter` use the `MFile` interface instead of concrete implementations.
2. Extend `CdmS3Uri` to include the concept of a delimiter for object keys that have a hierarchal structure (e.g. keys that use the path on disk from which objects were uploaded to the object store).
3. Cache and reuse `S3Client` objects.
4. Implement `MFile` for objects stored on object stores.
5. Implement an `MController` for object stores.

Finally, test NcML `JoinNew` aggregations for explicitly listed S3 objects, as well as using `scan` via the new `MController` for objects stores.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/542)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Jenkins looks good as well. This one should be ready for review.

**Review by haileyajohnson — APPROVED** [review]
Looks awesome!

> Reviewed 30 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/542#-:-MKpOYb_6YlHwCwvTO-6:b-k8r3ip)* status: all files reviewed, 3 unresolved discussions (waiting on @lesserwhirls)

___
*[cdm/core/src/main/java/ucar/nc2/internal/ncml/Aggregation.java, line 386 at r1](https://reviewable.io/reviews/unidata/netcdf-java/542#-MKl3aQKEnUle5CRSPIw:-MKl3aQKEnUle5CRSPIx:bvjrtlr) ([raw file](https://github.com/unidata/netcdf-java/blob/ff23a7746c39bde9db66cf718e40e01e96beac39/cdm/core/src/main/java/ucar/nc2/internal/ncml/Aggregation.java#L386)):*
> ```Java
>       AggDataset dataset = datasetsIter.next();
> 
>       if ((dataset.getMFile() != null) && (!dataset.getMFile().isReadable())) { // File.canRead() is broken on Windows,
> ```

I've usually been told not to call getters more than once for conditions+operations, i.e. 

if (dataset.getMFile() != null) { dataset.getMFile().getPath(); }

would be:

MFile mfile = datatset.getMFile();
if (mfile != null) { mfile.getPath(); }

I think nowadays it ends up being the same on most compilers, but I'm not sure :woman_shrugging: 
___
*[cdm/core/src/main/java/ucar/nc2/internal/ncml/AggregationOuter.java, line 665 at r1](https://reviewable.io/reviews/unidata/netcdf-java/542#-MKl4lRN8NUmGc-eSi-Y:-MKl4lRO2Hhj805GrJBI:bcgp7tb) ([raw file](https://github.com/unidata/netcdf-java/blob/ff23a7746c39bde9db66cf718e40e01e96beac39/cdm/core/src/main/java/ucar/nc2/internal/ncml/AggregationOuter.java#L665)):*
> ```Java
>       if ((type == Type.joinNew) && !(this instanceof PromoteVar)) {
>         return null; // ??
>       }
> ```

Should we be concerned about these question marks?
___
*[cdm/s3/src/main/java/thredds/inventory/s3/MFileS3.java, line 23 at r1](https://reviewable.io/reviews/unidata/netcdf-java/542#-MKlA2BIE3VsmtIhEmRg:-MKlA2BIE3VsmtIhEmRh:b-1cpisi) ([raw file](https://github.com/unidata/netcdf-java/blob/ff23a7746c39bde9db66cf718e40e01e96beac39/cdm/s3/src/main/java/thredds/inventory/s3/MFileS3.java#L23)):*
> ```Java
> import ucar.unidata.io.s3.CdmS3Uri;
> 
> /**
> ```

xzcd 
- comment courtesy of Hazel's paw slamming into my keyboard, thought I'd leave it in.

**Review by lesserwhirls — COMMENTED** [review]
I'm going to take a look at my the `PromoteVar` thing - likely one more commit coming to deal with that.

> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/542#-:-MKpwFpJ3C6TamCeDnUr:bmkc2dn)* status: all files reviewed, 3 unresolved discussions (waiting on @haileyajohnson)

___
*[cdm/core/src/main/java/ucar/nc2/internal/ncml/Aggregation.java, line 386 at r1](https://reviewable.io/reviews/unidata/netcdf-java/542#-MKl3aQKEnUle5CRSPIw:-MKpv7Iv02nkcaBLxHQo:b-896fix) ([raw file](https://github.com/unidata/netcdf-java/blob/ff23a7746c39bde9db66cf718e40e01e96beac39/cdm/core/src/main/java/ucar/nc2/internal/ncml/Aggregation.java#L386)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

I've usually been told not to call getters more than once for conditions+operations, i.e. 

if (dataset.getMFile() != null) { dataset.getMFile().getPath(); }

would be:

MFile mfile = datatset.getMFile();
if (mfile != null) { mfile.getPath(); }

I think nowadays it ends up being the same on most compilers, but I'm not sure :woman_shrugging: 
</blockquote></details>

Done.
___
*[cdm/core/src/main/java/ucar/nc2/internal/ncml/AggregationOuter.java, line 665 at r1](https://reviewable.io/reviews/unidata/netcdf-java/542#-MKl4lRN8NUmGc-eSi-Y:-MKpvKIW4FktD3_L-Ohf:bbufsbz) ([raw file](https://github.com/unidata/netcdf-java/blob/ff23a7746c39bde9db66cf718e40e01e96beac39/cdm/core/src/main/java/ucar/nc2/internal/ncml/AggregationOuter.java#L665)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

Should we be concerned about these question marks?
</blockquote></details>

I think so. I know adding the check to see if we were dealing with an instance of `PromoteVar` was needed for the case where NcML was being used to promote an attribute to a variable, but I ran into more problems with that kind of NcML and didn't go back now that everything else is working. I should take another look at that.
___
*[cdm/s3/src/main/java/thredds/inventory/s3/MFileS3.java, line 23 at r1](https://reviewable.io/reviews/unidata/netcdf-java/542#-MKlA2BIE3VsmtIhEmRg:-MKpvy9y-49R3dRCqbis:b-5hl1ce) ([raw file](https://github.com/unidata/netcdf-java/blob/ff23a7746c39bde9db66cf718e40e01e96beac39/cdm/s3/src/main/java/thredds/inventory/s3/MFileS3.java#L23)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

xzcd 
- comment courtesy of Hazel's paw slamming into my keyboard, thought I'd leave it in.
</blockquote></details>

Awesome! Pupper gives feedback on pull request. 13/10. Would pair pawgram any time.

**Review by lesserwhirls — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/542)* status: 24 of 39 files reviewed, 3 unresolved discussions (waiting on @haileyajohnson)

___
*[cdm/core/src/main/java/ucar/nc2/internal/ncml/AggregationOuter.java, line 665 at r1](https://reviewable.io/reviews/unidata/netcdf-java/542#-MKl4lRN8NUmGc-eSi-Y:-MKt4N-Q5XOuwJIUDynY:b-w7dtnq) ([raw file](https://github.com/unidata/netcdf-java/blob/ff23a7746c39bde9db66cf718e40e01e96beac39/cdm/core/src/main/java/ucar/nc2/internal/ncml/AggregationOuter.java#L665)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

I think so. I know adding the check to see if we were dealing with an instance of `PromoteVar` was needed for the case where NcML was being used to promote an attribute to a variable, but I ran into more problems with that kind of NcML and didn't go back now that everything else is working. I should take another look at that.
</blockquote></details>

So I've added a test that uses `PromoteVar`, but I think we keep the question marks as a hint that there might be other cases where returning early isn't the right thing to do. I can't think of any at the movement, but it could be helper when we're in the debugger.

**Review by haileyajohnson — APPROVED** [review]
> Reviewed 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/542)* status: all files reviewed, 3 unresolved discussions (waiting on @haileyajohnson)

**Comment by lesserwhirls** [comment]
If this looks good to you, would you like to merge it in? It will actually expose two new failures on Jenkins (so we'll have a total of 4), but Unidata/netcdf-java#545 will knock those out.

**Pull request merged**
