### PR TITLE
[5.x]fix link to ncml and remove link to developer's guide

### LINKED ISSUE #825: [5.x-7]: top nav links to developers guide and ncml doc sets are broken
### Versions impacted by the bug

v5.x, v6.x, v7.x

### What went wrong?

top nav links to developers guide and ncml doc sets 404

### Relevant stack trace

_No response_

### Relevant log messages

_No response_

### If you have an example file that you can share, please attach it to this issue.
If so, may we include it in our test datasets to help ensure the bug does not return once fixed?
Note: the test datasets are publicly accessible without restriction.

No

### Code of Conduct

- [X] I agree to follow the UCAR/Unidata Code of Conduct

### PR DESCRIPTION
**Pull request by haileyajohnson**
## Description of Changes

remove top nav link to developers guide (since it doesn't exist in 5.x)
fix link to ncml docset

## PR Checklist

- [ ] Indicate the version associated with this PR in the Title
       (e.g. "[5.x]: This is my PR title")
- [ ] Link to any issues that the PR addresses
- [ ] Add labels, especially if the PR should be ported to other versions
       (these labels start with "port: ")
- [ ] Open as a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/)
       until ready for review
- [ ] Make sure GitHub tests pass
- [ ] Mark PR as "Ready for Review"

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/827)

### CODE REVIEW

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/827)* status: all files reviewed, 1 unresolved discussion (waiting on @haileyajohnson)

___
*[docs/src/site/_data/topnav.yml, line 21 at r1](https://reviewable.io/reviews/unidata/netcdf-java/827#-MjeHQ6I7bvHxhEbeeJQ:-MjeHQ6I7bvHxhEbeeJR:boc9bja) ([raw file](https://github.com/unidata/netcdf-java/blob/2abd467e13a2ee83ca35b7ec18de8a8cfc1337ed/docs/src/site/_data/topnav.yml#L21)):*
> ```YAML
>             external_url: https://github.com/Unidata/netcdf-java
>           - title: User guide
>             external_url: https://docs.unidata.ucar.edu/netcdf-java/current/userguide/index.html
> ```

Did we want to make this link to `5.4` instead of current?

**Review by lesserwhirls — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/827)* status: all files reviewed, 2 unresolved discussions (waiting on @haileyajohnson)

___
*[docs/src/site/_data/topnav.yml, line 23 at r1](https://reviewable.io/reviews/unidata/netcdf-java/827#-MjeHoou49Y91UDA4sff:-MjeHoovBjGc9LakfVh9:b-a7sgin) ([raw file](https://github.com/unidata/netcdf-java/blob/2abd467e13a2ee83ca35b7ec18de8a8cfc1337ed/docs/src/site/_data/topnav.yml#L23)):*
> ```YAML
>             external_url: https://docs.unidata.ucar.edu/netcdf-java/current/userguide/index.html
>           - title: NcML
>             external_url: https://docs.unidata.ucar.edu/thredds/ncml/current/index.html
> ```

I guess we should consider if we should use 2.2 instead of current here, since that the the version of NcML supported by this version of the TDS?

**Comment by lesserwhirls** [comment]
Please forgive the comments if we decided yesterday to go with current on the 5.x branch...my brain is, yeah...

**Comment by haileyajohnson** [comment]
I thought we had said current for 5.x but....yeah I think these should be hardcoded too. brb...

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/827)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haileyajohnson)

**Pull request merged**
