### PR TITLE
Reverse deprecations in client.catalog classes.

### PR DESCRIPTION
**Pull request by JohnLCaron**
Revisit in version 6.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/310)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
I  assume since tests are working here that the previous failure is a flake. So then its ready....

**Comment by lesserwhirls** [comment]
...and now I see this one :-) Yeah, I think the test failure before is flaky, but not sure what's up. I'll just review this PR as one and close the other since it's picked up here.

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 15 of 15 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/310)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
LGTM 👍  Thank you @JohnLCaron!

**Pull request merged**
