### PR TITLE
Fix jenkins tests

### PR DESCRIPTION
**Pull request by JohnLCaron**
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/280)

### CODE REVIEW

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 66 of 66 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/280)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Thank you @JohnLCaron! I ended up reviewing this one, as it contained all of the commits from the previous two (that's why those were reviewed and merged in quick succession). Let me know when your ready for this one (although looks good to me as it stands).

**Comment by JohnLCaron** [comment]
ready

**Comment by JohnLCaron** [comment]
Had some more failures from previous PR. Ready again.

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/280)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Thanks @JohnLCaron !

**Pull request merged**
