### PR TITLE
Lost changes from PR comments on package.html files.

### PR DESCRIPTION
**Pull request by JohnLCaron**
pa

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/236)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Err:1 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 hdf5-helpers amd64 1.10.0-patch1+docs-4
2020-03-24T21:55:00.5686114Z   Could not connect to azure.archive.ubuntu.com:80 (52.177.174.250), connection timed out
2020-03-24T21:55:00.5696830Z Err:2 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libaec0 amd64 0.3.2-2
2020-03-24T21:55:00.5697218Z   Unable to connect to azure.archive.ubuntu.com:http:
...

**Comment by lesserwhirls** [comment]
I think it was an intermittent problem fetching ubuntu updates on azure. When you look at the actions page for a failed PR, do you see the option to "Re-run Jobs"?

gh

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/236)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lesserwhirls — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/236#-:-M3GkJRe69Uyh-QmRFo2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
The failures here are not related to this PR. They are all in `ucar.util.prefs.TestJavaUtilPreferences` (`testExport`, `testPutGet`, `testRemove`, `testRemoveNode`, `testSubnode`) all fail with:

```java
java.lang.AssertionError: Factory not set = java.util.prefs.FileSystemPreferences Property: ucar.util.prefs.PreferencesExtFactory
```

One thing I've noticed is that some of our test depend on the order in which they are executed, and the move to GitHub Actions has caused some of those to surface (not sure why though...different JDKs being used?). At any rate, this feels like it might be one of those cases (but I have not looked yet).

**Comment by JohnLCaron** [comment]
It look like the problem is that java.util.prefs.FileSystemPreference has already gotten set as the PreferencesFactory, the comment indicates that this might happen. So how can we set the System.property as the first thing before :uibase:test is run?

````
  // only works if System.setProperty called before anything else
  @Before
  public void testWho() {
    System.setProperty("java.util.prefs.PreferencesFactory", "ucar.util.prefs.PreferencesExtFactory");

    // this makes PreferencesExt the SPI
    Preferences userRoot = Preferences.userRoot();
    assert userRoot instanceof PreferencesExt : "Factory not set = " + userRoot.getClass().getName() + " Property: "
        + System.getProperty("java.util.prefs.PreferencesFactory");
  }
````

**Comment by lesserwhirls** [comment]
Ok, let's try this. In `uibase/build.gradle`,  can you add the following to the end of the file?

```gradle
test {
    // Tell java to use ucar.util.prefs.PreferencesExtFactory to generate preference objects
    // Important for ucar.util.prefs.TestJavaUtilPreferences
    systemProperty "java.util.prefs.PreferencesFactory", "ucar.util.prefs.PreferencesExtFactory"
}
```

**Comment by lesserwhirls** [comment]
Ok, that worked. I had to rerun the tds check manually, but it's all passing now. Travis failed fetching some artifacts, but that's fine, the others are good. Thanks @JohnLCaron, and sorry this took so long to get in.

**Pull request merged**
