### PR TITLE
CHANGE in the gcdm encoding protocol for USHORT. Fix gcdm test failures.

### PR DESCRIPTION
**Pull request by JohnLCaron**
Improvements to ArrayVlen.
Implement Opaque-valued Attributes.
Change Gcdm to use sint32 instead of uint32 for unsigned shorts. Otherwise, the protobug encoding blows up by 2x.

NOTE THIS IS A CHANGE in the gcdm encoding protocol, and other versions of library eg python must be updated. It should be backported.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/858)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Comment by JohnLCaron** [comment]
ready

**Review by haileyajohnson — APPROVED** [review]
> Reviewed 13 of 17 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/858)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnLCaron)

**Comment by dopplershift** [comment]
Attn: @rmcsqrd

**Pull request merged**
