### PR TITLE
NetcdfFiles and NetcdfDatasets handles both old and new iosps.

### PR DESCRIPTION
**Pull request by JohnLCaron**
Can access both old and new from NetcdfFiles and NetcdfDatasets.
This allows incremental upgrading of iosps

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/145)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
It looks like the TDS build is failing at the same spot (`Bearing`) as it was in the previous PR. Do you have the sense that there is more breakage for the TDS with this PR?

**Comment by JohnLCaron** [comment]
ill send a PR for TDS, then we can see.

**Comment by lesserwhirls** [comment]
The TDS tests pass now for this PR - w00t! Looks like just spotless now.

**Comment by JohnLCaron** [comment]
rock and roll

**Pull request merged**
