### PR TITLE
more deprecations and clarification of public API.

### PR DESCRIPTION
**Pull request by JohnLCaron**
use package.html to indicate if package is in the public API

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/234)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Why doesnt spotless love me, I love spotless? Ok I actually dont, Im getting to hate it. Could spotless just run automatically?

**Comment by JohnLCaron** [comment]
My spotless doesnt find any more errors. This is war.

**Comment by JohnLCaron** [comment]
Maybe we should stop using spotless check. Still a good idea to use it, but maybe not require it?

**Comment by lesserwhirls** [comment]
No idea what is happening there. The results from spotless on github actions and jenkins suggest that a space is needed between the two methods in `ThreddsMetadataContainer.java`, which is what you added in the second commit. It's almost like they didn't pickup the change when you added the new commit. They did run again, but seem to be missing out on the actual change.

We can certainly remove spotless as a required check. If it's a matter of things being applied automatically, I just use the git pre-commit hook so that spotlessApply is run behind the scenes on the files changed prior to the commit. If you are in an environment with access to bash, copy the file `hooks/pre-commit-nix` to `.git/hooks/pre-commit` and make it executable. If you are working in powershell, copy the file `hooks/pre-commit-windows` to `.git/hooks/pre-commit.`

**Comment by lesserwhirls** [comment]
I restarted github actions, and in the time it took me to respond, everything ran again and passed.

**Comment by lesserwhirls** [comment]
Closing, as these commits are part of Unidata/netcdf-java#235 (review of this PR is captured in review of Unidata/netcdf-java#235 as well).

**Pull request closed without merging**
