### PR TITLE
Stop using old CoordSysBuilders from NetcdfDatasets

### PR DESCRIPTION
**Pull request by JohnLCaron**
use internal.DefaultConventions

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/251)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
I dont understand why its failing.

**Comment by lesserwhirls** [comment]
There are a couple of failures that I can see in there (a few because the coordsysbuilder changed, which changed the value of an attribute.

The full JUnit HTML report is supposed to be uploaded to the Github Actions run when something fails, that way the report can be downloaded and inspected (instead of sifting through all of the stuff dumped to standard out)...it's supposed to work that way, but I made a typo, and it doesn't work. If you would not mind, could you changing:

https://github.com/Unidata/netcdf-java/blob/9741f14068936ab7872222b1c83f47f9cefe7089/.github/workflows/tds-check.yml#L28

and

https://github.com/Unidata/netcdf-java/blob/9741f14068936ab7872222b1c83f47f9cefe7089/.github/workflows/tds-check.yml#L37

to use `tds_build_dir`, and not `tds_buil_dir` (dang it Sean, what even is a buil dir anyways?). If you add that change to this PR, then when the TDS check fails, the JUnit html set will be available to download [as a github artifact](https://github.com/actions/upload-artifact#where-does-the-upload-go).

**Comment by JohnLCaron** [comment]
Changed the yml, though it didnt appear to push those files up in this PR. Is that what you expected?

**Comment by lesserwhirls** [comment]
That fixed it. If you visit the Github Actions page for the failing test (click the details link to the right of the failed .github/workflows/tds-check.yml, and it will take you to https://github.com/Unidata/netcdf-java/pull/251/checks?check_run_id=581395675. Once there, there is a dropdown widget about 1/3 down the page on the right (at least on my screen) that says "Artifacts (1)". If you click that, you'll be able to download a zip file containing the test results (https://github.com/Unidata/netcdf-java/suites/592484217/artifacts/4266522).

**Comment by lesserwhirls** [comment]
Failure 1:

`dap4.test.TestCDMClient`  `testCDMClient`
~~~bash
Netcdf-c library version: 4.6.0 of Feb  9 2018 19:21:24 $
pwd=/home/runner/work/netcdf-java/netcdf-java/tds_build_dir/dap4/d4tests
Testcase: add: file:/home/runner/work/netcdf-java/netcdf-java/tds_build_dir/dap4/d4tests/src/test/data/resources/TestCDMClient/testinput/test_enum_array.nc.4.raw  path=/home/runner/work/netcdf-java/netcdf-java/tds_build_dir/dap4/d4tests/src/test/data/resources/TestCDMClient/testinput/test_enum_array.nc.4.raw
...
Testcase: file:///home/runner/work/netcdf-java/netcdf-java/tds_build_dir/dap4/d4tests/src/test/data/resources/TestCDMClient/testinput/test_enum_array.nc.4.raw#protocol=dap4
Baseline: /home/runner/work/netcdf-java/netcdf-java/tds_build_dir/dap4/d4tests/src/test/data/resources/TestCDMClient/baseline/test_enum_array.nc.4.raw.txt
Comparison: vs /home/runner/work/netcdf-java/netcdf-java/tds_build_dir/dap4/d4tests/src/test/data/resources/TestCDMClient/baseline/test_enum_array.nc.4.raw.txt
>>>> 10 CHANGED FROM
  string :_CoordSysBuilder = "ucar.nc2.dataset.conv.DefaultConvention";
>>>>     CHANGED TO
  string :_CoordSysBuilder = "ucar.nc2.internal.dataset.conv.DefaultConventions";
>>>> Dap4 Testing: End of differences.
~~~

Failure 2:

`dap4.test.TestConstraints`  `testConstraints`
~~~bash
Netcdf-c library version: 4.6.0 of Feb  9 2018 19:21:24 $
Testcase: dap4://localhost:8083/d4ts/testfiles/test_one_vararray.nc?dap4.ce=t[1]#protocol=dap4
Baseline: /home/runner/work/netcdf-java/netcdf-java/tds_build_dir/dap4/d4tests/src/test/data/resources/TestConstraints/baseline/test_one_vararray.nc.1.raw.txt
Comparison:
>>>> 7 CHANGED FROM
  string :_CoordSysBuilder = "ucar.nc2.dataset.conv.DefaultConvention";
>>>>     CHANGED TO
  string :_CoordSysBuilder = "ucar.nc2.internal.dataset.conv.DefaultConventions";
>>>> Dap4 Testing: End of differences.
~~~

**Comment by JohnLCaron** [comment]
Appears that there are two failures in dap4, heres one:
````
2020-04-12T23:17:27.0427888Z dap4.test.TestConstraints > testConstraints STANDARD_ERROR
2020-04-12T23:17:27.0428758Z     Netcdf-c library version: 4.6.0 of Feb  9 2018 19:21:24 $
2020-04-12T23:17:27.0568937Z     Testcase: dap4://localhost:8083/d4ts/testfiles/test_one_vararray.nc?dap4.ce=t[1]#protocol=dap4
2020-04-12T23:17:27.0569604Z     Baseline: /home/runner/work/netcdf-java/netcdf-java/tds_build_dir/dap4/d4tests/src/test/data/resources/TestConstraints/baseline/test_one_vararray.nc.1.raw.txt
2020-04-12T23:17:27.7382754Z     Comparison:
2020-04-12T23:17:27.7386760Z     >>>> 7 CHANGED FROM
2020-04-12T23:17:27.7387152Z       string :_CoordSysBuilder = "ucar.nc2.dataset.conv.DefaultConvention";
2020-04-12T23:17:27.7387329Z     >>>>     CHANGED TO
2020-04-12T23:17:27.7387435Z       string :_CoordSysBuilder = "ucar.nc2.internal.dataset.conv.DefaultConventions";
2020-04-12T23:17:27.7387544Z     >>>> Dap4 Testing: End of differences.
2020-04-12T23:17:27.7387592Z 
2020-04-12T23:17:27.7873294Z 
2020-04-12T23:17:27.7874002Z dap4.test.TestConstraints > testConstraints FAILED
2020-04-12T23:17:27.7874311Z     java.lang.AssertionError: ***Fail
2020-04-12T23:17:27.7874582Z         at org.junit.Assert.fail(Assert.java:88)
2020-04-12T23:17:27.7874856Z         at org.junit.Assert.assertTrue(Assert.java:41)
2020-04-12T23:17:27.7875130Z         at dap4.test.TestConstraints.doOneTest(TestConstraints.java:209)
2020-04-12T23:17:27.7875401Z         at dap4.test.TestConstraints.testConstraints(TestConstraints.java:171)
````

However when I run it locally, it apparently works.  Something fishy I dont understand about how those tests are run. I dont see how they are calling the new code, eg NetcdfDatasets.open

**Comment by JohnLCaron** [comment]
Well I cant say thats significantly easier that grepping for failed, but may be helpful sometimes.

Anyway, any idea why it works when i run it manually? Are you able to replicate?

**Comment by JohnLCaron** [comment]
There doesnt appear to be a TestConstraints.java, presumably its a generated class file? or?
There is a TestCDMClient, which if I naively run, works. sooo

**Comment by lesserwhirls** [comment]
Quick question - are you running TestCDMClient out of the Unidata/tds repo?

**Comment by JohnLCaron** [comment]
Im running TestCDMClient from within IntelliJ from dap4.d4tests module.

**Comment by JohnLCaron** [comment]
Im running TestCDMClient from within IntelliJ from dap4.d4tests module, not
tds repo.

**Comment by lesserwhirls** [comment]
Ok, I think I see what's happening now. All the netCDF-Java checks pass for this PR. The thing that's failing is the GitHub Action that does a test of the TDS code using the netCDF-Java code for the PR. The TDS has its own copy of `TestCDMClient`, and is also where `TestConstraints` lives. I've messed with those tests before and have a somewhat good idea how they work. I'm happy to fix those up. Let me get that PR queued up.

**Comment by lesserwhirls** [comment]
Ok...this might take a little while longer. There are changes I've made to the dap4 resource files used used by netcdf-java that need to be moved to the TDS, and there are changes in the dap4 test infrastructure code that need to be ported to use the new cdl writer. I'm close, but it will be tomorrow.

**Comment by lesserwhirls** [comment]
This is very messy (the situation, not this PR). One thing I've found so far is that we have a change in behavior between the old and new default conventions when dealing with structure data. To see this, run `ucar.nc2.dataset.TestCoordSysBuildingProblem` on the following file:

`<path-to-repo>/dap4/d4tests/src/test/data/resources/testfiles/test_struct_array.nc`

Looks like the default conventions used to look through structures to see if it could find `GeoX` and `GeoY`, but the new default convention does not.

The dap4 tests do a lot of comparisons between CDLs, and while the fixes to the convention name attribute are relatively easy to do, some of these failures are more intense, and it's hard to tease out. 

Because of the state of dap4 on both sides (netcdf-java, tds), I've temporarily disabled testing dap4 when we do the netcdf-java check against the tds master. We'll still see these show up on Jenkins though. 

I believe the first thing we need to do to tease this out is replace the use of `NcdumpW` in the `d4tests` project with `ucar.nc2.write.Ncdump`, and get that working. That will probably reveal some missed cases in the new CDL writer.

At any rate, I'm going to merge this in for now to keep things going.

**Comment by JohnLCaron** [comment]
I think the idea is to keep the dap4 tests using the old stuff. Is that
possible?

Ive also seen the problem with assigning axes to things inside of
structures, and will have a look at that.

**Comment by lesserwhirls** [comment]
> I think the idea is to keep the dap4 tests using the old stuff. Is that possible?

The tests can use the old stuff, but the server itself is using the new stuff via `NetcdfFiles` and `NetcdfDatasets`. I can switch that back so that the TDS is only using the old stuff.

**Comment by JohnLCaron** [comment]
Hmmm, maybe so for now, until the new code has parity across the board.

**Comment by lesserwhirls** [comment]
I didn't mean to merge this when I did, but I didn't *not* mean to merge it then either. I put in a fix to have at least dap4 use the old stuff. I had moved other parts of the TDS to use `NetcdfDatasets`, `NetcdfFiles` awhile back, and those tests seem to be working ok. I can see about reverting those new api calls back, but it might not be simple at this point.

**Pull request merged**
