### PR TITLE
fix issues with update existing nc4

### LINKED ISSUE #644: `NetcdfFormatWriter.openExisting` does not work for netCDF4 files.
The nc4Iosp does not correctly support writing to an existing file:

- the location of the ncfile is not used by the iosp, resulting in a null pointer
- the iosp attempts to rewrite existing dimension, variables, and attributes to the file

### PR DESCRIPTION
**Pull request by haileyajohnson**
closes #644 

- sets location property for ncfile in NetcdfFormatWriter (fixes null pointer)
- sets newFile property to false when openExisting is called
- removes call to NetcdfFiles.open within openExisting (rootGroup is now set within nc3iosp._open)
- removes unused line in WritingNetcdfTutorial code snippet

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/645)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Ok, we have to give it a sec. Gradle tried to start up a local server, but the port was already bound from the previous failure.

**Comment by lesserwhirls** [comment]
Actually, you know what we should do? On the test related action jobs, we should tell gradle to force quit any running daemons before running our tests, which would free up the port if it is still open due to a previous failure. In order to do that, change:

~~~
run: ./gradlew --info --stacktrace testAll
~~~

to

~~~
run: ./gradlew --stop && ./gradlew --info --stacktrace testAll
~~~

in `.github/workflows/netcdf-java.yml` for the `tests-zulu` and `tests-adpotopenjdk-hs` job configurations.

**Comment by haileyajohnson** [comment]
hmmm....

**Review by lesserwhirls — APPROVED** [review]
Thank you @haileyajohnson!

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/645#-:-MZHwEL8DTWhzrDZuTBX:bujjhgn)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haileyajohnson)

**Pull request merged**
