### PR TITLE
Cleanup nc2.dataset, part 1

### PR DESCRIPTION
**Pull request by JohnLCaron**
Move CoordTransformFactory, StructurePseudoDS and StructurePseudoDS2D to internal.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/451)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
ready

**Comment by JohnLCaron** [comment]
ready - i think

**Review by lesserwhirls — APPROVED** [review]
> Reviewed 55 of 55 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/451)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lesserwhirls** [comment]
Thanks @JohnLCaron!

**Pull request merged**
